### ISSUE TITLE
[Issue] Date Subtraction

### ISSUE THREAD

**Issue by peteralfafara** [fbaligand/kibana-enhanced-table#1]
Hi fbaligand,

Thank you very much for creating this plugin as this is very useful compared to the standard data table.

I would just like to report an issue, or correct me if my understanding is correct. I'm trying to subtract 2 date fields in order for me to get the hours/minutes between those dates but I've got a a number which I cannot interpret how it got that result

Column 2: **February 13th 2018, 11:45:09.385**
Column 1: **February 12th 2018, 16:06:35.685**
Formula: **col[2] - col[1]**
Result: **70,713,700**

I was expecting a number similar to the following then I would just need to do some calculations for me to get the minutes:
Desired Result: **0.818449074074074074074074074074074074074**
Formula: **(col[2] - col[1]) * 24 * 60**
Actual Result: **1178.567**

Regards,
Peter

**Comment by peteralfafara** [comment]
Just realized that the result was in milliseconds. Closing the issue

**Comment by fbaligand** [comment]
Hi @peteralfafara 
Happy to see you appreciate the plugin !
