### ISSUE TITLE
How to compute the CTR?

### ISSUE THREAD

**Issue by wjguo2002** [fbaligand/kibana-enhanced-table#10]
Dear
  I got log from application, have the field action it values is in { expose and click}, i can stats by metric-count and bucket-action get the expose count and click count. I need a CTR = click / expose, I use formula col0/col1 is not work. 

can you help me resove the issue?
thanks

**Comment by fbaligand** [comment]
Well, said like that, I miss information to give you help. 
Could you give more details ?
Maybe a screenshot of computed columns editor and visualization ?

**Comment by wjguo2002** [comment]
a example, i get some logs:
uid:1000,time:20180814,action:expose
uid:1000,time:20180814,action:click
uid:1001,time:20180814,action:expose
uid:1001,time:20180814,action:click
uid:1002,time:20180814,action:expose
uid:1003,time:20180814,action:expose
uid:1004,time:20180814,action:expose
uid:1004,time:20180814,action:expose

I aggregate by action.
I can get how many counts for action is expose or click
now I need get the CTR = click count div expose count.
the action expose count is:6, click is 2; the CTR = 2/6 = 0.33

thank you.

**Comment by fbaligand** [comment]
Hi @wjguo2002 ,

Here's how you can do that : 
- create a "Max Bucket" metric aggregation, with Sub Aggregation "Filters" and filter 1 equals to "action:click"
- create a "Max Bucket" metric aggregation, with Sub Aggregation "Filters" and filter 1 equals to "action:expose"
- add a computed column, which expression is "col0/col1"
- in "hidden columns", set "0,1" (to hide the first and second columns)
- it should answer your need !

**Comment by fbaligand** [comment]
I close the issue, as question is answered and there is no feedback since about 2 months.
