### ISSUE TITLE
Feature-Request: add the ability to use computed totals

### ISSUE THREAD

**Issue by yjaigu** [fbaligand/kibana-enhanced-table#100]
Add an option to use a formula to compute the total of a column.
Example : I have the last column with a formula (1- (col2 / col1)) that computes a percentage and I would like to be able to compute the total with the same formula.
Actually, I have 151.8% as a total (because the total function is sum) instead of 1-15.9/938.47=98,3%.

![screenshot total enhanced-table](https://user-images.githubusercontent.com/581324/78646003-b38e8980-78b8-11ea-9343-3a59b97dd672.png)

**Comment by fbaligand** [comment]
Good idea

**Comment by fbaligand** [comment]
I don't promise, but I will try to add it to next release.

**Comment by fbaligand** [comment]
Thus, it is the #100 issue :)
It requires a special attention :)

**Comment by yjaigu** [comment]
Thanks, good news!
And I didn't pay attention to the number: it is an honour :)

**Comment by umarfachreza** [comment]
wow this good idea, i had same problem,

**Comment by fbaligand** [comment]
I can confirm you that I have implemented the feature and so, it will be available in next release!

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with ‘use formula to compute total’ option in computed columns, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0

**Comment by yjaigu** [comment]
Hi

Thanks a lot!

Yann

**Comment by fbaligand** [comment]
You’re welcome 😉

**Comment by umarfachreza** [comment]
i had install it, but i cannot find the compute total. can u demo how to do it?

**Comment by fbaligand** [comment]
Well, in the computed column editor, there is a checkbox “compute total using formula”
