### ISSUE TITLE
kibana web can not be open.Can't resolve 'plugins/enhanced-table/enhanced-table-vis-hack' in '$KIBANA_HOME/kibana-7.1.1-linux-x86_64/src/optimize'

### ISSUE THREAD

**Issue by Niidy** [fbaligand/kibana-enhanced-table#101]

**Comment by fbaligand** [comment]
Well, this issue is weird.
I mean : $KIBANA_HOME/kibana-7.1.1-linux-x86_64/src/optimize doesn't exist.
The right folder is $KIBANA_HOME/kibana-7.1.1-linux-x86_64/optimize

Which enhanced-table version did you install ?
Did you follow install guide? (https://github.com/fbaligand/kibana-enhanced-table#install)

**Comment by Niidy** [comment]
![image](https://user-images.githubusercontent.com/45956136/78895673-d3cd6c80-7aa1-11ea-82c3-7dff91263e20.png)

After I install this plugin and restart kibana, I wanna open the kibana web. but when I open web page, kibana process crash.

![image](https://user-images.githubusercontent.com/45956136/78895889-2870e780-7aa2-11ea-8daf-5ec64b93dfbc.png)

**Comment by Niidy** [comment]
> Well, this issue is weird.
> I mean : $KIBANA_HOME/kibana-7.1.1-linux-x86_64/src/optimize doesn't exist.
> The right folder is $KIBANA_HOME/kibana-7.1.1-linux-x86_64/optimize
> 
> Which enhanced-table version did you install ?
> Did you follow install guide? (https://github.com/fbaligand/kibana-enhanced-table#install)

Ihave successfully installed the plugin, as shown in the figure on the 3rd floor

**Comment by fbaligand** [comment]
Thanks for the screenshots.

Can you try to :
- stop kibana
- remove $KIBANA_HOME/optimize
- remove $KIBANA_HOME/plugins/enhanced-table
- install again enhanced-table 1.8.0
- start kibana

The important point is "remove $KIBANA_HOME/optimize"

**Comment by Niidy** [comment]
> Thanks for the screenshots.
> 
> Can you try to :
> 
> * stop kibana
> * remove $KIBANA_HOME/optimize
> * remove $KIBANA_HOME/plugins/enhanced-table
> * install again enhanced-table 1.8.0
> * start kibana
> 
> The important point is "remove $KIBANA_HOME/optimize"

thanks for ur answer，but It's the same after I tried.  I don't  know what r [plugins/enhanced-table/enhanced-table-vis] and [plugins/enhanced-table/enhanced-table-vis-hack], where can I found them.

**Comment by fbaligand** [comment]
After you install, could you list the files into: 
- KIBANA_HOME/plugins/enhanced-table
- KIBANA_HOME/plugins/enhanced-table/public

Could you show also content in: KIBANA_HOME/plugins/enhanced-table/package.json

**Comment by Niidy** [comment]
> After you install, could you list the files into:
> 
> * KIBANA_HOME/plugins/enhanced-table
> * KIBANA_HOME/plugins/enhanced-table/public
> 
> Could you show also content in: KIBANA_HOME/plugins/enhanced-table/package.json

thank u for ur answer ,I download src code, and  check my enhanced-table-1.8.0_7.1.1.zip . I found that some of the files were damaged during the download process. I changed my browser and downloaded the files again. Now I have started to learning how to use the plugin. ty!

**Comment by fbaligand** [comment]
Well, it is important to not download directly the sources from git, but to download the relevant package for your Kibana version here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.8.0
