### ISSUE TITLE
Is it possible to achieve subtotals with the enhanced table?

### ISSUE THREAD

**Issue by gferrette** [fbaligand/kibana-enhanced-table#102]
Hello!

First of all congratulations for this plugin!

I'm wondering if it's possible to achieve subtotals for the table, for example, with every bucket level display the result subtotals.

Is it possible?

Thanks in advance!

**Comment by fbaligand** [comment]
Hi,

Yes, you can do it!
Go to "Options" tab and check "Show metrics for every bucket/level" checkbox.
