### ISSUE TITLE
Can't reference columns with derivative aggregation

### ISSUE THREAD

**Issue by adrienyhuel** [fbaligand/kibana-enhanced-table#103]
I have a datatable with columns computed with derivative aggregation metrics.

When I reference those colmuns, ethier by number (col1) or name (col['xxx']), there is a javascript error : 
```
vendors.bundle.dll.js:441 Error: undefined variable: col1
    at evaluate (commons.bundle.js:3)
    at Expression.evaluate (commons.bundle.js:3)
    at computeFormulaValue (commons.bundle.js:3)
    at createComputedCell (commons.bundle.js:3)
    at commons.bundle.js:3
    at arrayEach (vendors.bundle.dll.js:32)
    at Function.<anonymous> (vendors.bundle.dll.js:32)
    at commons.bundle.js:3
    at arrayEach (vendors.bundle.dll.js:32)
    at Function.<anonymous> (vendors.bundle.dll.js:32) 
```

I use Kibana 6.8.6, with plugin version 1.8.0.

Maybe is it because with derivative the first line values are always "undefined" (derivate is calculated with value from previous line) ?

**Comment by fbaligand** [comment]
Hi,

Indeed, this is probably the cause. 
Il will try to find a solution for next release.

**Comment by fbaligand** [comment]
In next release, there will be a new function available in computed column formula: `getColOrDefault`

So you will be able to do this:
`getColOrDefault('Derivative of Count', 0)`

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with `col(indexOrLabel, defaultValue)` function, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
