### ISSUE TITLE
Feature request: Metric aggregation on split column

### ISSUE THREAD

**Issue by kimjavier43** [fbaligand/kibana-enhanced-table#104]
Metric and filter aggregation can be mixed up in elastic query so I assume it is possible on split columns but it seems not. I tried to accomplish the average metric but only filters are available.

BR,
Kim

**Comment by fbaligand** [comment]
Well, basically, “split cols” is a bucket like “Split rows“. So metrics aggregations are available per “split col”.  If you add a “average” metric, you will get in result table, “average” metric for each split column.
That said, if I understand well, you wish the average of all split cols?

**Comment by kimjavier43** [comment]
My first metric is a count not average then split row and split col is applied so it's not avg per split col and not about computed cols. I already made multiple columns of filters and I want to add a single avg bucket but there's no options. Not sure of this is by design on kibana but I can accomplish mixed buckets of filters and avg on elasticsearch query.

**Comment by kimjavier43** [comment]
I'm on 7.1.1 anyway.

**Comment by kimjavier43** [comment]
Think of the avg_price as the column. Can this be done?

`POST /sales/_search?size=0
{
    "aggs" : {
        "t_shirts" : {
            "filter" : { "term": { "type": "t-shirt" } },
            "aggs" : {
                "avg_price" : { "avg" : { "field" : "price" } }
            }
        }
    }
}`

**Comment by fbaligand** [comment]
Well, several points:
- average is not a bucket aggregation, but a metric aggregation. In kibana, you can define avg only as a metric
- concretely, on elasticsearch query, first, bucket aggregations are applied, then metric aggregations
- globally, in kibana visualizations, you cannot do all the complicated elasticsearch combined aggregations, whatever the visualization
- That said, to be able to compute split cols average, I will add two new computed column functions: sumPlitCols and countSplitCols. Thanks to this, you will be able to compute all split cols average.

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with sumSplitCols() and countSplitCols() functions and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
