### ISSUE TITLE
Calculate Growth Tax

### ISSUE THREAD

**Issue by rgoliveirati** [fbaligand/kibana-enhanced-table#105]
Hello! How could you calculate the growth rate according to the image?

![image](https://user-images.githubusercontent.com/45003762/80863025-acf0f900-8c4f-11ea-8f3d-2f0af96b6fe1.png)

**Comment by fbaligand** [comment]
Hi,

To have "Offset Growth Tax" column equivalent in enhanced-table, you add a computed column with this formula: `col2/(col1-col2)`
Then set 'Number' Format, and '0 %' Pattern.

**Comment by rgoliveirati** [comment]
Hello! Thank you very much for the answer, but column 2 is Serial Diff aggregation having the metric column 1. So when I create the computed column col2 nothing happens. Please see the images. Thank you!

![image](https://user-images.githubusercontent.com/45003762/80865004-ccdae980-8c5c-11ea-8948-da837b41f652.png)

![image](https://user-images.githubusercontent.com/45003762/80865013-df552300-8c5c-11ea-90b5-abc10e88510b.png)

![image](https://user-images.githubusercontent.com/45003762/80865038-07dd1d00-8c5d-11ea-81ac-6616cf479dc8.png)

![image](https://user-images.githubusercontent.com/45003762/80865053-204d3780-8c5d-11ea-8048-15fe14faf23d.png)

**Comment by fbaligand** [comment]
OK, I forget one point: first line has no value for col2, because it is a Serial Diff aggregation.
So, you have to wait next release, where a new function will be available: `getColOrDefault`

And so, you will be able to do this formula:
`getColOrDefault('Derivative of Count', 0) / (col1 - getColOrDefault('Derivative of Count', 0))`

**Comment by rgoliveirati** [comment]
OK! When will we have this new version? This plugin is fantastic! Thank you one more time!

**Comment by fbaligand** [comment]
I will release it after kibana 7.7 is out and that I make the plugin compatible with kibana 7.7

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with `col(indexOrLabel, defaultValue)` function, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
