### ISSUE TITLE
Ternary conditional Support on Column formula

### ISSUE THREAD

**Issue by karnamonkster** [fbaligand/kibana-enhanced-table#107]
Hi,

Setup: Elasticsearch/Kibana v 7.5.2 | Plugin: 
Great work with the plugin.. 
I am trying to plot a range with colors on the value feild.
value< 0.15 ## column value with RED color
value>1.5 ## column value with YELLOW color
0.15>value<1.5 ## column value with GREEN color

This worked fine for me, just that i need that extra Yellow to show along with red & green
`col2>0.15? 'green': 'red'`

**Comment by karnamonkster** [comment]
I believe i fixed it, Thanks again to your documentation 
Here it is 
col2<0.15? 'red': 'green' and 1.5>col2>0.15? 'green': 'yellow'

Would welcome a better way to do though

**Comment by fbaligand** [comment]
Hi,

This is the formula that I advice for your need:
`col2<0.15 ? 'red' : (col2>1.5 ? 'yellow' : 'green')`

**Comment by karnamonkster** [comment]
Worked like a charm! Thanks so much for that.
Not sure if i should continue with one more question, regarding the decimal precision
The value returned should be upto 3 decimal points.
Desired: 1.825
Computed column: 1.8246377548692734

Attached is the snapshot for your reference
![enhanced_q1](https://user-images.githubusercontent.com/5524898/81532694-df98a100-9375-11ea-8680-bc12ab2c9e11.PNG)

**Comment by fbaligand** [comment]
Well, to have the expected column format, I invite you to:
- have a first computed  column named color and no template
- have a second computed column named “daily avg-FV”, with formula “col2”, “Number” format, “0,0.000” pattern, and this template:
`<span style=“color: {{col3}}”>{{value}}</span>`
- have `3` in “hidden columns” field (to hide the color)

**Comment by karnamonkster** [comment]
Perfect, however the <span> did not work for me.
Managed to get that sorted with this
`<div style="color:{{col4}}">{{value}}</div>` 

Thanks for all the help @fbaligand . Happy to close the issue

**Comment by fbaligand** [comment]
Nice to see that it finally works as you expect!
