### ISSUE TITLE
Support Kibana 7.7.0

### ISSUE THREAD

**Issue by bard0x** [fbaligand/kibana-enhanced-table#108]
Add support to Kibana 7.7.0.

Thank's in advance

**Comment by fbaligand** [comment]
Hi, 

This enhancement is planned for next release.

**Comment by lucaszc** [comment]
Do you have a estimated date from this release ?? Regards

**Comment by fbaligand** [comment]
Hi @lucaszc,

Kibana 7.7 brings several breaking changes for community plugins.
I fix one after the other.
I currently work on a very big one.
That's why, unfortunately, I can't give you a date.
But once it will be available, be sure that I will notify you in this issue.

**Comment by bard0x** [comment]
> Hi @lucaszc,
> 
> Kibana 7.7 brings several breaking changes for community plugins.
> I fix one after the other.
> I currently work on a very big one.
> That's why, unfortunately, I can't give you a date.
> But once it will be available, be sure that I will notify you in this issue.

Thank you man. You rocks!

**Comment by anush0247** [comment]
+1 looking for this feature

**Comment by fbaligand** [comment]
I’m currently working on visualization editor migration from angularjs to reactjs. This migration is required for kibana 7.7. 
It takes some time, but I progress well.

**Comment by bard0x** [comment]
> I’m currently working on visualization editor migration from angularjs to reactjs. This migration is required for kibana 7.7.
> It takes some time, but I progress well.

The migration from angularJs to reactJs is only for the visualization editor or for the entire plugin?

**Comment by fbaligand** [comment]
Hi @bard0x 

It is only visualization editor

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with Kibana 7.7 support, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
