### ISSUE TITLE
DateDiff of the Time Range Selector (top right of Kibana)

### ISSUE THREAD

**Issue by JZ-SmartThings** [fbaligand/kibana-enhanced-table#109]
Hi, and apologies for throwing more of a question into here... didn't see any documented question arena.

The question is very pertinent though: is there ability to calculate datediff on the time range selector of Kibana? Number of days is the last piece I'd need to be able to auto-calculate (w/o copy past to Excel) power usage for the month (which ranges in number of days).

Awesome plugin, so thankful somebody recommended it, thank you for sharing it!

**Comment by fbaligand** [comment]
Hi,

Nice to see that you appreciate the plugin :)

Concerning your need, currently, this is not available. 
But it could be an enhancement.

**Comment by JZ-SmartThings** [comment]
@fbaligand thank you for considering this and most definitely appreciating the plugin... one more question and possibly another enhancement that I'll enter... notice the unbound/free-form total fields at the bottom of my spreadsheet. Do you have any capability of adding these "unbound" fields which I can use to populate with the same formula abilities that you offer in the plugin. Meaning if I don't want to settle for table grand totals and would rather calculate something crazy myself, etc.

![image](https://user-images.githubusercontent.com/16831042/82127793-1c480c00-976b-11ea-8661-ad755474fb6b.png)

**Comment by fbaligand** [comment]
Well:
- in a computed column, you can get hits count returned by current elasticsearch query: `total`
- in a computed column, you can get the total of a previous column: `total1` is the total of column no 1 (0-based indice)
- in next release (1.9.0), you will be able to use computed column formula to compute the column total. 
- but add some extra totals outside of the table is not possible (as you have at bottom of your spreadsheet)

**Comment by JZ-SmartThings** [comment]
You're awesome, thank you for helping me out @fbaligand!

**Comment by fbaligand** [comment]
You’re welcome ;)

**Comment by toog** [comment]
:+1: to have access to time picker value

**Comment by fbaligand** [comment]
Well, I mean a 👍 reaction on issue description.

**Comment by JZ-SmartThings** [comment]
@toog click the smiley face on my first post and pick the thumbs-up emoji.

**Comment by toog** [comment]
It’s done, sorry

**Comment by fbaligand** [comment]
Hi, 
I just published Enhanced Table v1.11.0! And it includes a `timeRange` variable with infos on "start" date, "to" date, and interval "duration".

More info on `timeRange` variable here:
https://github.com/fbaligand/kibana-enhanced-table#available-variables

More info on release here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.11.0

**Comment by JZ-SmartThings** [comment]
@fbaligand you're a beast! :) I had no idea you'd actually do this but this is awesome. The only other cherry on top would be to have unbound fields where you can do whatever you want like averages, min/max, totals at the bottom that make sense for some chart in question. Thanks again for taking it up a notch and getting me even closer to that Excel chart I originally pasted above,

**Comment by fbaligand** [comment]
Hi,

Happy to see that you appreciate my work on this plugin :)

Concerning your new feature request, I'm not sure to understand it. 
Is it tied to "time range"? 
Could you give more details?
Could you open a new issue, as this is a new feature?

**Comment by JZ-SmartThings** [comment]
@fbaligand see bullet 4 on your reply here: https://github.com/fbaligand/kibana-enhanced-table/issues/109#issuecomment-629757517

Let me know if that's feasible in any way and I'll certainly open a new feature request. You mentioned above that it's not possible.

**Comment by toog** [comment]
Thank's a lot for this gift :-) @fbaligand.

**Comment by fbaligand** [comment]
Happy that you appreciate @toog :)

**Comment by fbaligand** [comment]
@JZ-SmartThings 
Well, I can't promise you that I will implement the feature a day, but technically, this is possible to implement.
Not for Kibana 6, but it is possible for Kibana 7.x.
So I invite you to create a separate issue for that.

Then, I would like an explanation of how you compute the bottom totals.
I don't understand how they are computed, given the table above.

**Comment by JZ-SmartThings** [comment]
@fbaligand fully understood, thanks again for everything!
