### ISSUE TITLE
Enhanced table slow in response

### ISSUE THREAD

**Issue by anandgavai** [fbaligand/kibana-enhanced-table#11]
if the number of rows (50000) and columns (12) increase in size it take a lot of time to load the data. This problem exists within Kibana data tables is there a way to optimize this ? 

Alternatively if we use saved search from Discover within dashboard the response is lightining fast, however there is no way to download this data, any suggestion to deal with this would be great !

**Comment by fbaligand** [comment]
Well, As you probably guessed, enhanced table is a fork of standard « data table », with its strengths and flaws. 

Concerning your issue, I guess you don’t really do aggregations, but rather you list 50,000 documents, right ?
Data tables as enhanced table do aggregations, which is not performant when you do 13 sub aggregations with 50,000 terms. 
In my tests, this is both not performant on elasticsearch response and kibana display. 
But you can look at spy in visualization to see what is Elasticsearch response performance part. 

On the contrary, discover makes a simple search query, with no aggregations. That’s why it’s way more performant. 
If you use kibana 6.3, you probably have package with xpack (default distribution). 
So in discover app, there is a “reporting” menu, where you can download data in csv format. I precise that this feature is free (included in xpack basic). 
So I suggest you to test this feature.

**Comment by fbaligand** [comment]
I close the issue, as there is no answer since more than 2 months.
