### ISSUE TITLE
How can I hide data metric column when using split columns

### ISSUE THREAD

**Issue by hoberhol** [fbaligand/kibana-enhanced-table#110]
Hi 

Is there a  way to hide the data metric column and only show the computed column when using the split columns feature?

I would like to show weekly values for a certain period and using for this the split collumns feature with  a Data Histogram sub aggregation. I can create a computed column to e.g. format my sum metric value and also display this value for each week with the feature "Computed/Hidden cols per split col". 
But now I would like to only show this computed values and not the default data metric columns. When I try to configure this with the feature "Hidden columns" it is not working and always showing both values for each week.

Is there a way to do this?

Thanks a lot for your support.

**Comment by fbaligand** [comment]
Normally, when you check "Computed/Hidden cols per split col", you can add a computed column for each split column, and hide the original column.
I already did that.

Can you put here some screenshots? "Data" tab, "Options" tab and rendered table ?

**Comment by hoberhol** [comment]
Please see my config and the result below.

As you can see it is showing always both values the original and the computed one.
I also tried to specify the hidden column as "Col1" or 1, no luck.

Thanks for your help.

Config:

![ext_table_config1](https://user-images.githubusercontent.com/65902724/82940411-0f11f500-9f95-11ea-8e0a-f6719f66390d.png)

Result:

![ext_table_result](https://user-images.githubusercontent.com/65902724/82940427-19cc8a00-9f95-11ea-8b2d-f8542b68ae4c.png)

**Comment by fbaligand** [comment]
Hi,

In "Hidden columns", you have to write only: `count`.
As indicated in the placeholder and in the tooltip (question icon on the right) ; if you want to reference a column by its label in "Hidden columns", you have to write column label as is.

**Comment by hoberhol** [comment]
Hi 
Yes, this way is is working correctly.
It would help to read the help text until the end... sorry for bothering....

Thanks a lot and also thanks a lot for the great work on this plugin.

Regards,
Hans

**Comment by fbaligand** [comment]
Nice to see that it finally works!
And nice to see that you appreciate my work on this plugin! ;)

**Comment by GOPALAKRISHNAYM** [comment]
Hi,
i have want to just to apply background colour for entire cell, how can i achieve this.
Thank you.

**Comment by fbaligand** [comment]
@GOPALAKRISHNAYM
This is quite a different question, that should be another issue.
Anyway, in computed column, use "Cell computed CSS" setting and set something like: `"background-color: red"`
