### ISSUE TITLE
Kibana 7.8

### ISSUE THREAD

**Issue by edmarmoretti** [fbaligand/kibana-enhanced-table#111]
Add support to Kibana 7.8.0.

**Comment by tonykoval** [comment]
+1

Check https://www.elastic.co/guide/en/kibana/current/breaking-changes-7.8.html#general-plugin-API-changes-78

**Comment by fbaligand** [comment]
Hi all,

Just to say you that 7.8 compatibility development is started. 
Stay tuned.

**Comment by fbaligand** [comment]
enhanced-table v1.9.1 is out, with Kibana 7.8 support!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.1
