### ISSUE TITLE
New Version for Kibana 7.8.0

### ISSUE THREAD

**Issue by 98chris** [fbaligand/kibana-enhanced-table#114]
How can I install enhanced-table for kibana 7.8.0, will be there a new version for it or do I have to change the 1.9.0 Version with the new files from the Master Version?

**Comment by jamesharr** [comment]
1.9.0 is not compatible with Kibana 7.8.0, however code is merged into master (see #111 and #113) less than 24hr ago.

@fbaligand are you planning to do a point release for this?

**Comment by fbaligand** [comment]
Yes, for sure!
I will try to do the release tomorrow.
Tonight, I fixed a bug.

**Comment by fbaligand** [comment]
enhanced-table v1.9.1 is out, with Kibana 7.8 support!
