### ISSUE TITLE
The plugin isn't showing up (Kibana 7.8)

### ISSUE THREAD

**Issue by haiounj** [fbaligand/kibana-enhanced-table#117]
Hi,

I just installed enhanced-table on kibana 7.8 and the installation has been done well and when I launch kibana I can see the log message say enhanced-table is ready. However, I can't find the enhanced table in the visualization selector.

![Annotation 2020-07-15 125146](https://user-images.githubusercontent.com/45619942/87536797-f9b66e80-c699-11ea-82a8-d43a88ac964f.png)

![Annotation 2020-07-15 125246](https://user-images.githubusercontent.com/45619942/87536924-1eaae180-c69a-11ea-9b95-944c7e0694bb.png)

Thanks in advance for your help.

**Comment by tonykoval** [comment]
Try incognito mode or delete cached images and files in a browser

**Comment by haiounj** [comment]
Thank you delete cached images and files worked well !

**Comment by fbaligand** [comment]
Thanks @tonykoval for your help here!
