### ISSUE TITLE
Enhanced table only showing metrics when used on a dashboard (on Kibana 7.8.0)

### ISSUE THREAD

**Issue by lucasSimonelli** [fbaligand/kibana-enhanced-table#118]
Hey, I've recently upgraded to 1.9.1 (kibana 7.8.0) from 1.5.0 (with kibana 7.3.2). The tables look great when setting them up / looking at them in the 'Visualization' screen. I can also add them to a dashboard and they look fine.

However, when I refresh the dashboard page, the table only shows the metric, with none of the split rows i've set up:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/5222378/87563572-c70a7700-c695-11ea-9b8d-24e700ac5528.png">

No errors / warnings are displayed in the browser's console. Any clue what could be going on?

**Comment by tonykoval** [comment]
We have the same issue (Kibana 7.8.0, enhanced table plugin 1.9.1)

**Comment by fbaligand** [comment]
Hi,
I close this issue, as it is a duplicate of #116
