### ISSUE TITLE
Docs in query response are not shown in table.

### ISSUE THREAD

**Issue by dantete** [fbaligand/kibana-enhanced-table#12]
Very nice plugin! Thanks! 
But i notice un weird behaviour. Sometimes, some docs are not shown in the table. 

- Index with total 56 docs. 
- Between 2018/07/01 and 2018/08/08

- Intervals Weekly work perfect.
![screen shot 2018-08-08 at 12 04 51 pm](https://user-images.githubusercontent.com/4230552/43850217-58ddd078-9b05-11e8-89bb-52591772ac9a.png)

- Intervals Daily don't work. (day 2018/07/18 hidden in table and sum)
![screen shot 2018-08-08 at 12 11 42 pm](https://user-images.githubusercontent.com/4230552/43850836-0caae7b6-9b07-11e8-9c90-45fb84e5be34.png)
Notice that docs are in query response, but are not in table. 
I must show result Daily.

Any idea or suggestion for this case?
Thanks!...

**Comment by dantete** [comment]
Tested with: 
- enhanced-table-0.7.1_6.3.2.zip
- enhanced-table-0.7.0_6.2.3.zip

**Comment by dantete** [comment]
With standard kibana data table works perfect, show days correctly.

The problem happen when Split Cols is enabled. 

- Split Cols: DISABLE (show days correctly)
![3](https://user-images.githubusercontent.com/4230552/43866039-66d0fb06-9b32-11e8-9b07-8fa44ec052c0.png)

- Split Cols: ENABLE (day 2018/07/18 hidden )
![4](https://user-images.githubusercontent.com/4230552/43866061-87c30138-9b32-11e8-95b7-ff47ba2c77fd.png)

**Comment by fbaligand** [comment]
Thanks for this important precision. 
Well, no doubt here: it’s a bug. 

So that I can reproduce your issue, could you provide some data and your visualization document (available in management) ?

**Comment by fbaligand** [comment]
Could you test if you reproduce the issue with version 0.6.0 ?
I did a massive change on split cols in 0.7.

**Comment by dantete** [comment]
> So that I can reproduce your issue, could you provide some data and your visualization document (available in management) ?

I think that a snapshoot of the index is a good option. Also the .json of the kibana visualization. I can share you with a GDrive link... it is OK ?

> Could you test if you reproduce the issue with version 0.6.0 ?

ok. i going to test and post the results. 

Regards....

**Comment by fbaligand** [comment]
Yes, a gdrive link is nice.

**Comment by dantete** [comment]
> Could you test if you reproduce the issue with version 0.6.0 ?
> ok. i going to test and post the results.

I tested enhanced-table-0.6.0_6.2.3.zip
{
  "name": "enhanced-table",
  "version": "0.6.0",
  "description": "...",
  "main": "index.js",
  "kibana": {
    "version": "6.2.3"
  },

Same results as:
enhanced-table-0.7.1_6.3.2.zip
enhanced-table-0.7.0_6.2.3.zip

**Comment by fbaligand** [comment]
Ok, thanks for the test and the feedback. 
Sorry it doesn’t give you a workaround, waiting the fix.

**Comment by fbaligand** [comment]
Thanks for the link and the infos. 
I will try to reproduce the issue and will give you feedback.

**Comment by fbaligand** [comment]
Just for info, I’m currently on hollidays, so I won’t start to fix the issue before next week. 
Sorry for the delay.

**Comment by fbaligand** [comment]
Hi, I just tried to untar your elasticsearch backup, and it fails. It looks like it is not a tar file.
Do you have an idea about ?

**Comment by dantete** [comment]
HI! :D. 
i tried to untar in other linux pc and works, so i dont know...
Anyway i uploaded a .zip file in the same GDrive link. 

can you check please? 
Thanks.

**Comment by fbaligand** [comment]
I just downloaded the zip file, and now it works.
I finally understood what was the problem with the tar file : it's not a tar archive, but a tar.gz archive.

**Comment by fbaligand** [comment]
Hi @dantete 

I finally managed to import your data : I struggled with it because your indices require that elasticsearch node has `box_type: hot` attribute...

So the good news : I managed to reproduce your issue.

**Comment by dantete** [comment]
hi @fbaligand! 
how things are going with this issue? 
Anything let me know or if you need more information or maybe some test in my environment.

greetings, thanks.

**Comment by fbaligand** [comment]
Hi @dantete,

I'm currently working to make enhanced-table compatible with Kibana 6.4.
Then, I will try to your issue.
Sorry for the delay...

**Comment by fbaligand** [comment]
Hi @dantete, 

enhanced-table plugin v0.8.0 is out with support for multiple preceding 'Split Rows' buckets (before a 'Split Cols' bucket) ! 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.8.0

**Comment by dantete** [comment]
Awesome!!
I tested in Kibana 6.2.3 and it's working perfectly! 

Thanks a lot!

**Comment by fbaligand** [comment]
Great to hear it !
Happy you enjoy it ! :)
