### ISSUE TITLE
Enhanced table showing 0 for metrics that doesn't exist.

### ISSUE THREAD

**Issue by gagawapa** [fbaligand/kibana-enhanced-table#120]
Hi,

Great plugin that solves the painful limitation of the original data table.

From the screenshot attached, the "0" are actually "rows" that doesn't exist.
Is there a way to hide them instead of showing "0" ?
I'm using the top hit aggregation.

![image](https://user-images.githubusercontent.com/37303822/88031898-d004b800-cb6f-11ea-89fc-f8ea2cfca0b7.png)

The version im using is 1.9.1 on kibana 7.5.1

Thank you!

**Comment by fbaligand** [comment]
You can eventually use “computed filter” setting, with “col1 > 0”

It will show only table lines where the second column is superior to 0.

**Comment by fbaligand** [comment]
But to be sure to understand your case, could you explain or screenshot the different buckets and metrics you have?

**Comment by gagawapa** [comment]
![image](https://user-images.githubusercontent.com/37303822/88123545-ad20e500-cbfd-11ea-98e7-557634ea5e75.png)

Thanks for getting back.
I just noticed that by omitting the column header would make it harder to understand the picture.

If you look at the new screenshot above, the values that I marked with the green box are the values that actually exist, while the one outside of the box are values that doesnt exist but the visual decides to set their "default/missing" values as 0..

I'm attaching the original kibana visual to show the values that doesnt exist.
![image](https://user-images.githubusercontent.com/37303822/88123799-405a1a80-cbfe-11ea-926c-b63cadac4a56.png)

**Comment by fbaligand** [comment]
Hi,

So given your screenshot, I guess that you use one 'Split Rows' bucket and then one 'Split Cols' bucket. Right?

If so, 'Split Cols' bucket adds as many columns as there are values for all rows. And so, for one row, if there is no value for one column (one bucket term value in your case), 'Split Cols' has to put a default value. And as you noticed, default value is `0`.

What would you want instead of `0`?

**Comment by gagawapa** [comment]
Yes, you are right about that.

If possible, I would like to have "empty" in the display.
For this particular use case, we are using the number to tell the users about the number or errors for each category.

So, having `0` as the default value here would confuse the users, as the record doesn't even exist. We want to be able to differentiate a true `0` and record that doesn't exist.

**Comment by fbaligand** [comment]
OK. I understand your need. 
So I think a nice enhancement would be to add a “split cols default label” setting in visualization editor that lets you customize default label. Concretely, value will still be 0, but display will be customized label. It is important to keep a numeric value, especially when you have a total line. 

So could you open an issue that requests a “split cols default label” feature?

**Comment by gagawapa** [comment]
Yes. That's great. I'll go ahead and open a new issue.

Just want to confirm that we are on the same page, the default label will only apply to the value when it's empty right? Otherwise, it will show the actual number.

**Comment by fbaligand** [comment]
Yes, we are on the same page ;)

**Comment by gagawapa** [comment]
Thank you!
