### ISSUE TITLE
Can't add visualization to Canvas

### ISSUE THREAD

**Issue by JackCloudman** [fbaligand/kibana-enhanced-table#123]
Hello, I tested the plugin(v1.9.1) for kibana 7.8 and i want add my document table to canvas, but when i search elements dont return results

Visualize: 
![image](https://user-images.githubusercontent.com/17970185/88565412-2e131e80-cffa-11ea-91d1-64dd6adac1b9.png)

Canvas:
![image](https://user-images.githubusercontent.com/17970185/88565471-47b46600-cffa-11ea-88f5-92345aa1bf5c.png)

**Comment by fbaligand** [comment]
Hi,

Honestly, I didn’t tried this feature yet.
If you add a standard data table, does it work fine?

**Comment by JackCloudman** [comment]
Yes it works with standard kibana visualizations, i don't know if is necessary a tag that enable discover it in canvas tab.

**Comment by fbaligand** [comment]
Well, it seems that something special is required so that a visualization can be added in canvas (given your tests). 
For now, I don’t know what, but I will ask the question to kibana team.

**Comment by fbaligand** [comment]
Good news: enhanced table v1.10.0 is out with this issue fixed for Kibana 7.9+ and more enhancements!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0
