### ISSUE TITLE
Fresh install of Kibana 7.8.0, no table menu

### ISSUE THREAD

**Issue by alaindixon** [fbaligand/kibana-enhanced-table#124]
Hi

I have installed the plugin, I can't see the menu.
Do you know why ?

<img width="420" alt="Capture d’écran 2020-07-28 à 09 18 53" src="https://user-images.githubusercontent.com/5199552/88632071-66c2fe80-d0b3-11ea-84d4-9bb262286e57.png">

<img width="801" alt="Capture d’écran 2020-07-28 à 09 18 01" src="https://user-images.githubusercontent.com/5199552/88631974-485d0300-d0b3-11ea-8ac3-cf63a3c32c12.png">

Alain

**Comment by fbaligand** [comment]
Could you precise what menu you speak about?

**Comment by alaindixon** [comment]
Sorry, I mean the fields to setup the columns to make a division. 
I can see any fields.

**Comment by fbaligand** [comment]
Ok. It seems you clicked on “Data Table” visualization. 
Enhanced table is another visualization. 
So in “create visualization” screen, I invite you to choose “Enhanced Table”.

**Comment by alaindixon** [comment]
Thank you very much, I did not realize that I have to use another Widget.

**Comment by fbaligand** [comment]
You’re welcome 💯
