### ISSUE TITLE
Disable filter for value(CellFilter) in Document Table

### ISSUE THREAD

**Issue by ZuiY** [fbaligand/kibana-enhanced-table#125]
Hi, I'm using Kibana 6.8.6 and Enhanced Table 1.9.0, is there any way to disable the "filter for value" button in document table? It maybe block my button which I added it as default to click.
![image](https://user-images.githubusercontent.com/30773139/88758402-ef689a00-d19a-11ea-899f-33fe3c729ded.png)

I can modify the code of plugin and rebuild it by myself if there is any way to solve this, thanks for the great work!

**Comment by fbaligand** [comment]
Hi,

I guess that you use a computer column with just `colX` in formula, right?

If so, I invite you to change the formula to `colX || ""`.
I explain:
When a computed column contains only a reference to a filterable column, filter buttons are added. 
So the tip here is to concatenate colX with empty string to avoid this feature.

**Comment by ZuiY** [comment]
Hi @fbaligand ,
Thanks for the quickly reply

Yes, I use col0 which is the document ID I set as default, and the computed columns which has download icon need the ID to call my external API to download something.
If I change the formula from `col0` to `col0 || ""`, the table will show nothing.
![image](https://user-images.githubusercontent.com/30773139/88770087-dd452680-d1af-11ea-9e37-b83a294eced3.png)

Your tip can work on another situations to avoid filter button, but not work for mine.
Now I just expand the label of column like from "AAA" to "Download AAA" and align to left, the filter button will not block by button.
But I think it will be great to have enable/disable option to control the filter button.

**Comment by ZuiY** [comment]
OK, I think this issue should be Kibana's data table related.
If anybody face this issue can just expand the label of column to avoid it, so I close this issue.
Thanks ~

**Comment by fbaligand** [comment]
Well, this issue is clearly related to enhanced table, given that the issue concerns a computed column issue. 

I’m very surprised that my tip does not work for you. 
I tried this tip with string and number, and it works fine. 

Do you have some error logs on your browser console?
