### ISSUE TITLE
error on computed column from dashboard

### ISSUE THREAD

**Issue by jpchev** [fbaligand/kibana-enhanced-table#128]
hi there, 
I have an enhanced data table with 3 computed columns, the fomulas for these computed columns are like this
"col3 / col2 * 100.0" (computing percentages).

I'm facing the error "In computed column "col3 / col2 * 100.0", column number 3 does not exist" when including the enhanced table in a dashboard.

The error never happens when displaying the table in Visualisation.

I'm using Kibana 7.8.0 and the version 1.9.1 of enhanced table

Any ideas?
Thanks

**Comment by fbaligand** [comment]
Hi,

There is a blocking issue with kibana 7.8 for now: #116 
Your issue is the same so I close this issue as it is a duplicate.
