### ISSUE TITLE
Unable to filter using document table

### ISSUE THREAD

**Issue by dpippenger** [fbaligand/kibana-enhanced-table#129]
I have struggled to find a cause on my end, but I've been unable to do so. I can't seem to make the document table plugin filter on any fields. Clicking the +/- filter options seems to do nothing. 

I have reproduced this issue on index patterns both with and without a timestamp. I've tested on Chrome/Brave/Edge browsers (which granted are all chromium based). I've cleared my caches and used incognito modes... I've experienced this issue on both ES 7.8.0 and now 7.8.1 with the corresponding latest enhanced table plugin for each of those releases. I'm currently using 1.9.2 on ES 7.8.1.

Does this work for others on this version of ES? If so does anyone have any suggestions for me to try?

**Comment by fbaligand** [comment]
Hi

After tests, I confirm the bug. 
I work on it for next release.

But for now, if you want a version without this bug, I advice you to use enhanced table for kibana 7.7.1

**Comment by emaninder** [comment]
@fbaligand this plugin helped us improving our dashboards and the only feature thats not working is filter (+/-).

**Comment by fbaligand** [comment]
Hi,
Good news: I implémented the issue fix and it will be available in next release!

**Comment by dpippenger** [comment]
That's great news! Thank you for your response.

**Comment by fbaligand** [comment]
Good news: enhanced table v1.10.0 is out with this issue fixed and more enhancements!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0
