### ISSUE TITLE
Computed Rows not possible?

### ISSUE THREAD

**Issue by krasnars** [fbaligand/kibana-enhanced-table#130]
Hi,

I'd like to use the Computed Columns functionality, but on Row level. Is that possible somehow?

Thanks, Arsim

**Comment by fbaligand** [comment]
Not sure to understand your question. 
Computed columns are computed per row.
So basically, answer is yes. 
Maybe you could explain more your need?

**Comment by krasnars** [comment]
In the picter below you can see taht I have one row calculating the sum for every day of the week. It would be very nice if I could do some aggregations over the column "Sum of day_of_week_i" e.g. sum over all the fields. Maybe this is already possible, but I was not able to figure how it works yet and I've spent quite some hours. 

![Snap](https://user-images.githubusercontent.com/38656727/90428543-70dd8900-e0c4-11ea-856d-b557e7f181aa.png)

**Comment by fbaligand** [comment]
Could you explain what you mean by “sum over all the fields”? I guess you mean “sum over all the rows”, right?
If so, you can do it like this:
- activate “show total” option
- in your computed column, use `total1` variable. It contains the sum of column no 1 (0-based index).

**Comment by krasnars** [comment]
yes, that does the job as well. thanks a lot :)

**Comment by fbaligand** [comment]
Great!
So I close the issue as question is answered.
