### ISSUE TITLE
Visualization computed failed (col1/total)

### ISSUE THREAD

**Issue by msavitski** [fbaligand/kibana-enhanced-table#131]
Hi
There is one problem, on dashboards we have tables, that failed with ![image](https://user-images.githubusercontent.com/23666916/90370167-a1e29d00-e075-11ea-8745-e88a44228cf0.png)

Unfortunately, when go to the edit mode, it works as expect:
![image](https://user-images.githubusercontent.com/23666916/90371315-76f94880-e077-11ea-87bb-fbc115ca3c0b.png)
Also, when you click save and return, it also looks good on dash (another  enhanced datatables on dash also work fine). But after reloading dash the same error as previously. 

Kibana version - 7.8.1
Plugin version - 1.9.2

**Comment by fbaligand** [comment]
Given you error, I invite you to :
- stop kibana 
- remove kibana/optimize folder
- start kibana
- empty your browser cache
- and test again

Other had the same issue, and this way fixed the problem.

**Comment by msavitski** [comment]
Thanks a lot, it's true.
Removing kibana/optimize folder was key for solving problem.
