### ISSUE TITLE
Add Kibana 7.9 support

### ISSUE THREAD

**Issue by tonykoval** [fbaligand/kibana-enhanced-table#132]
Add support to Kibana 7.9. Check:
https://www.elastic.co/guide/en/kibana/current/release-notes-7.9.0.html
https://www.elastic.co/guide/en/kibana/current/release-notes-7.9.1.html
https://www.elastic.co/guide/en/kibana/current/release-notes-7.9.2.html
https://www.elastic.co/guide/en/kibana/current/breaking-changes-7.9.html

Thank you.

**Comment by allardwp** [comment]
I would like to upgrade to the latest version of Kibana (7.9), however I am dependent on the enhanced table which offers great additional functionality. I would like to know if it is planned to have a new release for the latest Kibana version?

**Comment by fbaligand** [comment]
Yes, I confirm you that it is planned. 
I currently add some new features, then will add support for kibana 7.9 and then release enhanced table version 1.10.0

**Comment by ravitandur** [comment]
Any timelines for releasing 7.9.x compatible version please?

**Comment by fbaligand** [comment]
I can't give you an exact date.
But I think about 1 or 2 weeks.

**Comment by ceo** [comment]
> Any timelines for releasing 7.9.x compatible version please?

What changes from kibana 7.8 to 7.9 ?

**Comment by fbaligand** [comment]
Globally, there are several refactorings in Kibana code, that requires code changes in enhanced table code. 
But the good news is that today, I think I have finished all required changes. I will do some addot  tests this we, then backport new features/bug fixes for old kibana versions, and finally release. 
I think I can release next week. 

Fabien

**Comment by vpiserchia** [comment]
This is amazing, thanks for you effort!

**Comment by markwheal** [comment]
keep up the good work @fbaligand !

**Comment by fbaligand** [comment]
Good news: enhanced table v1.10.0 is out with Kibana 7.9 support and more enhancements!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0
