### ISSUE TITLE
Referring [col4] cell color as background color to [col12] cell

### ISSUE THREAD

**Issue by ganesh-s05** [fbaligand/kibana-enhanced-table#133]
Hi, 
I am not sure if this will be a question/enhancement & I will leave that decision to you :) 

I have a scenario wherein I have a Status defined with a color coding (achieved this by choosing color in the Index pattern based on condition) in one column say col4 & I have another column say col12 which has the date displayed. I would like to keep the col12 as such & have the background color referenced from col4. Is this possible? I tried to do the referencing by - <span style="color: {{col0}}">{{value}}</span> but it shows me error stating unable to reference columns. Could you please provide some insights? 

![image](https://user-images.githubusercontent.com/67759874/91327406-15f21300-e7e3-11ea-9685-60536a406d42.png)

**Comment by fbaligand** [comment]
Hi,

I think that this comment should answer your need:
https://github.com/fbaligand/kibana-enhanced-table/issues/106#issuecomment-667250493

**Comment by ganesh-s05** [comment]
Awesome.. thank you very much.. It worked like a charm.. You made my day!!  I have attached the screenshot of the solution..  I have 2 questions though. 

1. I now similarly have about 5-6 columns to which I need to perform this computed column. Is there a range/regexp something like that i can set to the formula or should i create those many Computed Columns? 
2. Is it possible to change the font color as well? I tried adding <span style="background-color: {{col3}}">{{value}}</span> in addition to the background color in the Template. But, the column displayed same value two times, (which makes sense). Currently, the font color is black, is it possible to change it to white unanimously? 

![image](https://user-images.githubusercontent.com/67759874/91551595-0b04c300-e948-11ea-9e78-f7af4ae4b238.png)

**Comment by ganesh-s05** [comment]
@fbaligand 
Meanwhile, I tried the hard way of creating computed columns for each and every column and it looks something like below. It looks a bit clumpsy. All the computed columns are closely coupled. Are there any ways to make the column width extended? I went over the documentation but I couldn't find anything for column width or for bordering (like excel). Any ideas would be helpful. 

![image](https://user-images.githubusercontent.com/67759874/91557960-0b568b80-e953-11ea-9ec6-6a4478ed60ea.png)

**Comment by fbaligand** [comment]
Hi,
So I guess you use “split cols” bucket in your last screenshot, right?

- for font color, if you want white color for all your cells, then you can use “color” css property with fixed value, without any other computed column:
`<span style="color: white">{{value}}</span>`
- if you want no line return in your column, you can try style="white-space: nowrap" or else, you can use replace function in formula to replace space by ubreakable space: `replace(colX, " ", "&nbsp;")`

**Comment by fbaligand** [comment]
Then you can’t define a border or change column width explicitly but activate alternative row color by activating  option  “striped rows”

**Comment by ganesh-s05** [comment]
Hi, 
To your first question - I actually used "split rows". 
If i understand right - So if I tried using the font colors then i can't define the border/change column width ?

I can use the same "Template" thing to define the border & column width? Sorry if it's a silly question.

**Comment by fbaligand** [comment]
There’s no link between defining font colors and defining border/column width. 

So:
- basically enhanced table displays a html table 
- with computed column template, you can define whatever html/css you want, but the html is inserted in table “td” tag. So you can’t customize “td” html/css, but only the html/css inside “td” tag. 
- That’s why I consider that you cannot define border or cell width. 
- But you can try to do something like a border in template, using “div” tag and css style. In the same way, you can try to customize width with div and css style. 
- bur I can’t promise you the expected result.

**Comment by ganesh-s05** [comment]
Thank you, @fbaligand for you time & inputs. 
The column width depends on the size of the text in the column header. The moment i give a larger title the column does expands. 
In addition for the table border, i implemented the below in one specific column. 
`<span style="background-color: {{col21}}", table { border-collapse: collapse}">{{value}} </span>`

I can still add a table { border: 3px solid } to make the borders more thick.. And the beauty is - It got applied for the entire Enhanced table. I thought it will get applied only to the specific column. Its a bonus :) This is how my table looks like now: 

![image](https://user-images.githubusercontent.com/67759874/91725819-e2393380-ebbc-11ea-8b93-e48722b5ea47.png)

**Comment by fbaligand** [comment]
Thanks for the share!
I'm very surprised that a css style defined on "span" tag that is inside the table impacts the whole table css!
But it's a cool hack :)

**Comment by fbaligand** [comment]
Concerning width of the column, you can try to put this style: `white-space: nowrap`.
It avoids to have line breaks in your columns.

**Comment by ganesh-s05** [comment]
> Thanks for the share!
> I'm very surprised that a css style defined on "span" tag that is inside the table impacts the whole table css!
> But it's a cool hack :)

Yep.. I'm surprised either :)

**Comment by ganesh-s05** [comment]
> Concerning width of the column, you can try to put this style: `white-space: nowrap`.
> It avoids to have line breaks in your cells.

Sure. I will try.. Thank you very much. I will go ahead and close this. 
Once again appreciate your help.

**Comment by fbaligand** [comment]
Nice to see that you solved your need!
