### ISSUE TITLE
ES OpenDistro 1.9.0 with Enhanced Table not working

### ISSUE THREAD

**Issue by ky-ma** [fbaligand/kibana-enhanced-table#134]
Hi,

I am using OpenDistro ES and the latest release is July 9th 2020 and they  use ES 7.8.0 and Kibana 7.8.0.

https://opendistro.github.io/for-elasticsearch-docs/version-history/

I downloaded the Enhanced Table 1.9.2 source to compile for Kibana 7.8.0 successfully but when I load it in Kibana it gives me an "undefined indexpattern" and I can't do anything with it.

I saw that there is a Kibana 7.8.0 issue but wondered if 1.9.2 is running into that issue.

Any input is appreciated as I'd like to keep using OpenDistro release with Enhanced Table.

Thanks!

**Comment by fbaligand** [comment]
No it is not possible. 
Enhanced table v1.9.2 uses a patch included in kibana 7.8.1 (and not in kibana 7.8.0). 

But If open distro supports 7.8.0, it should also support 7.8.1. 
You can install kibana 7.8.1, and change kibana version in open distro kibana plugins inside their package.json file.
BTW, you can keep elaticsearch 7.8.0

Fabien

**Comment by ky-ma** [comment]
OK, let me try that! thanks for the quick response.

**Comment by ky-ma** [comment]
I'm not sure I can upgrade Kibana by itself, what do you recommend.

ubuntu@es-oss:~$ sudo dpkg -i kibana-oss-7.8.1-amd64.deb 
Selecting previously unselected package kibana-oss.
(Reading database ... 173844 files and directories currently installed.)
Preparing to unpack kibana-oss-7.8.1-amd64.deb ...
Unpacking kibana-oss (7.8.1) ...
dpkg: error processing archive kibana-oss-7.8.1-amd64.deb (--install):
 trying to overwrite '/etc/kibana/kibana.yml', which is also in package opendistroforelasticsearch-kibana 1.9.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 kibana-oss-7.8.1-amd64.deb
ubuntu@es-oss:~$

**Comment by fbaligand** [comment]
OK, so I guess that you have installed opendistroforelasticsearch using DEB install package?
I think that you should manually install kibana 7.8.1:
- untar https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.8.1-linux-x86_64.tar.gz somewhere
- copy kibana-7.8.0/plugins to kibana-7.8.1/plugins
- change kibana version to 7.8.1 in each opendistro plugin "package.json" file
- use this new kibana install, instead of old kibana 7.8.0 install

**Comment by ky-ma** [comment]
OK, let me try this method, thanks for the details on how to do this.

**Comment by fbaligand** [comment]
Hi,
Sorry for my late answer, I missed your question.

So, normally, uuid file is writer in kibana data folder.
So the main question is where is kibana data folder and what are the rights for this folder?

**Comment by fbaligand** [comment]
I close the issue as main question is answered and there is no feedback since more than two months
