### ISSUE TITLE
enhanced table release for Kibana 7.8.0

### ISSUE THREAD

**Issue by npayaresc** [fbaligand/kibana-enhanced-table#135]
hello,

please let me know where I can find the release of enhanced Table 1.9.x for Kibana 7.8.0

Regards,
Nico

**Comment by fbaligand** [comment]
Kibana 7.8.0 is not supported because there is a blocking issue with Kibana 7.8.0 (#116), that has been fixed in Kibana 7.8.1.
So there is no release of enhanced Table 1.9.x for Kibana 7.8.0

**Comment by fbaligand** [comment]
Question is answered, so I close the issue.
