### ISSUE TITLE
Is it possible to do set operations?

### ISSUE THREAD

**Issue by abhishek063** [fbaligand/kibana-enhanced-table#138]
I have 2 fields "build version" and "defects". If 'X' and 'Y' are build versions then I want to know:
1. The defects common to X and Y.
2. Defects unique to X and Y.

**Comment by fbaligand** [comment]
Hi,

I could suggest to do this:
- create a "Terms" bucket based on "defects" fields
- create a "Sum Bucket" metric, with a "Filters" sub-aggregation
-- add one Filter "build_version:X" and another "build_version:Y"
- then you can create 3 computed columns : "Only X", "Only Y", and "X and Y"
- "Only X" has this formula: "col1 > 0 and col2 == 0"
- "Only Y" has this formula: "col1 == 0 and col2 > 0"
- "X and Y" has this formula: "col1 > 0 and col2 > 0"

**Comment by abhishek063** [comment]
Thanks for the prompt response. I will try this and let know how it goes.

**Comment by fbaligand** [comment]
By the way, it will simply display true or false for each computed column. 
But you can have a custom display using : <condition> ? ”Yes" : "No".
Or you can also generate html instead of Yes/No.

**Comment by abhishek063** [comment]
Thank you, Fabien for your help. I was able to create the necessary chart. Just followed a slightly different approach from the instruction you gave. 

Instead of using the "SUM bucket" metric agg with "filters" sub-agg, I used "Split rows" on the build version and then "Split Cols" on the same build version with "COUNT" metric agg. to get intended columns. I did this as I did not want to limit my charting to those build values only and wanted the chart to dynamically take the last 2 build versions. Below is the chart for reference. I have hidden the col0 which is a row split of the build version and helping me get the last 2 values of it.

<img width="922" alt="Screen Shot 2020-09-18 at 5 43 42 PM" src="https://user-images.githubusercontent.com/2530420/93596159-86e9ac80-f9d6-11ea-87ea-1b77b9b89007.png">

I know the label field is a static TEXT field, still checking to see if we can dynamically control the labels for computed columns so that I don't see "Only X", "Only Y" and rather see the build versions??

**Comment by fbaligand** [comment]
nice to see that you find a way to answer your need. 
That said, I'm very surprised that you first do a split rows bucket on "build version" and then a split cols on "build version".
Doing so, you can't have both build versions for one table row. 
Up to me, you should remove the first split rows bucket. 
Then, if you want the "2 last build versions for one defect", I invite you to use "top hit" metric. 
Then, with computed column, you can work on array value, with several methods (provided by expr-eval or enhanced table). You can look at documentation on GitHub to see all the available functions. 

Finally, I confirm you that you can't have a dynamic column label.

**Comment by abhishek063** [comment]
Thank you, Fabien for pointing out the mistake I was doing. I got blinded by the amount the data (rows) and did not realize the issue. I followed your instructions and I am pretty happy with what I have achieved. Thank you very much to you and the community for the awesome plugin and active development.
<img width="1618" alt="Screen Shot 2020-09-23 at 1 16 09 PM" src="https://user-images.githubusercontent.com/2530420/93982582-04c70280-fd9f-11ea-933e-eb39abd94a24.png">

**Comment by fbaligand** [comment]
Hi,

Well, I think about your issue.
And at this time, there is not a really easier way to do...
Actually, Top Hit aggregation returns a simple string if there is only one value found, and an array if more values are found.
That's why "uniq" function has this weird behavior.
In next release, I will add a new `isArray` function and enhance uniq method to detect if value is not an array.

**Comment by abhishek063** [comment]
Great, that sounds good. Thank you again!

**Comment by fbaligand** [comment]
Hi @abhishek063,

Good news: enhanced table v1.10.0 is out with `isArray` function, uniq/sort functions that support single value as input (instead of array), and more enhancements!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0

**Comment by abhishek063** [comment]
@fbaligand : That's great news Fabien. Looking forward to using it soon. Thank you for taking care of it on priority.
