### ISSUE TITLE
Kibana 6.4

### ISSUE THREAD

**Issue by yuri-kozlov** [fbaligand/kibana-enhanced-table#14]
Please add support Kibana 6.4

**Comment by fbaligand** [comment]
Well, I m currently working on it. 
Sadly, as usually now, Kibana new minor version has breaking and undocumented changes :(

**Comment by fbaligand** [comment]
Hi @yuri-kozlov, 

enhanced-table plugin v0.8.0 is out with Kibana 6.4.0 support ! 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.8.0
