### ISSUE TITLE
variable 'Top Hits' count to retrieve latest X results?

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#140]
Hi all,
I am posting a question here as I am avid user and fan of the enhanced tables, and am wondering about the functionality of the array capabilities mentioned in the documentation. I've not made use of arrays here before.

I am wanting to retrieve the sum of a field of an unknown number of documents.
I can determine the number of documents that I wish to retrieve, but it will be a different number for each row of my table.

Is there a way to specify a unique TopHit [number] per row, where the number could be calculated in another column of the table, i.e. I could do col1[col['value']]? And I could do a top hit SUM calculation over the variable number of documents?

Thanks
Mark

**Comment by fbaligand** [comment]
Well, if you want a column that is the sum of a field, there is a simple way: you add a "metric", and choose "sum" aggregation. And you add also a "split rows" bucket for every row you want in the result table. The document count per row is not a problem. 

Or maybe there is a complexity that I missed in your need?

**Comment by markwheal** [comment]
I'd like to have a metric where I can do a TopHiit and then SUM the results, where Size is the variable that I can set flexibly

**Comment by fbaligand** [comment]
Well, if you want to sum the values in a top hit metric, you can use "fold" method in computed column formula:

`fold(f, y, a) `
Array fold: Fold/reduce array a into a single value, y by setting y = f(y, x, index) for each element x of the array.

**Comment by markwheal** [comment]
Oh wow thank you. I've not used fold before... I'll give it a try 😃👍

**Comment by fbaligand** [comment]
I close the issue as question is answered and there is no feedback since more than two months
