### ISSUE TITLE
Applied on total line the same calculation than on the other line for the calculated column

### ISSUE THREAD

**Issue by filou711** [fbaligand/kibana-enhanced-table#142]
Hello Team,

Please find below a proposition of feature request: 

**Describe the feature:**
We create a table visualization(like enhanced table in kibana) and create a calculated column. 
We add a total line with an operator (like sum). 
The total on calculated column, is not the one with the formula/calcul, but the total with the operator of total line.
We would like to have the same calculation  on total line than on the other line of the calculated column

**Describe a specific use case for the feature:**
Imagine, we have these data:
- A list of data per country
- Country are aggregate in a column "COUNTRY GROUP"

![data_example](https://user-images.githubusercontent.com/7106012/94949453-3ba8c100-04e1-11eb-989f-98d0abd9cb34.jpg)

I create an enhanced table to have the percent value between the two colum: Project margin/Indirect cost. 
I add a total line with the operator "SUM". 
I sum the value of Project margin/Indirect cost.
But on the calculated column, I have also a  sum of all the value calculated. 

![step1_wrongtotal](https://user-images.githubusercontent.com/7106012/94949573-701c7d00-04e1-11eb-9131-742f8c6a60de.png)

I would like to have, on the total line, also the sum of the column Project margin/Indirect cost.
But on the column calculated, not the sum but the calcul between  the two colum: Project margin/Indirect cost, like on this example (apply also on total line, the calculation): 
![step2_wrongtotal](https://user-images.githubusercontent.com/7106012/94949713-abb74700-04e1-11eb-85bb-db054562a369.png)

Thanks for your feedback!

**Comment by fbaligand** [comment]
Well, this feature is already implemented in v1.9.0. 
When you define your computed column, you have to check the option "compute total using formula".

**Comment by fbaligand** [comment]
I close the issue as question is answered and there is no feedback since more than two months
