### ISSUE TITLE
Time filter no longer working with latest version [Kibana 7.9.2 - ET 1.10.0]

### ISSUE THREAD

**Issue by hoberhol** [fbaligand/kibana-enhanced-table#144]
Time filter in Kibana is no longer working with latest version of Enhanced Table.
Always all results will be shown regardless of the settings in the time filter.

**Enhanced Table:**

13059 results shown, not correct for "Today" time filter

![image](https://user-images.githubusercontent.com/65902724/95140865-1d0c2980-0770-11eb-9651-0be1d8aefdc1.png)

**Kibana Data Table:**
327 results shown

![image](https://user-images.githubusercontent.com/65902724/95140937-3c0abb80-0770-11eb-92e4-2e0278ae2060.png)

**Discover:**
327 results shown

![image](https://user-images.githubusercontent.com/65902724/95140975-517fe580-0770-11eb-931b-16e267e0ed4b.png)

**Comment by fbaligand** [comment]
Hi @hoberhol,

I just released enhanced-table 1.10.1, with this issue fixed:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.1

**Comment by WizBangCrash** [comment]
Hi @fbaligand,

I tried using 1.10.1 today, but whenever I try to create a visualisation with an enhanced table I get the following error:
`ChunkLoadError: Loading chunk 9 failed.
(error: http://localhost:5601/33984/bundles/plugin/enhancedTable/9.plugin.js)
    at Function.requireEnsure [as e] (http://localhost:5601/33984/bundles/plugin/enhancedTable/enhancedTable.plugin.js:106:26)
    at http://localhost:5601/33984/bundles/plugin/enhancedTable/enhancedTable.plugin.js:191502:129
    at http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:105001
    at xs (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:105150)
    at ml (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:90018)
    at hl (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:89943)
    at ol (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:87291)
    at http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:45733
    at t.unstable_runWithPriority (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:430:3462)
    at Hi (http://localhost:5601/33984/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:422:45442)` 

I am using Kibana v7.9.2.
Any pointers as to what might be causing this?

**Comment by hoberhol** [comment]
Hi @fbaligand,

Thanks a lot for the fast bugfix. I tested the new version and everything is now working just perfect!

@WizBangCrash: I cannot reproduce your issue. On my side I can create a new visualisation with an enhanced table without any problem. 
I'm using 1.10.1 with 7.9.2 as you.

Have a nice evening.

Regards,
Hans

**Comment by fbaligand** [comment]
@hoberhol 
Happy to see that you confirm the bugfix!

@WizBangCrash 
I invite you to follow steps indicated in Troubleshooting section:
https://github.com/fbaligand/kibana-enhanced-table#troubleshooting

**Comment by WizBangCrash** [comment]
@fbaligand 
FYI. I rebuilt my docker image with the `--no-cache` option and I no longer have the error.
Thanks for the latest version :-)

**Comment by fbaligand** [comment]
Great!
Happy to see that it finally works, and thanks for the feedback.
It's nice to know for other users that can have the same issue.
