### ISSUE TITLE
Unable to connect to kibana after loading enhanced-table plugin

### ISSUE THREAD

**Issue by mhlnk** [fbaligand/kibana-enhanced-table#145]
I am running Kibana 7.8.1 on Ubuntu. Kibana is installed in /usr/share/kibana. Things work fine prior to installing the enhanced-table plugin. However, after the installation, I am getting a message: "Kibana server is not ready yet". I found a similar post here: https://github.com/fbaligand/kibana-enhanced-table/issues/34, and followed the instructions to copy the index.css file. This did not help.

I don't see this problem when running on Windows.
Could this be another permissions problem?

Thanks in advance.

**Comment by mhlnk** [comment]
Problem solved. I was running kibana as a service. There was permission issue with /user/share/kibana/plugins directory. Once the right permissions were given, everything is working!

**Comment by fbaligand** [comment]
Nice to see you finally solve your problem. 
As your problem is solved, I close the issue.
