### ISSUE TITLE
Invalid visualization type "enhanced-table" with kibana 7.9.2

### ISSUE THREAD

**Issue by sriccio** [fbaligand/kibana-enhanced-table#147]
Hello and thank you for this very neat plugin.

I just updated our ELK stack to 7.9.2 and removed/installed enhanced-table 1.10.1, but now all visualizations using enhanced-table returns "Invalid visualization type "enhanced-table".

When creating a new vis' the enhanced-table is not listed.

Would you have any idea how to find what can be wrong ?

Thanks.

```
[root@es-node01 ~]# sudo -u kibana /usr/share/kibana/bin/kibana-plugin list
enhanced-table@1.10.1
```

```
[root@es-node01 ~]# rpm -qa | grep kibana
kibana-7.9.2-1.x86_64
```

**Comment by fbaligand** [comment]
Hi,

I just tested to install enhanced-table 1.10.1 on Kibana 7.9.2 and I don't reproduce this issue.

Just 2 simple questions:
- it is quite obvious, but do you install this package: https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.10.1/enhanced-table-1.10.1_7.9.2.zip ?
- do you install using "kibana-plugin install file:///path/to/enhanced-table-1.10.1_7.9.2.zip ?

If all answers are yes, I invite you to do these actions:
- stop kibana
- remove $KIBANA_HOME/optimize folder
- start kibana
- empty your browser cache
- reload kibana

**Comment by sriccio** [comment]
Hello,

Thanks a lot.

Yes I installed this package and like you said.

I followed the steps you suggested and it now works. Not sure if it was the browser cache or the optimize folders though :)

Thanks again,
Sébastien

**Comment by fbaligand** [comment]
Nice to see that it finally works!

Starting from Kibana 7.9, normally, optimize folder is not anymore an issue. So it's probably the browser cache. 
That said, without an isolated test, you will never know :)
