### ISSUE TITLE
Adding drilldown links from the table plugin

### ISSUE THREAD

**Issue by ganesh-s05** [fbaligand/kibana-enhanced-table#148]
Hi @fbaligand , 

I have a scenario wherein i will need to use drill down links. The default table plugin has the drilldown links however I couldn't find this in the plugin. Is there an alternate way to use the drill down links? 

I will not be able to use the String formatting (URL) at the Index level because I will need to pass the filter value & also the value data which i'm choosing inside the table.

**Comment by fbaligand** [comment]
Hi @ganesh-s05,

Drilldown links are supported by enhanced-table since Kibana 7.9.2.
So the easy way is to upgrade your Kibana version to v7.9.2.

If it is not possible for you, you can add a computed column, with "Apply template" setting.
In Template, you can put a html link that references another dashboard with a filter applied based on some column value of the row:
`<a href="#/view/dashboard1?...{{col1}}...">{{col1}}</a>`

**Comment by ganesh-s05** [comment]
that's a brilliant idea @fbaligand . I couldn't upgrade to 7.9 for now.. but the reference column trick worked out. Thank you very much! 
I actually had a control filter on top & also needed to reference the "column" as well. I wasn't very sure on how to reference the control filter value, so i added that field as another column as well, referenced it in the 'href' easily & hid the original column. 

Thank you once again.

**Comment by fbaligand** [comment]
Nice to see that it solves your need!

**Comment by ganesh-s05** [comment]
@fbaligand - a quick question. Not relevant to the above ones. I did not want to open a new ticket for a simple question. 

I am having about 40 columns of which 22 are reference columns. I will be anyways showing only about 10 columns and remaining i will be hiding. Will there be any performance issues that has been encountered in your experience with too many computations & reference columns? 
Are there any kind of best practice should i keep in mind for these many columns?

**Comment by fbaligand** [comment]
Wow, 40 columns!
Honestly, I never experimented so much. So I can't tell how it behaves.

Just one thing, if you want to display one row per document, use Document Table, not Enhanced Table, performance will be greatly better (and your Elasticsearch memory also).

**Comment by ganesh-s05** [comment]
Well, I can get you the observations then.. I already have about 30 columns of which 10 are referenced columns. So, far its OK except for some shards issue if there isn't any filter applied. 
I really am not sure about the "one row per document" thing.. I will also see how the Document Table is displaying my data.

**Comment by fbaligand** [comment]
Document Table shares a lot of code with Enhanced table, especially render view that displays the table. 
Options tab is also shared. 

So the only difference is that enhanced table query is a aggregations query (in your case, a lot of sub aggregations), and document table query is a simple search query where results displayed are hits. 
That's why document table way more performant.

**Comment by shayegh** [comment]
Hi,
I'm using kibana 7.9.2 but can't find Drilldown actions,
could you please give a sample?

**Comment by fbaligand** [comment]
Hi @shayegh,

First, be sure you have Kibana with at least "Basic" license, given that the feature is not OpenSource.

Globally, to get Drilldown actions:
- you go to your dashboard page
- you click on "Edit" link
- you click on Enhanced Table viz settings icon (at top-right)
- and you click on "Drilldown actions" menu item
- if you don't see this menu item, you probably need to create a fresh new "Enhanced Table" visualization, as it may not be able available for visualizations created before Kibana 7.9.

**Comment by shayegh** [comment]
Hi,
thanks for your response, 
But is there any way to drill down by rows?
for example, I click on a row and by its data it sho me another dashboard.

**Comment by fbaligand** [comment]
This is exactly the aim of "Drilldowns" feature.
You can find official Kibana documentation about that feature here: https://www.elastic.co/guide/en/kibana/current/drilldowns.html

Concerning precisely enhanced-table, to use configured "Drilldowns", you click on "Filter for value" / "Filter out value" icon on one cell, and Kibana will ask you if you want to filter this dashboard or open a Drilldown dashboard.

**Comment by shayegh** [comment]
Hi @fbaligand ,
Thank you for the quick answer, it solved my problem.
it's good to add this in your amazing plugin readme.

**Comment by fbaligand** [comment]
I didn't have indicated this in README, because, this is core feature provided by Kibana.
But everybody does not know every Kibana new feature, so that's a nice idea to document it.

**Comment by fbaligand** [comment]
Hi,
This information is now documented in README page.
