### ISSUE TITLE
Error using sumSplitCols() in Kibana 7.6.2

### ISSUE THREAD

**Issue by cpiment** [fbaligand/kibana-enhanced-table#149]
Hi @fbaligand!

First of all thanks for your amazing work :)

We are using enhanced-tables 1.10 for Kibana 7.6.2 and we are trying to use the sumSplitCols() function introduced in 1.9. When we use the function we get this error in both Chrome and Firefox

![imagen](https://user-images.githubusercontent.com/10828255/96255084-a284aa80-0fb6-11eb-9ef1-6670c6e60b79.png)

And the visualization doesn't render. When we remove the computed column, the table renders again.

The split column is a daily date histogram and the metric we are using is the sum of a Kibana scripted field, I don't know if that can make any difference.

Do you know what could be happening?

Thanks in advance for your help

**Comment by fbaligand** [comment]
Can you share your computed column formula?

Given the error, It seems that you write only "sumSplitCols" and not "sumSplitCols()"

**Comment by fbaligand** [comment]
Hi, 

I just tested your exact use case (Split Cols on Date Histogram & Sum of a Scripted Field) on Kibana 7.6.2 with enhanced-table 1.10.0, and it works fine.

So I really believe that there is a mistake in your computed column formula.

**Comment by cpiment** [comment]
Hi,

Here's a full screenshot of the formula with the error and the blank table that renders when I click the play button:

![imagen](https://user-images.githubusercontent.com/10828255/96405312-418aeb80-11dd-11eb-96e8-fa99a2789d25.png)

I have recently updated enhanced-tables from 1.8 to 1.10. In our architecture we have a load balancer in front of Kibana that may be caching some Javascript... Is there a way to check which version of enhanced-tables is being loaded using the web developer tools of the browser?

**Comment by fbaligand** [comment]
To my known, there is no way to know enhanced table version through browser dev tools. 

That said, as it looks like a cache problem, I advice you to follow troubleshooting actions described here:
https://github.com/fbaligand/kibana-enhanced-table#troubleshooting

**Comment by cpiment** [comment]
I have tried what is proposed in Troubleshooting without success... I don't really know if it is a cache problem, but I can't find another explanation to this.

**Comment by fbaligand** [comment]
Can you do a test with direct access  from your browser to Kibana, without any proxy?

As I don't reproduce the issue with same versions than you, the cache problem is the better explanation.

Can you confirm that you also removed optimize folder and restarted Kibana ?

**Comment by cpiment** [comment]
Hi,

I'm using Kibana official Docker image, extended with this Dockerfile:

```FROM docker.elastic.co/kibana/kibana:7.6.2

COPY ./enhanced-table-1.10.0_7.6.2.zip /usr/share/kibana

RUN /usr/share/kibana/bin/kibana-plugin install file:///usr/share/kibana/enhanced-table-1.10.0_7.6.2.zip

RUN /usr/share/kibana/bin/kibana --optimize
```

I run the optimize command and the end of the image creation because if I don't do that, the Kibana container takes a long time to start since it does the optimize in every startup.

I have started a fresh Kibana container using this image, and I'm accessing directly to it (no proxies or load balancers) and the problem still persists with the same symptoms.

**Comment by fbaligand** [comment]
Well, two advices:
- really delete "optimize" folder, before to run "kibana --optimize" command.
- use "--no-cache" option when building your Docker image as suggested in this comment:
https://github.com/fbaligand/kibana-enhanced-table/issues/144#issuecomment-709907047

**Comment by cpiment** [comment]
I have generated a new image with this Dockerfile:

```
FROM docker.elastic.co/kibana/kibana:7.6.2

COPY ./enhanced-table-1.10.0_7.6.2.zip /usr/share/kibana

RUN /usr/share/kibana/bin/kibana-plugin install file:///usr/share/kibana/enhanced-table-1.10.0_7.6.2.zip

RUN rm -rf /usr/share/kibana/optimize

RUN /usr/share/kibana/bin/kibana --optimize
```

And built it with the `--no-cache` option of `docker build`, and now the column is shown 

![imagen](https://user-images.githubusercontent.com/10828255/96555812-8172d100-12b8-11eb-9f98-73d793eb0bcf.png)

In this example I forced the column "test" with formula "sumSplitCols()/3600" to have the same value as column "Horas" to check I got the same result.

Thanks a lot for your help solving this.

**Comment by fbaligand** [comment]
Nice to see that it fixes your issue!
I precise that there is also countSplitCols function, so you can do: 
sumSplitCols()/countSplitCols()

**Comment by cpiment** [comment]
Thanks! That was the main reason for upgrading from 1.8 to 1.10, so we could use that two functions :)

Thanks for the great plugin and the terrific support!
