### ISSUE TITLE
Add more Split Column

### ISSUE THREAD

**Issue by shayegh** [fbaligand/kibana-enhanced-table#151]
Hi,
tanks for your excellent plugin,
is there any way to split a bucket by more than one column?
for example, I have a bucket consist of College, field, sex, grade, I want to have a column of the count of students by their sex and another column of the count of students by their grade while my rows are split by College.

**Comment by fbaligand** [comment]
Hi,

The plugin does not allow to have multiple "split cols" bucket. 

That said, given your case, you could achieve your need, doing so:
- a split rows bucket by college
- a split cols bucket by grade
- a "Max bucket" metric, with "filters" bucket aggregation and one filter "sex:male", count metric aggregation and custom label "male"
- another "Max bucket" metric, with "filters" bucket aggregation and one filter "sex:female", count metric aggregation and custom label "female"

You should get one column per duo "grade - sex"

**Comment by shayegh** [comment]
Hi,
Thanks a lot,
You're amazing.

**Comment by fbaligand** [comment]
Nice to see that you appreciate my work ;)

If your issue is solved, thanks to close the issue.

**Comment by jafaryehsan** [comment]
i'm very happy to know you , and thank you for your excellent knowledge sharing. can you give me your email address ? i'm very thankful if i ask some more questions. could we being in touch in Persian ? i am waiting for your response.

**Comment by shayegh** [comment]
Hi,
shayegh@gmail.com
