### ISSUE TITLE
Add Kibana 7.10 support

### ISSUE THREAD

**Issue by tonykoval** [fbaligand/kibana-enhanced-table#153]
Add support to Kibana 7.10. Check:
https://www.elastic.co/guide/en/kibana/current/release-notes-7.10.0.html
https://www.elastic.co/guide/en/kibana/current/release-notes-7.10.1.html
https://www.elastic.co/guide/en/kibana/current/breaking-changes-7.10.html

Thank you.

**Comment by fbaligand** [comment]
Hi,

I just published packages for Kibana 7.10.0 and 7.10.1!
You can find it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.1
