### ISSUE TITLE
How can i add a string column based on values of previous column?

### ISSUE THREAD

**Issue by Shivamyadav2512** [fbaligand/kibana-enhanced-table#154]
Say i have col0 of integers ranging 0 - 100
I want col1 to be `Great`, `Good`, `bad` and so on based on the value of col0  - say > 60 is `Great`.

I found this `col0 > 60 ? 'Great' : 'Need to another condition here'` how can i add more condition in it for rest of the ranges?

**Comment by fbaligand** [comment]
Hello,

You can do like this:
`col0 > 60 ? 'Great' : (col0 > 40 ? 'Good' : 'Bad')`

**Comment by Shivamyadav2512** [comment]
Thank you @fbaligand
