### ISSUE TITLE
Export link creates unsaved.csv

### ISSUE THREAD

**Issue by rafreyes** [fbaligand/kibana-enhanced-table#155]
Hi,
I have encountered an issue when exporting the table (enhanced and document) as CSV through the export links. While the export is successful the filename generated is "unsaved.csv". Would it be possible to have the visualisation's name as the filename?

Thanks a lot for sharing this useful plugin

**Comment by fbaligand** [comment]
Hi,

Thanks to report this bug.
I will try to fix it in next release.

**Comment by fbaligand** [comment]
Hi,

I looked deeply to fix this issue, but actually there is no mean to, because vis title information is not provided by Kibana to plugin's controller.

So I just created a PR to Kibana core, so that it provides vis title information to a visualization plugin:
https://github.com/elastic/kibana/pull/84456

**Comment by fbaligand** [comment]
Hi,

My PR on kibana core (https://github.com/elastic/kibana/pull/84456) has been merged and will be available in Kibana 7.11.0.
So this issue will be fixed in Kibana 7.11.0

**Comment by rafreyes** [comment]
Hello,
thanks for the feedback. so, we'll wait for the 7.11 version
have a nice day

**Comment by fbaligand** [comment]
Hi,

Waiting for Kibana 11, I just released Enhanced Table v1.11.0, and default name is now `export.csv`, in Kibana 7.8+.
It is better than "unsaved.csv" :)

**Comment by rafreyes** [comment]
Hello,

yes, that's better. thank you

have a nice 2021 :)

**Comment by fbaligand** [comment]
Happy new year 2021 !

**Comment by fbaligand** [comment]
As expected, the bug has been solved in Kibana 7.11.
So I close this issue.

**Comment by fbaligand** [comment]
Hi,

Finally, there was also a bug in Enhanced Table plugin code.
I just fixed it in last release (v1.13.3), available here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.3
