### ISSUE TITLE
Calculate column value difference with first row ( or any other ? )

### ISSUE THREAD

**Issue by zewelor** [fbaligand/kibana-enhanced-table#156]
Hi

thanks for great plugin. I'm wondering is it possible to calculate difference, between some column, but in different rows ? For example I want to calculate difference between column 2 in each row, against column 2 in row 0 ( so row 0 will have 0 difference ).

**Comment by fbaligand** [comment]
Basically, it is not possible, sorry.
the tip that I can give would be :
- do a "Cumulative Sum" metric, where inner metric is your actual "column 2 metric".
- then enable "show total" and use "min" total function
- finally, in computed column, use "total2" in your formula. It will reference the total of column 2, that is the min value of your "cumulative sum" column. So it is column 2 row 0.

**Comment by zewelor** [comment]
Thanks for the reply and suggestion !
