### ISSUE TITLE
Total and Subtotal

### ISSUE THREAD

**Issue by xAKOSx** [fbaligand/kibana-enhanced-table#157]
Hi, is there a way, to create total and subtotal lines too in the table? If I split the table, I have subtotals but no total line. Thx&Cheers!

**Comment by fbaligand** [comment]
Hi,

Sorry, there is no such a feature.

Here are some alternative solutions:
- having subtotals in columns (not rows) using option "Show metrics for every bucket/level"
- use "split tables" bucket with a "Filters" aggregation where the last filter is "*"

**Comment by xAKOSx** [comment]
Hi,
thanks! Maybe next version! :)
