### ISSUE TITLE
Display fields without aggregation

### ISSUE THREAD

**Issue by bphenriques** [fbaligand/kibana-enhanced-table#16]
Can you add support for displaying custom fields without aggregations?

In the following example, I want to display the `items.name` without any kind of aggregations next to the `item.id`.

### Use case:
``` 
POST /orders/_doc/orderA
{ 
    "orderId": "orderA",
    "amount": 10,
     "items": [ 
          { "id": "A", "name": "ItemA" },
          { "id": "B", "name": "ItemB" }
     ] 
}

POST /orders/_doc/orderB
{ 
    "orderId": "orderB",
    "amount": 5,
     "items": [
          { "id": "A", "name": "ItemA" }
     ] 
}
```

|Item Id| Item Name|Sum Amount|
|---|---|---|
|A|ItemA|$15.00|
|B|ItemB|$10.00|

**Note**: The `items` is nested type.
```
{
	"version": 1,
	"index_patterns": ["orders"],
	"mappings": {
		"_doc": {
			"properties": {
				"items": {
					"type": "nested"
				}
			}
		}
	}
}
```

### What is manageable
Have the Item Id (Bucket by `items.id` and create a `SUM` aggregation over the `amount` field. What is missing is displaying the `items.name`.

**Comment by fbaligand** [comment]
If « sum amount » column is the sum of « amount » field per item Id, I would say that for item « B », sum amount is 10 (not 5), right ?

Then did you try to do what you suggest at the end of your comment ?
I mean: in the buckets, add a « terms » aggregation based on item.id field. In the metrics, add a « sum » aggregation based on amount field.

**Comment by bphenriques** [comment]
> If « sum amount » column is the sum of « amount » field per item Id, I would say that for item « B », sum amount is 10 (not 5), right ?

Indeed. Fixed the example :)

> Then did you try to do what you suggest at the end of your comment ?
I mean: in the buckets, add a « terms » aggregation based on item.id field. In the metrics, add a « sum » aggregation based on amount field.

I could have made it clear, will update the description.  I want to display the `items.name` without any kind of aggregations next to the `item.id`.

**Comment by fbaligand** [comment]
Well, to do so, you need to do a « nested » aggregation in buckets. 
And as I know, nested aggregation is not yet supported in kibana. 
If you don’t do a nested aggregation, Elasticsearch doesn’t associate item name with its Id.

A potential trick is to make a terms aggregation per item name and not display item id column. Sure, it’s not perfect but I have to better solution for you.

**Comment by bphenriques** [comment]
Nested aggregations is actually possible ([source](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-nested-aggregation.html)). I managed to do it on a separate example using Vega charts but in there I have full control over the query.

**Comment by fbaligand** [comment]
Well, indeed, nested aggregation is available since a long time in elasticsearch.
But my point was that in « standard » kibana visualizations (with standard bucket/metrics editor), in the bucket aggregations, you can’t add a « nested » aggregation. 
And enhanced table uses a standard editor. 

That said, in Vega, with its very custom editor, you can make a custom elasticsearch query manually, and so, a nested aggregation.

**Comment by bphenriques** [comment]
Yeah, I understand. Thank you.

**Comment by fbaligand** [comment]
Sorry that enhanced-table can't answer your "nested" need.
But actually, this is more a "kibana-core" problem.

**Comment by bphenriques** [comment]
Yep :) Thanks!

For completeness, I will leave the Kibana issue here.
https://github.com/elastic/kibana/issues/1084

**Comment by fbaligand** [comment]
Nice !
So I close this issue.
