### ISSUE TITLE
Check in formula that column is empty

### ISSUE THREAD

**Issue by GeorgeRD** [fbaligand/kibana-enhanced-table#162]
I was wondering if there is a way when writing a formula for a new computed field to check if an existing column field is empty. I tried 'col1== null' and checked if there was an isnull/ifnull but could not sort it out. Thank you in advance!
Kibana server: 6.8.10
enhanced_table: 1.9.1

**Comment by fbaligand** [comment]
Hi, there is a way to put a default value, if column is empty:
`col(1, -1)`
-1 is the default value.

**Comment by GeorgeRD** [comment]
Many thanks @fbaligand  for the quick reply. I noticed the following:
* when setting formula equal to colx, if there is an empty value, the table does not display any data
* when using col(x) or col(x,0) or col('header') col('header',0) the table displays data but there is no value on the rows where the column is empty, i.e. it seems it doesn't replace with the default value.

**Comment by fbaligand** [comment]
It is strange. 
could you tell what is your kibana version and Enhanced table version?

**Comment by GeorgeRD** [comment]
Sure, it was posted on my first comment. 
Kibana server: 6.8.10
enhanced_table: 1.9.1

**Comment by fbaligand** [comment]
Hi,

Sorry to have asked you this, although you already provided the information.
So, this bug is normally fixed since enhanced-table v1.10.0.
You can see it in the last line of release notes:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0

So I invite you to upgrade to enhanced-table v1.10.0.

**Comment by GeorgeRD** [comment]
Many thanks @fbaligand for your support and thanks again for this great product!

**Comment by fbaligand** [comment]
Nice to see that you appreciate :)
