### ISSUE TITLE
Fail to install enhanced-table v1.11.0 -> Optimization failure on Kibana 7.6.2

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#168]
Hello @fbaligand 

When installing on fresh ELK 7.6.2 i got this error message.
I use the command line to install : ./bin/kibana-plugin install file:////[PATH_TO]/enhanced-table-1.11.0_7.6.2.zip 
then starting kibana :
`````
FATAL  Error: Optimizations failure.
   6131 modules
    
    ERROR in ./plugins/enhanced-table/public/data_load/kibana_cloned_code/courier.ts
    Module not found: Error: Can't resolve '../../../../src/legacy/core_plugins/visualizations/public' in '/Users/.../elk-7.6.2/kibana-7.6.2-darwin-x86_64/plugins/enhanced-table/public/data_load/kibana_cloned_code'
    
    ERROR in ./plugins/enhanced-table/public/data_load/kibana_cloned_code/courier.ts
    Module not found: Error: Can't resolve '../../../../src/plugins/data/public' in '/Users/.../elk-7.6.2/kibana-7.6.2-darwin-x86_64/plugins/enhanced-table/public/data_load/kibana_cloned_code'
`````

**Comment by fbaligand** [comment]
Hi,
Sorry this bug. 
I see what’s the problem. 
I will fix it tonight or in the following days.

**Comment by toog** [comment]
thanks

**Comment by fbaligand** [comment]
Hi  @toog,

I fixed the problem and published the fixed packages (in place of the older ones).
You can find it here on v1.11.0 release page:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.11.0

The fixed packages are those from Kibana 7.6.0 to 7.8.1.

**Comment by fbaligand** [comment]
Tell me if it fixes your problem.
And if the problem is still there, re-open the issue.

**Comment by toog** [comment]
👍 it's OK now

**Comment by fbaligand** [comment]
Great !
