### ISSUE TITLE
Conditional rules for calculated column templates

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#173]
I know there is a workaround - to add another column and hide it - to set the color there to green/red/etc based on cells value.
However, it would be simpler to be able to apply templates with conditions, i.e. >=0 is green; <0 is red. The TSVB table has a simple method to apply colours like this for a column/metric, but otherwise doesn't compare to enhanced table functionality!
Thanks!

**Comment by fbaligand** [comment]
Hi,

Since enhanced-table v1.10, there is a new computed column setting named "Cell computed CSS".
Using this setting, you can customize cell CSS dynamically.

For instance:
`col1 >= 0 ? "color: green" : "color: red"`

**Comment by markwheal** [comment]
Dreamy 👍 nice one. I will upgrade
