### ISSUE TITLE
Evol metric with custom request 

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#174]
I’ve been confronted multiple time to this pb, and i think an evolution on your great plugin can resolve it.  

my need is to have a table splitted by row on a fiels value of doc’s type A.
On the second column to have a formula base on a metric divide by a value computed by a mix of metric on doc’s type A and another metric targetting doc’s type B with no common field with doc type A.

My data are like this example. 
{ type: A, num: 1, run: 56 }
{ type: A, num: 2, run: 25 }
{ type: A, num: 3, run: 46 }
...
{ type: A, num: 5, run: 88}
{ type: A, num: 6, run: 99}
{ type: B, fieldY: 1, state : ok}
{ type: B, fieldY: 4, state : ok}
{ type: B, fieldY: 17, state : ko}
{ type: B, fieldY: 1, state : ok}

|num|Ratio|  
|-|-|
|x| Max(run)/ count(query (type:B and state: ok)|
|1| 56/3 |
|2| 25/3 |
...

so it would be powerful to compute metric with custom request without usage of the main bucket.
Or to have on the data configuration part the ability to add multiple couple of bucket/metric(s).  

like Excel/sql  we can compute part of a formula by using separated request.

**Comment by fbaligand** [comment]
Hi,

Well, honnestly, this is very complex to implement, both solutions.

**Comment by fbaligand** [comment]
I think that you can achieve your need doing these steps:
- in "Metrics", add "Max" aggregation, and choose field "run"
- in "Metrics", add "Max Bucket" aggregation
  - choose "Filters" as sub "Bucket" aggregation
  - in "Filter 1" option, indicate your sub query (ex: `type:B and state: ok`)
  - choose "Count" as sub "Metric" aggregation
- Finally create a computed column with this formula:
`col['max_run'] / col['State B and state OK Count']`
