### ISSUE TITLE
Plugin on cloud

### ISSUE THREAD

**Issue by hdianawinwinit** [fbaligand/kibana-enhanced-table#175]
Is it possible to install this plugin on the Elastic Cloud? If yes, how to do it?

**Comment by fbaligand** [comment]
To my known, it is possible to install it on Elastic Cloud Enterprise (ECE), Elastic Cloud for Kubernetes (ECK), but not Elastic Public Cloud.

**Comment by abbanabennanih** [comment]
I confirm, it's not possible to install Kibana plugins on Elastic Cloud as stated here https://www.elastic.co/guide/en/cloud/current/ec-restrictions.html#ec-restrictions-plugins

**Comment by fbaligand** [comment]
As question is answered, I close the issue.
