### ISSUE TITLE
Hiding columns with numerical labels

### ISSUE THREAD

**Issue by martinschi** [fbaligand/kibana-enhanced-table#179]
Hello,

I have problem hiding columns with numerical labels. I have documents tagged with week numbers (integer number from 1 till 5). I do `split cols` `histogram` aggregation, which gives me 5 columns labeled 1,2,3,4,5. Problem is that I can't actually hide them "by name", because when I enter 3 to the *Hidden columns* field, it hides third column (= col3) as opposed to column with label 3 (= col['3']).

I can't rely on column index for hiding either, because the histogram can return only columns 3,4 for example, when there are no data for weeks 1,2 and 5.

Suppose example:

| Name | 1 | 2 | 3 | 4 | 5 | Computed Col 1 |
|---|---|---|---|---|---|---|
| Name1 | 8  | 3 | 7 | 6 | 2 | 10 |

I can't just hide 1,2,3,4,5, because that's hiding columns with indexes 1,2,3,4,5 as opposed to columns with labels 1,2,3,4,5. Another data slice may only yield columns 3,4 and then the index of Computed Col 1, which I want to keep, would become 3 and it would become hidden by the Hidden columns =  1,2,3,4,5.

It would really help if I could say Hidden columns =  '1','2','3','4','5' to mark it as labels.

**Comment by fbaligand** [comment]
Hi,

Indeed, I understand your problem.
And I think, like you, that it would be a nice enhancement.
So, I will try to implement it in next release.

**Comment by fbaligand** [comment]
Hi, 
Enhanced Table v1.14.0 is out, with ability to indicate hidden column titles surrounded by single or double quotes!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.14.0
