### ISSUE TITLE
Split col order by term broken

### ISSUE THREAD

**Issue by bfranzen** [fbaligand/kibana-enhanced-table#18]
v6.4.0
It always sorts by metric despite setting, causing computed column expressions to break as referenced by col number

**Comment by fbaligand** [comment]
Well, unfortunately, I have  the same conclusion...
I go through results as they are returned by Elasticsearch and add columns as new values are discovered. 
So if aggregated data is not in the right order, enhanced table don’t manage it. 

That said, you can  use a « filters » aggregation, it lets you to be sure that the order is what you wish.

**Comment by bschmer** [comment]
Unfortunately, the column terms are mostly non-deterministic in my case so that is not an option.

**Comment by fbaligand** [comment]
I’m afraid I can’t help you on this issue...

**Comment by bfranzen** [comment]
Thanks for the input
Filter cols dont work at all for me however :)

**Comment by fbaligand** [comment]
The idea is to use a "Filters" aggregation in the "Split Cols" bucket.
Then you configure several filters :  
![image](https://user-images.githubusercontent.com/3750300/48836293-95d38980-ed82-11e8-8aca-ea7e69799550.png)

Doing so, you will be sure that you will have 3 columns and in the right order (even if there is no "VAL1" value in your data).

**Comment by bfranzen** [comment]
Thanks again, I had to add all columns referenced in expressions and it worked

**Comment by fbaligand** [comment]
Happy to see that it works!

**Comment by fbaligand** [comment]
So can I close the issue ?

**Comment by bschmer** [comment]
Well, the underlying problem isn't solved, but can the workaround at least be added to the documentation?  I fear for my use case that I'll actually need to solve the problem somehow, but I'll get something working and submit a PR.

**Comment by fbaligand** [comment]
Well, can you detail your use case and problem ? Maybe a editor screenshot could help (data and options tabs)

**Comment by fbaligand** [comment]
I close the issue, given there is no answer for 5 months.
