### ISSUE TITLE
CSV download including computed columns

### ISSUE THREAD

**Issue by pfennema** [fbaligand/kibana-enhanced-table#180]
Currently when downloading either the raw or formatted CSV only the columns which are directly from ElasticSearch are downloaded in the CSV. Is it possible to add the computed columns as well as this would greatly improve the possibilities of the CSV.

**Comment by fbaligand** [comment]
Hi,

If you don't check 'Full CSV export' option, CSV export (raw or formatted) already includes computed columns.

'Full CSV export' downloads pages of Elasticsearch data, and directly exports it as CSV, without rendering.
That's why 'Full CSV export' is not compatible with 'Computed columns', 'Rows computed filter', 'Hidden columns', 'CSV export with total row' and 'Add row number column' options.

**Comment by pfennema** [comment]
Thanks a lot for the explanation!

**Comment by pfennema** [comment]
Unfortunately the option 'Full CSV export' only applies for a Document Table, not for an enhanced table. I did not specify that unfortunately. As we're using the pivot functionality quite a bit we need to use the enhanced table including computed columns and want to export the result into a csv.

**Comment by fbaligand** [comment]
Ah. This is surprising. 
what is your kibana version and enhanced table plugin version ?

**Comment by pfennema** [comment]
The version of enhanced table is:  enhanced-table-1.11.0_7.10.2.zip
The version of Kibana and ES is also 7.10.2

Thanks a lot for the support!

**Comment by fbaligand** [comment]
Hi,

Today, I made tests with enhanced table v1.11.0 on Kibana 7.9 and Kibana 7.10, and on both, I can download raw or formatted CSV export, and I get well computed columns and Split Cols columns.

So I don't reproduce your issue.

**Comment by fbaligand** [comment]
Maybe you have some special configuration, can you screenshot your buckets, metrics and options ?

**Comment by pfennema** [comment]
Grr, somehow I cannot upload png files to github (probably a restriction on our desktop environment).

What I did now is export the saved object and the text below is the output:

```
`{"attributes":{"fields":"[{\"count\":0,\"name\":\"@timestamp.date_histogram._count\",\"type\":\"number\",\"esTypes\":[\"long\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"@timestamp.date_histogram.interval\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"@timestamp.date_histogram.time_zone\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"@timestamp.date_histogram.timestamp\",\"type\":\"date\",\"esTypes\":[\"date\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"_id\",\"type\":\"string\",\"esTypes\":[\"_id\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"count\":0,\"name\":\"_index\",\"type\":\"string\",\"esTypes\":[\"_index\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"count\":0,\"name\":\"_score\",\"type\":\"number\",\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false},{\"count\":0,\"name\":\"_source\",\"type\":\"_source\",\"esTypes\":[\"_source\"],\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false},{\"count\":0,\"name\":\"_type\",\"type\":\"string\",\"esTypes\":[\"_type\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"count\":0,\"name\":\"client_number.terms._count\",\"type\":\"number\",\"esTypes\":[\"long\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"client_number.terms.value\",\"type\":\"number\",\"esTypes\":[\"long\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"etr_long.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"etr_short.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"otc_long.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"otc_short.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"proc_qty_long_prim_prod.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"proc_qty_short_prim_prod.sum.value\",\"type\":\"number\",\"esTypes\":[\"float\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"safe_keeping_id.keyword.terms._count\",\"type\":\"number\",\"esTypes\":[\"long\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"count\":0,\"name\":\"safe_keeping_id.keyword.terms.value\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true}]","timeFieldName":"@timestamp.date_histogram.timestamp","title":"rollup_etr*"},"id":"2ba68f60-729d-11eb-95c5-c3450023079d","migrationVersion":{"index-pattern":"7.6.0"},"references":[],"type":"index-pattern","updated_at":"2021-02-19T10:28:13.269Z","version":"WzU3ODYwLDEwXQ=="}
{"attributes":{"description":"Daily summary of ETR and regular trades aggregated on Client","kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"},"title":"ETR overview - overall","uiStateJSON":"{\"vis\":{\"params\":{\"sort\":{\"columnIndex\":null,\"direction\":null}}}}","version":1,"visState":"{\"title\":\"ETR overview - overall\",\"type\":\"enhanced-table\",\"aggs\":[{\"id\":\"2\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"etr_long.sum.value\",\"customLabel\":\"ETR Long\"},\"schema\":\"metric\"},{\"id\":\"3\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"etr_short.sum.value\",\"customLabel\":\"ETR Short\"},\"schema\":\"metric\"},{\"id\":\"4\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"proc_qty_long_prim_prod.sum.value\",\"customLabel\":\"Long\"},\"schema\":\"metric\"},{\"id\":\"5\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"proc_qty_short_prim_prod.sum.value\",\"customLabel\":\"Short\"},\"schema\":\"metric\"},{\"id\":\"6\",\"enabled\":true,\"type\":\"terms\",\"params\":{\"field\":\"client_number.terms.value\",\"orderBy\":\"_key\",\"order\":\"asc\",\"size\":1000,\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"customLabel\":\"Client\"},\"schema\":\"split\"},{\"id\":\"7\",\"enabled\":true,\"type\":\"date_histogram\",\"params\":{\"field\":\"@timestamp.date_histogram.timestamp\",\"timeRange\":{\"from\":\"now-3M\",\"to\":\"now\"},\"useNormalizedEsInterval\":true,\"scaleMetricValues\":false,\"interval\":\"d\",\"drop_partials\":false,\"min_doc_count\":1,\"extended_bounds\":{},\"customLabel\":\"Day\"},\"schema\":\"bucket\"}],\"params\":{\"addRowNumberColumn\":false,\"computedColsPerSplitCol\":true,\"computedColumns\":[{\"alignment\":\"left\",\"applyAlignmentOnTitle\":true,\"applyAlignmentOnTotal\":true,\"applyTemplate\":false,\"applyTemplateOnTotal\":true,\"cellComputedCss\":\"\",\"computeTotalUsingFormula\":false,\"customColumnPosition\":3,\"datePattern\":\"MMMM Do YYYY, HH:mm:ss.SSS\",\"enabled\":true,\"format\":\"number\",\"formula\":\"col('ETR Long')+abs(col('ETR Short'))\",\"label\":\"ETR Gross\",\"pattern\":\"0,0\",\"template\":\"{{value}}\"},{\"alignment\":\"left\",\"applyAlignmentOnTitle\":true,\"applyAlignmentOnTotal\":true,\"applyTemplate\":false,\"applyTemplateOnTotal\":true,\"cellComputedCss\":\"\",\"computeTotalUsingFormula\":false,\"customColumnPosition\":4,\"datePattern\":\"MMMM Do YYYY, HH:mm:ss.SSS\",\"enabled\":true,\"format\":\"number\",\"formula\":\"abs(col('ETR Long') + col('ETR Short'))\",\"label\":\"ETR Net\",\"pattern\":\"0,0\",\"template\":\"{{value}}\"},{\"alignment\":\"left\",\"applyAlignmentOnTitle\":true,\"applyAlignmentOnTotal\":true,\"applyTemplate\":false,\"applyTemplateOnTotal\":true,\"cellComputedCss\":\"\",\"computeTotalUsingFormula\":false,\"customColumnPosition\":7,\"datePattern\":\"MMMM Do YYYY, HH:mm:ss.SSS\",\"enabled\":true,\"format\":\"number\",\"formula\":\"col('Long')+abs(col('Short'))\",\"label\":\"Gross\",\"pattern\":\"0,0\",\"template\":\"{{value}}\"},{\"alignment\":\"left\",\"applyAlignmentOnTitle\":true,\"applyAlignmentOnTotal\":true,\"applyTemplate\":false,\"applyTemplateOnTotal\":true,\"cellComputedCss\":\"\",\"computeTotalUsingFormula\":false,\"customColumnPosition\":8,\"datePattern\":\"MMMM Do YYYY, HH:mm:ss.SSS\",\"enabled\":true,\"format\":\"number\",\"formula\":\"abs(col('Long')+col('Short'))\",\"label\":\"Net\",\"pattern\":\"0,0\",\"template\":\"{{value}}\"}],\"csvEncoding\":\"utf-8\",\"csvExportWithTotal\":false,\"filterAsYouType\":false,\"filterBarHideable\":false,\"filterBarWidth\":\"25%\",\"filterCaseSensitive\":false,\"filterHighlightResults\":false,\"filterTermsSeparately\":false,\"hideExportLinks\":false,\"perPage\":\"\",\"row\":true,\"showFilterBar\":false,\"showMetricsAtAllLevels\":false,\"showPartialRows\":false,\"showTotal\":false,\"sort\":{\"columnIndex\":null,\"direction\":null},\"stripedRows\":false,\"totalFunc\":\"sum\"}}"},"id":"3fa601f0-72a0-11eb-95c5-c3450023079d","migrationVersion":{"visualization":"7.10.0"},"references":[{"id":"2ba68f60-729d-11eb-95c5-c3450023079d","name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern"}],"type":"visualization","updated_at":"2021-02-19T11:02:50.969Z","version":"WzU3OTIzLDEwXQ=="}
{"exportedCount":2,"missingRefCount":0,"missingReferences":[]}
`

```
Don't know whether that is useful, in the mean time I will try to upload the screenshots in a different way.

Thanks again!

**Comment by fbaligand** [comment]
Honestly, the json is complicated to use. 
because, I must also have the index pattern, and some example data to be able to load the visualization and investigate.

**Comment by fbaligand** [comment]
Another possibility is to reproduce the issue with official kibana example data (logs or flights or e-commerce). 
If you manage to reproduce the issue with this example data, the visualization json is useful.

**Comment by pfennema** [comment]
Yes I can totally imagine, I will try with the example data first.

**Comment by pfennema** [comment]
Hi Fabian,

When creating the same enhanced table view with the 'kibana_sample_data_ecommerce'  I do not get the computed column(s) either.
What I did: 
1. Added 2 fields as metric and aggregate them as sum (products.quantity and taxful_total_price).
2. Add a computed field which squares the two fields: **col('Products Quantity') * col('Total Price')** 
3. Via 'Inspect'  get the Download CSV. 

Unfortunately the computed column does not appear in the CSV file.
Also tried it with a bucket (day of week) but that does not make a difference apart from getting more rows with days in it, but not the computed column.
I tried it with Computed/Hidden cols per split col (when applying the day bucket), but did not make a difference either.

**Comment by fbaligand** [comment]
Can you export the visualization in saved objects and share it here?

**Comment by pfennema** [comment]
I just noticed that I forgot yesterday and created the export just now ;-)

`{"attributes":{"fieldFormatMap":"{\"taxful_total_price\":{\"id\":\"number\",\"params\":{\"pattern\":\"$0,0.[00]\"}}}","fields":"[{\"name\":\"_id\",\"type\":\"string\",\"esTypes\":[\"_id\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"name\":\"_index\",\"type\":\"string\",\"esTypes\":[\"_index\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"name\":\"_score\",\"type\":\"number\",\"count\":0,\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"_source\",\"type\":\"_source\",\"esTypes\":[\"_source\"],\"count\":0,\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"_type\",\"type\":\"string\",\"esTypes\":[\"_type\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":false},{\"name\":\"category\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"category.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"category\"}}},{\"name\":\"currency\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"customer_birth_date\",\"type\":\"date\",\"esTypes\":[\"date\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"customer_first_name\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"customer_first_name.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"customer_first_name\"}}},{\"name\":\"customer_full_name\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"customer_full_name.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"customer_full_name\"}}},{\"name\":\"customer_gender\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"customer_id\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"customer_last_name\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"customer_last_name.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"customer_last_name\"}}},{\"name\":\"customer_phone\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"day_of_week\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"day_of_week_i\",\"type\":\"number\",\"esTypes\":[\"integer\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"email\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"event.dataset\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"geoip.city_name\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"geoip.continent_name\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"geoip.country_iso_code\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"geoip.location\",\"type\":\"geo_point\",\"esTypes\":[\"geo_point\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"geoip.region_name\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"manufacturer\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"manufacturer.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"manufacturer\"}}},{\"name\":\"order_date\",\"type\":\"date\",\"esTypes\":[\"date\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"order_id\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products._id\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"products._id.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"products._id\"}}},{\"name\":\"products.base_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.base_unit_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.category\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"products.category.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"products.category\"}}},{\"name\":\"products.created_on\",\"type\":\"date\",\"esTypes\":[\"date\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.discount_amount\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.discount_percentage\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.manufacturer\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"products.manufacturer.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"products.manufacturer\"}}},{\"name\":\"products.min_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.product_id\",\"type\":\"number\",\"esTypes\":[\"long\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.product_name\",\"type\":\"string\",\"esTypes\":[\"text\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":false,\"readFromDocValues\":false},{\"name\":\"products.product_name.keyword\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true,\"subType\":{\"multi\":{\"parent\":\"products.product_name\"}}},{\"name\":\"products.quantity\",\"type\":\"number\",\"esTypes\":[\"integer\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.sku\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.tax_amount\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.taxful_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.taxless_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"products.unit_discount_amount\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"sku\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"taxful_total_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"taxless_total_price\",\"type\":\"number\",\"esTypes\":[\"half_float\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"total_quantity\",\"type\":\"number\",\"esTypes\":[\"integer\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"total_unique_products\",\"type\":\"number\",\"esTypes\":[\"integer\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"type\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"name\":\"user\",\"type\":\"string\",\"esTypes\":[\"keyword\"],\"count\":0,\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true}]","timeFieldName":"order_date","title":"kibana_sample_data_ecommerce"},"id":"ff959d40-b880-11e8-a6d9-e546fe2bba5f","migrationVersion":{"index-pattern":"7.6.0"},"references":[],"type":"index-pattern","updated_at":"2021-02-22T14:47:38.122Z","version":"WzU5MDcyLDExXQ=="}
{"attributes":{"columns":["category","sku","taxful_total_price","total_quantity"],"description":"","hits":0,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"highlightAll\":true,\"version\":true,\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"},"sort":[["order_date","desc"]],"title":"[eCommerce] Orders","version":1},"id":"3ba638e0-b894-11e8-a6d9-e546fe2bba5f","migrationVersion":{"search":"7.9.3"},"references":[{"id":"ff959d40-b880-11e8-a6d9-e546fe2bba5f","name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern"}],"type":"search","updated_at":"2021-02-22T14:47:38.122Z","version":"WzU5MDY5LDExXQ=="}
{"attributes":{"description":"","kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"},"savedSearchRefName":"search_0","title":"test_enhanced_table","uiStateJSON":"{\"vis\":{\"params\":{\"sort\":{\"columnIndex\":null,\"direction\":null}}}}","version":1,"visState":"{\"title\":\"test_enhanced_table\",\"type\":\"enhanced-table\",\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"params\":{},\"schema\":\"metric\"},{\"id\":\"2\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"total_quantity\",\"customLabel\":\"Total Quantity\"},\"schema\":\"metric\"},{\"id\":\"3\",\"enabled\":true,\"type\":\"sum\",\"params\":{\"field\":\"taxful_total_price\",\"customLabel\":\"Price\"},\"schema\":\"metric\"}],\"params\":{\"addRowNumberColumn\":false,\"computedColsPerSplitCol\":false,\"computedColumns\":[{\"alignment\":\"left\",\"applyAlignmentOnTitle\":true,\"applyAlignmentOnTotal\":true,\"applyTemplate\":false,\"applyTemplateOnTotal\":true,\"cellComputedCss\":\"\",\"computeTotalUsingFormula\":false,\"customColumnPosition\":\"\",\"datePattern\":\"MMMM Do YYYY, HH:mm:ss.SSS\",\"enabled\":true,\"format\":\"number\",\"formula\":\"col('Total Quantity') * col('Price')\",\"label\":\"QP\",\"pattern\":\"0,0\",\"template\":\"{{value}}\"}],\"csvEncoding\":\"utf-8\",\"csvExportWithTotal\":false,\"filterAsYouType\":false,\"filterBarHideable\":false,\"filterBarWidth\":\"25%\",\"filterCaseSensitive\":false,\"filterHighlightResults\":false,\"filterTermsSeparately\":false,\"hideExportLinks\":false,\"perPage\":10,\"showFilterBar\":false,\"showMetricsAtAllLevels\":false,\"showPartialRows\":false,\"showTotal\":false,\"sort\":{\"columnIndex\":null,\"direction\":null},\"stripedRows\":false,\"totalFunc\":\"sum\"}}"},"id":"004dba80-75b0-11eb-98ab-df02bbca02f1","migrationVersion":{"visualization":"7.10.0"},"references":[{"id":"3ba638e0-b894-11e8-a6d9-e546fe2bba5f","name":"search_0","type":"search"}],"type":"visualization","updated_at":"2021-02-23T08:20:34.470Z","version":"WzU5NDA4LDExXQ=="}
{"exportedCount":3,"missingRefCount":0,"missingReferences":[]}`


I is quite irritating that we cannot attach files (probably due to a security limitation on our side), but thanks again!

**Comment by fbaligand** [comment]
Thanks. 
I am currently on vacation. But I will test your visualization as soon as I can.

**Comment by fbaligand** [comment]
Hi,

I just imported your export in my Kibana 7.10.0 instance.
Then I go to your "test_enhanced_table" vis, and generate two CSV exports: "Raw" and "Formatted". Both of them work nice: I have 4 columns:
``` csv
Count,"Total Quantity",Price,QP
1,2,"€145",290
```

I also added visualization to a dashboard and generated CSV exports (Raw and Formatted), and it works nice too.

So, up to my tests, behavior is nice.

At this point, I think that there is no bug.
But I think more about something wrong on your side.
Since Kibana 7.10, I already saw some weird browser cache problems.
So can you fully empty your browser cache and test again?
By "fully empty your browser cache", I don't mean "F5" or "Shift+F5" or "Ctrl+F5", but go to browser options and click the "Empty Data" button (or something similar).

**Comment by pfennema** [comment]
Hi Fabian,

Thanks for trying out with the test data, I tried your suggestion of clearing the browser cache but unfortunately it does not work. I will try to dive further into why it is not working on my side, will try IE instead of Chrome just to see what happens.

**Comment by pfennema** [comment]
Hmm even with a new browser never used before (MS Edge) it has the same behaviour, so would say there is something wrong in my set-up on the server. Just to be sure, I select 'Inspect' (and then I only see the original columns and not the computed one) and then select 'Download CSV' .

**Comment by fbaligand** [comment]
OK, I understand now!
So, to make CSV export working fine (with all enhanced features), you should not use "Inspect" menu, but the 2 export links below enhanced table vis: "Raw" and "Formatted".
Using "Inspect" menu, you have raw Elasticsearch response data export, without enhanced table rendering features.

**Comment by pfennema** [comment]
O my! That is quite an revalation! :-) Good that I mentioned my steps and you immediately noted what went wrong. Thanks again for looking into this.

**Comment by fbaligand** [comment]
Nice to see that we finally found what was wrong :)
