### ISSUE TITLE
Add support for Kibana 7.11

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#181]
https://github.com/elastic/kibana/releases/tag/v7.11.1

Loving enhanced table on an older version of Kibana. Are we ok to upgrade Kibana to the latest release; will enhanced tables still work?

Thanks!

**Comment by fbaligand** [comment]
Hi,

I have to do some tests to say that :)
In the better case, the current code is compatible, and I just have to publish packages for Kibana 7.11.0 and 7.11.1.
In the worst case, the current code is not compatible, and I have to spend some time to find and fix the required changes.

**Comment by dharmaru** [comment]
Hi  fbaligand,

Yeah really loving enhanced table on an older version of Kibana. May I know when you are planning to release a version of this plugin which will have added support for kibana 7.11.1?

**Comment by rajuimported35** [comment]
Hi fbaligand,
It would be very helpful if you let us know when you are planning to release the new version of the enhanced table for Kibana 7.11.0.

**Comment by rajuranasubhasree** [comment]
Hi fbaligand,
It would be very helpful if you let us know when you are planning to release the new version of the enhanced table for Kibana 7.11.0.

**Comment by fbaligand** [comment]
Hi,

I'm currently working on it. 
There are some breaking changes in Kibana 7.11 and I try to find how to deal with these breaking changes.

**Comment by fbaligand** [comment]
Hi all,

I'm glad to announce you that enhanced-table v1.11.1 is out, with Kibana 7.11 support!

You can get it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.11.1

Enjoy :)
