### ISSUE TITLE
Computed Column Total using Enhanced Table and Split Columns by Date Histogram

### ISSUE THREAD

**Issue by RalphRoss** [fbaligand/kibana-enhanced-table#185]
Using the enhanced table to create a series of date columns and counting up entries. We want to create a series of split calculated columns to take the previous column array 1, divided by the total of column 1. When we have only 1 day, the calculate column is correct, however when we add 2nd day, the total is summing up the 2 days and dividing that into all the entries. 

![1 day Enhanced table](https://user-images.githubusercontent.com/77459767/109233954-ca6ff000-7798-11eb-9bf2-c3a5df2711ec.JPG)
![2 day Enhanced table](https://user-images.githubusercontent.com/77459767/109233959-cc39b380-7798-11eb-8c7a-7f9bd47c2e37.JPG)

**Comment by fbaligand** [comment]
Well, indeed, that is a known bug.
Currently, reference column total with a “split cols” bucket and “computed/hidden cols per split col” checked does not work.

It is complex to pre-calculate total when “computed/hidden cols per split col” is checked.

**Comment by RalphRoss** [comment]
Thank you for the rapid response. This one bug is impacting 8 different visuals in one dashboard and I have 6 variants of the dashboard. We tried using precalculated indexes to solve the problem, but this was not accurate. Solving this one bug will not only correct the 48 different visuals, but will also allow us to simplify our index strategy. is there any way you can bump this fix up in priority? Thank you for consideration.

**Comment by fbaligand** [comment]
Hi,

Well, the first way to bump this fix up in priority, is your last comment explanation, where you explain how impacting is this bug for your use.

The second way is to support my work on this plugin:
https://github.com/fbaligand/kibana-enhanced-table#donation

**Comment by RalphRoss** [comment]
Hi Fabien,

Thanks for your response. I use the enhanced tables and TSVB for the majority of my visuals. I have several othe dashboards that I can make for monitoring our supplier performance, once the enhanced table is working properly.

I saw your coffee donation request and provided a contribution for several cups of coffee for you.

Thanks again,
Ralph Ross
________________________________

**Comment by RalphRoss** [comment]
Hi Fabien, 

Are you able to spend any time to address the bug with the enhanced tables? It would be a big help with the visuals so that people would not need to do manual calculations with the raw data in the tables. 

Thank you, 
Ralph Ross

**Comment by fbaligand** [comment]
Yes, I will work on the fix.
I’m currently working on another open source project (logstash editor) for its next version, and then I will work on enhanced table next version.

**Comment by RalphRoss** [comment]
Hi Fabien, 
Hope you are doing well. I am checking back with you to see if you have any plans to work on this bug. 
Please let me know when you can proceed with a fix. 
Thank you.

**Comment by fbaligand** [comment]
Hi,

Well, this fix is on the roadmap, but sorry, I can't give you an estimated date.

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with this issue fixed!
Numerous other enhancements are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0
