### ISSUE TITLE
Document table doesn't filter by Datetime picker criteria

### ISSUE THREAD

**Issue by jpchev** [fbaligand/kibana-enhanced-table#189]
The datetime interval set by datetime picker is not taken into account by document table.
Tested on version 1.11.0, Kibana 7.10.2 (Opendistro version)

**Comment by fbaligand** [comment]
Hi,

Sorry for my very late answer.
I just tested with the same conditions : enhanced table v1.11.0 and Kibana v7.10.
And I don't reproduce your issue. The date interval is taken into account by document table.

I advice you to fully remove your browser cache and retry.
By "fully remove your browser cache", I mean to go to your browser options, and click the "Delete cache" button (not just F5 or Ctrl+F5).

I saw some weird behaviors solved by this tip.

**Comment by jpchev** [comment]
thanks for your answer, did you test with Kibana Opendistro or with plain Kibana?
Thanks

**Comment by fbaligand** [comment]
I tested with plain Kibana

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
