### ISSUE TITLE
Kibana 6.5.0

### ISSUE THREAD

**Issue by Sungwook-Choi** [fbaligand/kibana-enhanced-table#19]
with Kibana 6.5.0
enhanced table plugin is not working.
I succeeded installing the plugin after changing the kibana version on package.json and running up the Kibana.
but Discover, Visualize, Dashboard menu is not working.
capture
<img width="1551" alt="kibana650" src="https://user-images.githubusercontent.com/10297110/48826402-81f14d00-edad-11e8-9bef-bd9f922d95a6.png">

**Comment by fbaligand** [comment]
Indeed, plugin is not yet compatible with Kibana 6.5. 
But I’m currently working on it, and I will soon provide a release compatible with Kibana 6.5

**Comment by fbaligand** [comment]
Hi,

I'm glad to announce that enhanced-table v0.9.0 is released, with Kibana 6.5 support!
This release also includes a visualization options redesign!

You can get it here : 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.9.0

**Comment by fbaligand** [comment]
Feel free to give feedback about this new release!
