### ISSUE TITLE
Unable to see plugin in the kibana dashboard .Installed the plugin using the cli (Internet URL command). Tested version - 1.11.1 and Kibana - 7.11.0.

### ISSUE THREAD

**Issue by harshitmalhotra02** [fbaligand/kibana-enhanced-table#190]

**Comment by fbaligand** [comment]
Well, I invite you to fully delete your browser cache. I mean in your browser options. 
then refresh kibana url. 

To see the plugin in kibana 7.11, go to visualize app, then click  “create visualization” button, then click on “aggregation based”, and here, you will see both “Enhanced Table” and “Document Table”  visualizations.

**Comment by harshitmalhotra02** [comment]
Thank you so much.
