### ISSUE TITLE
Condition upon column value

### ISSUE THREAD

**Issue by Jacquito77** [fbaligand/kibana-enhanced-table#191]
Hello,

Is it possible to set a condition on a computed column so that the column value depends on the category value of another (example: col5=0 if col3 = True/False or col4="some_str") ? If so, how to do it ?

Thank you

**Comment by fbaligand** [comment]
Yes it is possible.

Globally, you can see whole documentation for computed column formulas here:
https://github.com/fbaligand/kibana-enhanced-table#computed-settings-documentation

Then, the formula expression language is [expr-eval](https://github.com/silentmatt/expr-eval#expression-syntax). You can click the link to see the syntax.

Finally, to answer to your precise question, you can use this formula:
`(col3 == "True/False" or col4 == "some_str") ? 0 : 1`

**Comment by callmeSaqib** [comment]
@fbaligand is it possible to pinned filter on filterbar by clicking a conditional column in enhanced table? as seen below, I want to click on the red box to add that filter on the filterbar. Thankyou in advance
![image](https://user-images.githubusercontent.com/67755306/112341628-65e67900-8ce3-11eb-9a8f-0e787037078b.png)

**Comment by Jacquito77** [comment]
Thanks @fbaligand , I couldn't find it in the documentation, but it works perfectly, thanks a lot !

**Comment by fbaligand** [comment]
Well, concerning documentation, in [expr-eval](https://github.com/silentmatt/expr-eval#expression-syntax), you have a table listing all operators, including `or` operator and ternary operator (`x ? y : z`)

**Comment by fbaligand** [comment]
Happy to see that my suggestion works perfectly for your need!
Given that your question is answered, I close the issue.
