### ISSUE TITLE
small nit in the readme :)

### ISSUE THREAD

**Issue by rful011** [fbaligand/kibana-enhanced-table#194]
I have just installed the plugin, restarted kibana and went to my kibana window *which was already open*.

followed the instructions but there was no "enhanced table".    Thought for a moment or two and hit refresh...

I suggest you adding something in the instructions to cover the case where the user already has a browser window open with kibana running.

for example:

Open Kibana URL in your browser (by default: http://localhost:5601) *or hit reload if you already have a kibana window open*

**Comment by fbaligand** [comment]
Ok, I will try to enhance documentation.

**Comment by fbaligand** [comment]
This issue is now fixed by "Troubleshooting" section in documentation:
https://github.com/fbaligand/kibana-enhanced-table#troubleshooting
