### ISSUE TITLE
The total number of any sign and its further use in the table

### ISSUE THREAD

**Issue by anomaliyao** [fbaligand/kibana-enhanced-table#20]
Is it possible to take into account the number, which is obtained overall in the column? Those. there is a total number of entries in the table for a certain time interval - do you need to calculate the top most popular ones from this and use it to calculate the table column?

**Comment by fbaligand** [comment]
Hi,

I'm not sure to understand your question.
Could you give a concrete example to help me understand your need ?

**Comment by anomaliyao** [comment]
In the table for the calculation i need a similar method of calculation, something like "total". Only this should be calculated as, not just the total number of documents (records) in the table, but such as top users by visits. Those. This number will be dynamic, the total number of the most active users.

**Comment by fbaligand** [comment]
Well, I think you could achieve your goal using a sibling pipeline aggregation like "Sum Bucket".
In this metric, you can do a Terms or Filters aggregation, and then compute a metric per bucket. Finally you will have overall sum of bucket metrics in a column.
Then, with enhanced-table, you can reference this column to make your calculation, and hide this "Sum Bucket" column in "Hidden columns" option.

**Comment by anomaliyao** [comment]
This is good, but does not work for me. Because the sum is calculated for each term. And for the calculation I need to get the total amount for all terms and use it.

**Comment by fbaligand** [comment]
Well, the aim of "bucket sum" pipeline aggregation is especially to compute the overall sum, that is to say, the sum of each metric per term.

Here's an example based on Kibana Sample Data Flights (you can test it for yourself).
If you compute the count for the top 3 "DestCountry" terms, you get : 
- IT	422
- US	352
- CN	220
So the total is 994.

And if you do a sum bucket pipeline aggregation, you get 994, so the sum of each term metric.

Here's the Kibana screenshot : 
![sum-bucket](https://user-images.githubusercontent.com/3750300/49370356-2fd8f180-f6f4-11e8-8d72-2ad7e3a7dc02.png)

**Comment by anomaliyao** [comment]
![image](https://user-images.githubusercontent.com/23505611/49371639-3887f280-f709-11e8-9e02-5c0799735562.png)
Yes, it is clear. The total amount of all data is available.
But how can I use the number in the table, which is obtained in the blue square?

**Comment by anomaliyao** [comment]
![image](https://user-images.githubusercontent.com/23505611/49443344-3ee79e80-f7dd-11e8-88aa-8c18a930f010.png)
Those. in the column where formula calculation is needed, i need to divide the data by term by the total number of column 2. And not within per term

**Comment by anomaliyao** [comment]
In table first add a "Filters" bucket with 1 filter "*" , then add a "Terms" bucket (field).
When use Sum Bucket with subAgg Terms by custom metric sum & aggregation by count I get the following error
`Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"buckets_path aggregation does not exist for aggregation [15]: 15-bucket&gt;_count"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"index_1","node":"node_1","reason":{"type":"illegal_argument_exception","reason":"buckets_path aggregation does not exist for aggregation [15]: 15-bucket&gt;_count"}}],"caused_by":{"type":"illegal_argument_exception","reason":"buckets_path aggregation does not exist for aggregation [15]: 15-bucket&gt;_count","caused_by":{"type":"illegal_argument_exception","reason":"buckets_path aggregation does not exist for aggregation [15]: 15-bucket&gt;_count"}}},"status":400}`

When I remove "Filters" bucket with 1 filter "*", the error disappears. And aggregation works correctly.

**Comment by fbaligand** [comment]
Yes, unfortunately, you can't mix "Show metrics for every bucket/level" and "Sum Bucket" aggregation :(
This problem is also available for standard Data Table.

But, because of "Filters" bucket with 1 filter "*", you normally don't need anymore a Sum Bucket aggregation. You can do a simple metric aggregation.

**Comment by fbaligand** [comment]
I close the issue because:
- no answer for 4 months.
- I provided a workaround 
- concerning the ability to use a previous column total in a computed column, you can follow this issue: #32
