### ISSUE TITLE
Search/ filter computed columns

### ISSUE THREAD

**Issue by MyronM95** [fbaligand/kibana-enhanced-table#200]
Is there anyway to search or filter the computed columns in the search or filter bar like you can with non-computed columns? e.g. "computedColumnName" > "5". Thanks for the great plug-in!

**Comment by fbaligand** [comment]
If you mean global Kibana search/filter bar, this is not possible as this search/filter is done server-side on elasticsearch data, while enhanced table computed columns are computed and rendered front-side.

That said, in enhanced table options, you can enable a “filter bar” that allows you to filter table rows, similarly to Kibana global search bar.

**Comment by MyronM95** [comment]
But the filter bar only always you to search for specific values through out the rows. You can't look up a value in only a specific column and get back the rows where that matches, right?

**Comment by fbaligand** [comment]
Indeed.
You can do it through index pattern scripted fields. 
or, in enhanced table, using “rows computed filter” option.

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
