### ISSUE TITLE
is it possible to round to significant figures?

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#202]
I have various values that get reported in the same field - however, some values are extremely different. I use the following format in enhanced table visualisations to display them today: `0,0.0000`

2 example values:
99,999.1
0.9999

99,999.1 is an example where I only care to show 1 decimal place in tables, but floats in Kibana are displayed with as many decimal places as I choose to show using 0,0.0000 format. If I store 99,999.1 as my value post a kibana transform, and it is stored as a float, I am shown a value with apparent additional decimal places.

0.9999 shows up as expected/intended when using 0,0.0000 format.

So, I was thinking if significant figures are supported, I could make use of them as a formatting method? Or is there something better that already exists?

Thanks
Mark

**Comment by fbaligand** [comment]
Hi,

To display these 2 values as you expect, I invite you to use `0,0.[0000]` pattern.

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
