### ISSUE TITLE
Blank table / error when a field is missing

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#203]
I'm using ELK 7.6.2, I have a table with 2 metrics 
![image](https://user-images.githubusercontent.com/40697794/114862765-3660f300-9def-11eb-851b-90ea9a8cf079.png)

when i use an index with some missing fields we have this message
![image](https://user-images.githubusercontent.com/40697794/114862837-4aa4f000-9def-11eb-93d6-00358d5b67a9.png)

but when we wan't to edit the visualisation it's not possible
![image](https://user-images.githubusercontent.com/40697794/114862893-5ee8ed00-9def-11eb-9ec6-6f66595d391e.png)

when i open in visualization editor i'v got a blank page with this msg 

![image](https://user-images.githubusercontent.com/40697794/114864363-3235d500-9df1-11eb-8481-149670bda22e.png)

I must go to the management/Saved Object to edit in textual mode the vizualization.

 - is it possible to got the visualization editor with some metric in red to change the value for more easy to use ?
 - is it possible to automatically disable metric that are not possible to compute and have a result for the others ?

**Comment by fbaligand** [comment]
Well, using a field that is missing in the Kibana index pattern is a very weird case, that should not happen.
I have tested the same case with core "Data Table", and the behavior is exactly the same.
So this behavior is not "enhanced table" plugin's fault. It is Kibana behavior.
Sorry.

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
