### ISSUE TITLE
Add computed row or use a formula when using SHOW TOTAL

### ISSUE THREAD

**Issue by ashryverrr** [fbaligand/kibana-enhanced-table#206]
Hi,

I'm using Kibana 7.10 and I have a question regarding computed columns: 

I've added the Show Total (SUM function) and I added a  computed column which computes the variance between 2 values.

![image](https://user-images.githubusercontent.com/22993446/117319980-6404fd80-aebe-11eb-973e-b06eca17fdd4.png)

Now, in the Total Sum row instead of  the Variance column being the total Sum of the variances above, is there any way that I can also use a formula to get the variance of the TOTAL SUM row by using a formula? Because what it's currently doing is adding all of the Variance which makes sense since the function is SUM. 

Also, thank you for this wonderful plugin. 

Best regards

**Comment by fbaligand** [comment]
Hi,

you can do that, by checking “compute column total using formula” in your computed column settings.

**Comment by ashryverrr** [comment]
Hi Fabien,

I just tried it but it doesn't seem to be working. The computed column is not showing the Total which is supposed to be calculated using the formula, it's just blank on my end. 

![image](https://user-images.githubusercontent.com/22993446/117692871-063f2100-b1f0-11eb-8412-c0aceff4aab9.png)

**Comment by ashryverrr** [comment]
Yes, I'm using "Split cols" bucket. Here is the screenshot of the computed column:
![image](https://user-images.githubusercontent.com/22993446/117706109-7c974f80-b1ff-11eb-8928-a1ec4a6ad932.png)

**Comment by fbaligand** [comment]
OK.
Could you try this formula :
(col(3, 0) - col(2, 0)) / col (2, 0.01)

**Comment by ashryverrr** [comment]
That worked - thank you! Can you explain why my original formula didn't work and why this one did? I want to understand in case, I have other kind of scenario like this one. 👍

**Comment by fbaligand** [comment]
Nice to see that it works!

I think that your column labels are numbers and not strings. And so, col() function does not find the column when it searches with a string value. 
then, it is important to not divide by 0.

**Comment by ashryverrr** [comment]
Hi Fabien,

Sorry to re-open this but I tried doing the same thing now with strings as the title column but it still doesn't show the total based on the formula.

This is my computed formula settings:

![image](https://user-images.githubusercontent.com/22993446/120390311-22059500-c360-11eb-92f2-2135c793bd0e.png)


Below is the output:

![image](https://user-images.githubusercontent.com/22993446/120390170-f682aa80-c35f-11eb-8563-40361824a1fb.png)

Any idea or it might be a bug? Thank you in advance.

**Comment by fbaligand** [comment]
Well, I just tried to reproduce your issue.
And I get also a buggy result. My result seems to be a bit different, because I get `0%` as total.
I will try to fix the bug in a next release.

Waiting this, here's a workaround that works for my test:
`((col(2, 0)  * 2) - col(1, 0)) / col(1, 0.1)`

That is to say: use column index to reference columns instead of column labels.

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with this issue fixed!
Numerous other enhancements are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0
