### ISSUE TITLE
Add computed column to split metrics columns

### ISSUE THREAD

**Issue by Jacquito77** [fbaligand/kibana-enhanced-table#207]
Hi,

Is there a way I could juxtapose computed columns to vanilla metric columns when splitting columns while having it splitted ?

An image so it gets a bit clearer:

![enhanced_table_question](https://user-images.githubusercontent.com/24941088/117429803-b2021b80-af27-11eb-8e61-e72beb1fd367.PNG)

**Comment by fbaligand** [comment]
Yes, it is possible: enable "Computed/Hidden cols per split col" setting, and you will have each computed column "per split column".

**Comment by Jacquito77** [comment]
Ah right I missed the feature, thanks a lot, it worked perfectly !

**Comment by fbaligand** [comment]
Nice to see that it answers your need!
As this issue is solved, I close the issue.
