### ISSUE TITLE
The buttons "Apply alignment on title" and "Apply alignment on total" don't work

### ISSUE THREAD

**Issue by carnicod** [fbaligand/kibana-enhanced-table#209]
In this example, 
-- the content of computed column "long column title1" is been aligned to right and the button "Apply alignment on title" and "Apply alignment on total" are enable 
-- the content of computed column "long column title2" is been aligned to center and the button "Apply alignment on title" and "Apply alignment on total" are enable 

But in the table result, the title and totals are not aligned as content.; Is there any missing configuration? 
![immagine](https://user-images.githubusercontent.com/84218857/118349186-7979c780-b54f-11eb-8464-a02f9eab64c2.png)

What am I doing wrong?  My enhanced table version is 1.11.1_7.11.0

**Comment by fbaligand** [comment]
Hi,
I just tested your issue, and can confirm this is a bug in Kibana 7.11.
I will try to fix it in next release.

**Comment by carnicod** [comment]
Hi Fabien, when do you think to realiase the fix?

**Comment by fbaligand** [comment]
Well, I can tell you that I fixed the issue.
Initially, I would like to release it with other fixes/enhancements.
But I will maybe finally release only this fix.

**Comment by fbaligand** [comment]
Hi @carnicod,

I just published enhanced-table v1.11.2 that fixes this issue:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.11.2

Hope you will enjoy it :)
