### ISSUE TITLE
Custom column position issue when data is filtered

### ISSUE THREAD

**Issue by ashryverrr** [fbaligand/kibana-enhanced-table#213]
Hi Fabien,

I was using the custom column position and it works great except when you try and filter the data. 

As an example if you have a table:

Jan | Feb |  Mar | Apr | May | Jun | Computed Column  
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- 
1 |  2 | 3 | 4 | 5 | 6 | 0 

In this situation the "Computed Column" will have a custom column position value of 7.  Now if I filter the data to exclude Jan and Feb, it will produce an error like the screenshot. Because now my index is only up to 5 and the position of value "7" doesn't exist anymore in the index since some columns have been removed.

![image](https://user-images.githubusercontent.com/22993446/121360035-a363b580-c966-11eb-8c7a-37f764a27117.png)

Any idea if there is a workaround for this?

**Comment by fbaligand** [comment]
That said, if your need is to put computed column after all "split" columns, you just have to not set "Custom column position" setting.
By default, computed column is after all "split" columns.

**Comment by ashryverrr** [comment]
Hi Fabien, based on your apply I take that this is working as default right? 

Since the custom column position is not really expecting that there will be a change in the # of columns and it's strictly for a fixed number. 

I guess the other workaround would be to replicate the original columns by using a computed column and then arrange it from there. Thanks for the answer!

**Comment by fbaligand** [comment]
As default, one computed column is positioned as last column. 
you don’t answer my question: do you use a “split cols” bucket?
If so, it would be surprising to set a fixed position among split columns.
Up to me, it makes sense to set a fixed custom position before split columns. Or else after all columns, and so, no custom position.

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
