### ISSUE TITLE
Using Key as String from Response as column names

### ISSUE THREAD

**Issue by vikramnr** [fbaligand/kibana-enhanced-table#214]
I was wondering if there is way to display the below key from response as Column name. Requirement is show to Month names in different format and I'm using Date Histogram for it. I have tried using terms but aggregation doesn't work properly since I have data for each day

![Screenshot from 2021-06-11 07-38-48](https://user-images.githubusercontent.com/8538409/121620736-5eb94680-ca5a-11eb-8e5c-83b64d948d6e.png)

**Comment by fbaligand** [comment]
Well, you cannot use key_as_string as column label.
But you can customize Kibana display for month aggregations in Kibana advanced settings.

To do that, in Kibana "advanced settings" screen, edit "dateFormat:scaled" setting and add this array item:
`  ["P1MT", "MMM, YYYY"],`

**Comment by vikramnr** [comment]
Thanks @fbaligand. I have tried it out and was just check if we have something like this in the plugin.
