### ISSUE TITLE
Support for Elasticsearch/Kibana release 6.5.3

### ISSUE THREAD

**Issue by rducharme** [fbaligand/kibana-enhanced-table#22]
Just leaving an note in case you had not yet seen that happening today.

**Comment by fbaligand** [comment]
Thanks for the info, I didn't notice it.
=> I just released the plugin for Kibana 6.5.3 : 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.9.0

**Comment by fbaligand** [comment]
By the way, I'm interested to know how you are notified that a new Kibana version is released ?

**Comment by rducharme** [comment]
?Thank you


Robert Ducharme

Senior Consultant

5 Penn Plaza, Suites 2365-2368 | 23rd Floor |  New York, NY  10001
work 970-405-6253 | Robert.Ducharme@prolifics.com
________________________________
