### ISSUE TITLE
Release for kibana 6.6.0

### ISSUE THREAD

**Issue by gabmess** [fbaligand/kibana-enhanced-table#23]
When is the release for the 6.6.0 version of kibana expected?
Thank you

**Comment by fbaligand** [comment]
Well, I can’t give you a date, but I’m working on it. 
I will notify here when it’ll be released!

**Comment by gabmess** [comment]
Yes thanks, i need to upgrade the enhanced Table plugin at Kibana 6.6.0 version, could give me an upgrade guide ?

**Comment by fbaligand** [comment]
Hi guys,

For having tested it, enhanced table code is not yet compatible with Kibana 6.6. Some code changes are required, because of some breaking changes in Kibana core code.

If someone is interested to push a PR to bring Kibana 6.6 compatibility, you're welcome :)

**Comment by fbaligand** [comment]
Hi guys,

Just to tell you that I'm working on Kibana 6.6.0 compatibility.
More globally, I'm working on next 1.0.0 release that will include 6.6.0 compatibility and some new features.
I think I will release it in few days.

**Comment by fbaligand** [comment]
Hi guys,

Great news: enhanced table v1.0.0 is out with Kibana 6.6 support and new filter bar options!
You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.0.0
