### ISSUE TITLE
computed column on empty top hit metric

### ISSUE THREAD

**Issue by hayo0o0o0** [fbaligand/kibana-enhanced-table#238]
I am on kibana version 7.15.2 with enhanced-table 1.12.2

When I try to use a computed column on a null metric top hit, I receive the error:
undefined variable: col0, invalid expression in computed column: col['test']

I named the top hit test
and only added in expression col['test']

To reproduce:
In dev tools:
```
PUT /testmetric
{
 "mappings": {

   "properties": {
    "a": {"type": "keyword"},
    "b": {"type": "keyword"}
   }

 }
}

POST testmetric/_bulk
{ "index":{} }
{ "a":"john doe","b":null }
{ "index":{} }
{ "a":"mary smith","b":"abcd" }
{ "index":{} }
{ "a":"mary smith","b":"efgh" }
```

For the visualization the following export:
[testmetric.txt](https://github.com/fbaligand/kibana-enhanced-table/files/7770976/testmetric.txt)

**Comment by fbaligand** [comment]
Hi,

Thanks for having provided all stuff to reproduce your issue.
So I imported your data & viz in my Kibana 7.15, and reproduced your error.

When you use brackets to reference a column, the column must exist and be valued.
But there is a `col` function that takes a default value when referenced column does not exist or is empty.

So, in your case, you can use this formula:
`col('test', '')`

**Comment by hayo0o0o0** [comment]
@fbaligand thank you, this behavior is new, since my update from kibana 7.13.4 to 7.15.2. In 7.13.4 and enhancedTable 1.12.0 this worked as is with col['test'].
I will follow your suggestion to change it to col function.

**Comment by fbaligand** [comment]
Thanks for the feedback.
This is really strange as enhanced-table core code is exactly the same.
The only changes are integration code with Kibana platform.
