### ISSUE TITLE
Error Displaying Data on Enhanced Table

### ISSUE THREAD

**Issue by diallo1** [fbaligand/kibana-enhanced-table#24]
Hello,

I have a bug on the filter of Enhanced Table.
When I run a search on information that does not exist in the table, I have data that appears below. See the image below.

![image](https://user-images.githubusercontent.com/12812107/52179104-67d4e180-27d6-11e9-9a74-ed69e3d54742.png)

**Comment by fbaligand** [comment]
Bug is now solved in enhanced table v1.0.0
