### ISSUE TITLE
Rows comparison for analytics

### ISSUE THREAD

**Issue by bhavinshah1086** [fbaligand/kibana-enhanced-table#242]
Hi,

I was hoping, can we do comparision of total with last day, last week, last one month something like that in output table.

Regards
Bhavin.

**Comment by fbaligand** [comment]
Well, you can use “split cols” bucket with a “date range” aggregation where each range is last week or last month. 
Then you can add a computed column with a formula based on previous month/week column, using col1 or total1 if you want to reference the column total.

**Comment by fbaligand** [comment]
Given that question is answered, I close the issue.
