### ISSUE TITLE
Wrong data shown if computed column with col() is before the referenced column

### ISSUE THREAD

**Issue by hayo0o0o0** [fbaligand/kibana-enhanced-table#243]
Versions:
Kibana: 1.15.2
enhanced table: 12.2.2

Steps to reproduce:
To reproduce:
In dev tools:
```
PUT /testmetric
{
 "mappings": {

   "properties": {
    "a": {"type": "keyword"},
    "b": {"type": "keyword"}
   }

 }
}

POST testmetric/_bulk
{ "index":{} }
{ "a":"john doe","b":null }
{ "index":{} }
{ "a":"mary smith","b":"abcd" }
{ "index":{} }
{ "a":"mary smith","b":"efgh" }
```

enhanced table setup:
![image](https://user-images.githubusercontent.com/6409301/148612401-ac5b6678-2599-45e6-a979-533ed66ffee3.png)
![image](https://user-images.githubusercontent.com/6409301/148612526-b46f0da9-7592-4e48-b695-0669f30d6a2e.png)

Result:
![image](https://user-images.githubusercontent.com/6409301/148612557-c857f2fd-48dc-466f-8517-9a5ab1712de4.png)

When i move the position to 2 or leave it empty the correct data is filled

**Comment by fbaligand** [comment]
I just reproduced the issue with `col('test')` formula.
That said, with `col1` or `col(1)` or `col['test']` syntax, it works fine.

**Comment by hayo0o0o0** [comment]
Thanks, unfortunately, col['test']  does not work for me as per issue #238, but indeed based on the index it works ok.

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with this issue fixed!
Numerous other enhancements are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0
