### ISSUE TITLE
"Show metrics for every bucket/level" not working in enhanced table 1.12.2

### ISSUE THREAD

**Issue by vsabelli** [fbaligand/kibana-enhanced-table#247]
Hi all,

I have just performed both a ELK stack and enhanced table plugin update.

The current versions are:
7.15.2 ELK (previously used version 7.11.2)
1.12.2 enhanced table (previously used version 1.11.2)

I have migrated some working visualisations to my cluster and I noticed that the switch "Show metrics for every bucket/level" is NOT working anymore.
As a result, many computed columns which relied on those values are currently broken in my dashboard.

Can you please look into this problem?

Thank you!

**Comment by fbaligand** [comment]
Hi @vsabelli,

I confirm that I can reproduce the bug.
I will try to fix it in next release.

**Comment by fbaligand** [comment]
By the way, I reproduce the issue on Kibana 7.14, but not on Kibana 7.13

**Comment by vsabelli** [comment]
Hi @fbaligand ,

thank you for your support and the effort you put into developing this amazing plugin!

Do you have any news about an expected release date which includes this fix?

**Comment by fbaligand** [comment]
Great news: Enhanced Table v1.13.0 is out with this issue fixed!
Numerous other enhancements are also available.

Check it there:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.0
