### ISSUE TITLE
Hide export links has no effect in kibana 6.5.4

### ISSUE THREAD

**Issue by istvanszoboszlai** [fbaligand/kibana-enhanced-table#25]
Does not matter the state of the checkbox, export links are shown

**Comment by fbaligand** [comment]
Hi,

It's very surprising: I just tested enhanced table plugin with Kibana 6.5.4, and "Hide export link" option works fine, both in "Visualization" app and "Dashboard" app.
Sorry to ask it, but did you click "Apply changes" button ?
Do you have errors on browser console ?
Do you have a special context that could explain your issue ?

**Comment by Moermi** [comment]
I had the same issue. After a restart of Kibana, the "Hide export link" button works.

**Comment by fbaligand** [comment]
@Moermi Interesting.
I never managed to reproduce the issue. 
Did you have this issue at first "enhanced-table" plugin use?
Or did it work during a time, and later it failed?

**Comment by Moermi** [comment]
I had the issue when i just installed the plugin and used it for the first time.

**Comment by fbaligand** [comment]
OK, thanks for your feedback.

**Comment by istvanszoboszlai** [comment]
@fbaligand, thanks for the answer, and sorry for the slow response.

It is absolutely no problem that you ask any circumstances. I use enhanced-datatable a lot, even for advanced use-cases like creating a link to another visualization or dashboard.

I use Kibana in docker, so every time it starts, it's a fresh install of the plugin. Kibana inside the official kibana docker image cannot be restarted, because that is the main process of the docker container. I will try to create a custom docker image.

**Comment by fbaligand** [comment]
Goog idea to create a custom image : you can install the plugin during image build

**Comment by istvanszoboszlai** [comment]
So hiding the export links does work when installing first and only starting kibana later with this very simple Dockerfile:

```
FROM docker.elastic.co/kibana/kibana:6.6.0
USER kibana
RUN bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.0.0/enhanced-table-1.0.0_6.6.0.zip
CMD ["/usr/local/bin/kibana-docker"]
```
Thanks for your help again, @fbaligand

**Comment by fbaligand** [comment]
Great to see that your issue is solved!
Thus, your docker image will start in seconds instead of minutes!

**Comment by fbaligand** [comment]
Now that your issue is solved, I close the issue.
