### ISSUE TITLE
Feature request - Return more than 10000 hits

### ISSUE THREAD

**Issue by gplechuck** [fbaligand/kibana-enhanced-table#255]
Hey @fbaligand ,

I like this plugin - the Document Table is very nice and much lighter than the Data Table visualization which depends on aggregations when adding columns, when a simple search would suffice. I understand the limit of 10000 hits in a single search response is imposed by Elasticsearch, but are there any plans to extend the document table to handle more than 10000 hits, by using the scroll API perhaps ? 

Cheers

**Comment by fbaligand** [comment]
Hi @gplechuck,

First, thanks for your interest for Document Table visualization. Happy to see that you find it useful!

Then, the feature you requested for is already available, since enhanced table v1.11.0.
Extract of the release notes:

> Document Table: ability to display more than 10000 rows, in 'Hits size' setting (Kibana 6.6+)

**Comment by gplechuck** [comment]
Excellent, I will try that, thanks. I made a foolish assumption that the releases tracked specific Kibana versions and installed 1.10 first .

**Comment by fbaligand** [comment]
Yes, I regularly add new features and provide it for a lot of Kibana versions!
Before v1.13.0, I supported all possible Kibana versions from Kibana 5.5.
And since v1.13.0, I support all possible Kibana versions from Kibana 6.6.

**Comment by fbaligand** [comment]
As question is answered, I close the issue.

**Comment by gplechuck** [comment]
Installed 1.13.0, working great - thanks

**Comment by fbaligand** [comment]
Happy to hear that!
