### ISSUE TITLE
Use conditional with handlebars

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#26]
Is it possible to test {{value}} in template handlebars to do conditional color rendering ?
Thanks

**Comment by fbaligand** [comment]
Hi @toog,

To do that, this what I do : 
- I add a computed column (say col1) with a formula to generate green ou red, upon previous columns.
Ex: `col0 > 0 ? "green" : "red"`
- I add another computed (say col2) column with this template : 
`<span style="color:{{col1}}">{{value}}</span>`

**Comment by toog** [comment]
Hi @Fabien

Thanks a lot i’ll try rapidly this ..

**Comment by fbaligand** [comment]
I close the issue, given that question is answered.
