### ISSUE TITLE
Enhanced table not working with Kibana 7.17.1

### ISSUE THREAD

**Issue by kw8088** [fbaligand/kibana-enhanced-table#261]
Hi, 

Last week I just upgraded Enhanced Table to v1.13 with Kibana 7.17.0; everything just work fine. (Thanks!) 

But this morning I try to upgrade to Kibana 7.17.1; and Kibana don't start anymore due to the Enhanced Table incompatibility. (See log below)
Just checking if we will have patch soon? 
Thank you.

Here is the log: 
{"type":"log","@timestamp":"2022-03-08T10:38:43+08:00","tags":["error","plugins-service"],"pid":7567,"message":"PluginDiscoveryError: Plugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\". (incompatible-version, /usr/share/kibana/plugins/enhancedTable/kibana.json)\n    at Function.incompatibleVersion (/usr/share/kibana/src/core/server/plugins/discovery/plugin_discovery_error.js:32:12)\n    at parseManifest (/usr/share/kibana/src/core/server/plugins/discovery/plugin_manifest_parser.js:139:56) {\n  type: 'incompatible-version',\n  path: '/usr/share/kibana/plugins/enhancedTable/kibana.json',\n  cause: Error: Plugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\".\n      at parseManifest (/usr/share/kibana/src/core/server/plugins/discovery/plugin_manifest_parser.js:139:90)\n}"}
{"type":"log","@timestamp":"2022-03-08T10:38:43+08:00","tags":["fatal","root"],"pid":7567,"message":"Error: Failed to initialize plugins:\n\tPlugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\". (incompatible-version, /usr/share/kibana/plugins/enhancedTable/kibana.json)\n    at PluginsService.handleDiscoveryErrors (/usr/share/kibana/src/core/server/plugins/plugins_service.js:173:13)\n    at PluginsService.discover (/usr/share/kibana/src/core/server/plugins/plugins_service.js:65:5)\n    at Server.preboot (/usr/share/kibana/src/core/server/server.js:161:30)\n    at Root.preboot (/usr/share/kibana/src/core/server/root/index.js:48:14)\n    at bootstrap (/usr/share/kibana/src/core/server/bootstrap.js:99:9)\n    at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:229:5)"}
{"type":"log","@timestamp":"2022-03-08T10:38:47+08:00","tags":["error","plugins-service"],"pid":7599,"message":"PluginDiscoveryError: Plugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\". (incompatible-version, /usr/share/kibana/plugins/enhancedTable/kibana.json)\n    at Function.incompatibleVersion (/usr/share/kibana/src/core/server/plugins/discovery/plugin_discovery_error.js:32:12)\n    at parseManifest (/usr/share/kibana/src/core/server/plugins/discovery/plugin_manifest_parser.js:139:56) {\n  type: 'incompatible-version',\n  path: '/usr/share/kibana/plugins/enhancedTable/kibana.json',\n  cause: Error: Plugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\".\n      at parseManifest (/usr/share/kibana/src/core/server/plugins/discovery/plugin_manifest_parser.js:139:90)\n}"}
{"type":"log","@timestamp":"2022-03-08T10:38:47+08:00","tags":["fatal","root"],"pid":7599,"message":"Error: Failed to initialize plugins:\n\tPlugin \"enhancedTable\" is only compatible with Kibana version \"7.17.0\", but used Kibana version is \"7.17.1\". (incompatible-version, /usr/share/kibana/plugins/enhancedTable/kibana.json)\n    at PluginsService.handleDiscoveryErrors (/usr/share/kibana/src/core/server/plugins/plugins_service.js:173:13)\n    at PluginsService.discover (/usr/share/kibana/src/core/server/plugins/plugins_service.js:65:5)\n    at Server.preboot (/usr/share/kibana/src/core/server/server.js:161:30)\n    at Root.preboot (/usr/share/kibana/src/core/server/root/index.js:48:14)\n    at bootstrap (/usr/share/kibana/src/core/server/bootstrap.js:99:9)\n    at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:229:5)"}

Best Regards, 
KW

**Comment by fbaligand** [comment]
Well, if you upgrade Kibana version to 7.17.1, you have also to install the enhanced-table package for Kibana 7.17.1.
So you have to install this package:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.17.1.zip

**Comment by hkw2pg1** [comment]
I overlooked this "variant". My bad *facepalm* 

Now it worked :) Cheers!

**Comment by fbaligand** [comment]
Great!
So now that your issue is resolved, I close the issue.
