### ISSUE TITLE
"Show metrics for every bucket/level" not working properly in enhanced table 1.13.0

### ISSUE THREAD

**Issue by vsabelli** [fbaligand/kibana-enhanced-table#262]
Hi all,

I have already filed a similar issue here -> https://github.com/fbaligand/kibana-enhanced-table/issues/247

My ELK/ET versions are:
7.17.1 ELK 
1.13.0 enhanced table

I would like to migrate to this versions, but I have noticed an annoying problem.
Differently from my last filed issue, now I can see some numbers in the split columns, nonetheless they are always 0 for any split but the last one.

Here's a couple examples:
![1](https://user-images.githubusercontent.com/53933206/157460935-33ef5874-1821-4089-a151-f31a71eba5c7.png)
![2](https://user-images.githubusercontent.com/53933206/157460961-e1787dcd-e8d4-4fec-b0ba-0609f2bc7fd3.png)

So, if I hide the last split columns, the first column "magically" shows the right numbers.

Thank you for your support!

**Comment by fbaligand** [comment]
Hi,
After some tests, it seems to appear only for other aggregations than "Count".

**Comment by fbaligand** [comment]
Hi,

I just fixed the bug. It will be part of next release.

**Comment by fbaligand** [comment]
Hi @vsabelli,

The issue has been fixed in last version v1.13.1:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.1

**Comment by vsabelli** [comment]
Hi @fbaligand ,

thank you! I will test it asap :)

**Comment by vsabelli** [comment]
Hi @fbaligand ,

everything working fine, thank you again for your support and your effort! 🥇

**Comment by fbaligand** [comment]
Happy to hear that!
