### ISSUE TITLE
"Show partial rows " not working properly in enhanced table 1.13.1

### ISSUE THREAD

**Issue by RPaolo** [fbaligand/kibana-enhanced-table#263]
Hi all,

My ELK/ET versions are:
7.15.2 ELK
1.13.1 enhanced table

With this new version of enhanced table when we enabled 'show partial rows, nothing happens.

before:  1.12.2 enhanced table
![image](https://user-images.githubusercontent.com/32684111/160088077-9ed671ae-abca-45d7-a1d1-c05007271f2c.png)

after: 1.13.1 enhanced table
![image](https://user-images.githubusercontent.com/32684111/160088986-4295e564-7aa1-44e6-b725-a79650abd21c.png)

**Comment by fbaligand** [comment]
Hi,

Question. Could you precise what is enhanced table version and kibana version in your "before" screenshot?

**Comment by RPaolo** [comment]
> Hi,
> 
> Question. Could you precise what is enhanced table version and kibana version in your "before" screenshot?

version: 7.11.2

**Comment by fbaligand** [comment]
Thanks, so I think that problem is not tied to enhanced table version but kibana version. 
Could you test with enhanced table version 7.13.0 and kibana version 7.11.2?

**Comment by RPaolo** [comment]
> Thanks, so I think that problem is not tied to enhanced table version but kibana version. Could you test with enhanced table version **7.13.0** and kibana version 7.11.2?

enhanced table version 1.13.0?  and kibana version 7.11.2

**Comment by fbaligand** [comment]
Yes, enhanced table v1.13.1 is a patch version only for a bug on kibana 7.14+

**Comment by fbaligand** [comment]
Do you get the expected result if you do the same visualization with classic "Data Table"?
Could you export and share your visualization json configuration?

**Comment by RPaolo** [comment]
With both versions, 7.11, 7.15 Show partial rows give no results for the daa table. Show partial rows only results on kibana version 7.11.2 on enhanced table version 1.12.2. Maybe the classic 'Data table' is not usable becouse it does not have 'split cols'.
These are the photos of the metrics and buckets applied to kibana 7.11.2, enhanced table version 1.12.2.
![image](https://user-images.githubusercontent.com/32684111/160558313-22ea2e8e-03fa-480b-84ee-5bfc302dbeeb.png)
![image](https://user-images.githubusercontent.com/32684111/160558376-0e4fafbd-d759-402d-bba2-897c4c3623eb.png)
![image](https://user-images.githubusercontent.com/32684111/160558444-1d8217ac-b7ef-4e0b-b2e7-55d3824192b8.png)
![image](https://user-images.githubusercontent.com/32684111/160558487-de9a6901-be44-40e6-81a0-2d7cc64df381.png)

**Comment by RPaolo** [comment]
Thanks for support. I will update the kibana version to 7.16 soon

**Comment by fbaligand** [comment]
Nice!

As a solution is provided for this issue, I close the issue.
