### ISSUE TITLE
Can't install Enhanced Table in OpenSearch Dashboard

### ISSUE THREAD

**Issue by singhavnish26** [fbaligand/kibana-enhanced-table#265]
Hi @fbaligand I tried to install the plugin in my OpenSearch Dashboard using the steps you provided but got this error:

`[oss@ip-10-92-3-133 opensearch-dashboard]$ bin/opensearch-dashboards-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.1_osd-1.2.0.zip

Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.1_osd-1.2.0.zip

Attempting to transfer from https://artifacts.opensearch.org/downloads/kibana-plugins/https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.1_osd-1.2.0.zip/https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.1_osd-1.2.0.zip-1.2.0.zip

Plugin installation was unsuccessful due to error "No valid url specified."

[oss@ip-10-92-3-133 opensearch-dashboard]$
`

Not sure what to do next please help.

**Comment by fbaligand** [comment]
Well, your package URL is wrong.

The good one is:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.1/enhanced-table-1.13.1_osd-1.2.0.zip

**Comment by singhavnish26** [comment]
Thanks @fbaligand issue resolved.
