### ISSUE TITLE
Question: How to show row total over split column

### ISSUE THREAD

**Issue by hoberhol** [fbaligand/kibana-enhanced-table#278]
Hi all

I'm facing quite often the problem, that I would like to show the row total over the currently displayed split columns .

The following example is showing some values for some employees for some months (split columns). I would like to also show a total for each employee (yellow).

![enhancedTableIssue](https://user-images.githubusercontent.com/65902724/184938228-335c5a84-7769-4d52-849a-52726a4d1fbd.png)

Does anyone can help me with this? Seems to be quite an easy task, but so far I was not able to find the solution.

Thanks a lot.

**Comment by fbaligand** [comment]
Hi,

To do that, you add a "computed column", and in "Formula", you put `sumSplitCols()`

You can view all available methods in "Formula" here:
https://github.com/fbaligand/kibana-enhanced-table/#available-functions

**Comment by hoberhol** [comment]
Hi,

Thanks a lot for your support. 
With your proposed solution I'm able to achieve a total over split column like this:

![image](https://user-images.githubusercontent.com/65902724/185034366-886956ad-46d7-4040-a8de-c34db35121ba.png)

Unfortunately, I'm no longer able to format the cells, as I cannot used computed columns for the split columns and a total computed column the same time...or this it at least what I found out.

![image](https://user-images.githubusercontent.com/65902724/185034747-221e4357-d273-4200-898b-dbc52b75b34e.png)

In order to use computed columns in the split columns I need to enable the option "Computed/Hidden cols per split col". That way the computed column for the total is now also calculated for each month and no longer as a total of all months.


![image](https://user-images.githubusercontent.com/65902724/185035166-e2b47dea-f59e-4667-b3ca-8143ae295798.png)

![image](https://user-images.githubusercontent.com/65902724/185035231-d00f0c7f-6d24-4750-89d7-684c44a08bdf.png)

I've tried to use "Custom column position = 1" for the total computed columns. But this is getting some strange result:

![image](https://user-images.githubusercontent.com/65902724/185035806-4c7b34d5-edd0-4a4c-b246-60f9d585e18a.png)

Do you have a solution for this? Or is it just not possible?
As I'm using quite often the split column feature and almost always a total would be important, a solution to this would help me a lot. It is also always necessary to format the columns (number format, color, formula), therefore I need to be able to use the computed column for the split columns.

Thanks a lot for your support.

**Comment by fbaligand** [comment]
Hi,
Unfortunately, it is not possible to have both "computed columns per split col" and "computed columns for all cols".
There is a feature request for this: https://github.com/fbaligand/kibana-enhanced-table/issues/54
You can "+1" it to give it more priority.

That said, given your specific use case, maybe you could try with this setting enabled: "Show metrics for every bucket/level".
It should add "total" column.
