### ISSUE TITLE
error on 8.4.1

### ISSUE THREAD

**Issue by cdgh2021** [fbaligand/kibana-enhanced-table#285]
i build a zip from main branch ,for kibana version 8.4.1. build ok, but run error:
```
TypeError: Cannot set property hierarchical of #<agg_configs_AggConfigs> which has only a getter
    at expression_function_ExpressionFunction.fn (http://localhost:5601/55434/bundles/plugin/enhancedTable/kibana/enhancedTable.plugin.js:1:35310)
```
any help?

**Comment by fbaligand** [comment]
Hi @cdgh2021,

Well, Kibana 8.4 brings some breaking changes that require some code changes in enhanced table plugin.
I will release this week a new enhanced table plugin version that is compatible with Kibana 8.4.

**Comment by fbaligand** [comment]
Hi @cdgh2021,

Enhanced Table plugin version 1.13.3 is out, with support for Kibana 8.4:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.3

**Comment by fbaligand** [comment]
Hi,
For information, with same Enhanced Table v1.13.3 release, Kibana 8.5 is now supported!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.3

**Comment by fbaligand** [comment]
Hi,
For information, with same Enhanced Table v1.13.3 release, Kibana 8.6 is now supported!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.3
