### ISSUE TITLE
Add threshold filter

### ISSUE THREAD

**Issue by numbnut** [fbaligand/kibana-enhanced-table#29]
Hi @fbaligand ,
are you interested in adding a threshold filter, like only show rows with a value bigger than x in column y? We are currently using a fork of the internal table visualization for doing that, but it could make sense to integrate it in your enhanced table visualization. What do you think about it? Would you be open minded to integrate such a feature? 
Thank you!

**Comment by fbaligand** [comment]
Hi @numbnut,

Well, I have good news for you: this feature is already implemented and will be part of the next release!
I will notify you here when the release will be out!

**Comment by numbnut** [comment]
Hi @fbaligand, this is great news. Thanks for sharing this. Do you have a rough estimation, when this next release will be published? Is it possible to have a look at a beta version before? I didn't find any related commits in the repository. Thanks again!

**Comment by fbaligand** [comment]
Indeed, I have not yet pushed my code on github. So, for now, it is only on my computer :)
I can't give you an exact date, but I think it should be released in 1 or 2 weeks.

**Comment by numbnut** [comment]
Thanks again for the information. If you need some assistance for final testing or something else, please let me know.

**Comment by fbaligand** [comment]
Thanks for proposal!

**Comment by fbaligand** [comment]
Hi @numbnut 

I have great news for you: I just released enhanced-table v1.1.0, with the feature you wish here!
So now, you have a new option called "Lines computed filter", where you can fill a boolean formula telling which lines are kept in the table.
For example: `col0 > 0`

There are also some other new features!
Check it out here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.1.0

**Comment by numbnut** [comment]
Hi @fbaligand, thank you very much. I will have a look at it soon.

**Comment by fbaligand** [comment]
Hope you will enjoy the feature!
