### ISSUE TITLE
Request: naming for column > split rows > filters

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#290]
When adding a bucket of Split Rows by filter, the column name is set as "filters".

It would be fantastic to be able to rename that column name. As I type this, I guess I could probably hide col0 and add a new computed column and set the desired name there, so we have a workaround...! :D
![Screenshot 2022-09-16 at 12 20 04](https://user-images.githubusercontent.com/44969282/190628267-3ff1aa09-ef75-4fa3-8bd9-94abfef0d10b.png)
![Screenshot 2022-09-16 at 12 20 11](https://user-images.githubusercontent.com/44969282/190628268-624f1f70-05ba-4b55-beda-fbc971c72874.png)

**Comment by fbaligand** [comment]
Hi,

I agree that it is annoying to have this "fixed column name".
I personally have been annoyed by this.

But to be precise, the issue more about the bucket aggregation itself, that is responsible to say "what is the column name".
You have exactly the same problem on any other visualization, especially standard "Data Table".

The good solution would be to add a "Custom label" field, like most other bucket aggregations.

So I invite you to open an issue on Kibana repository itself:
github.com/elastic/kibana/issues/
