### ISSUE TITLE
Display only the total row

### ISSUE THREAD

**Issue by dnyamy** [fbaligand/kibana-enhanced-table#294]
Hi all,

And thanks a lot for this plugin.
I have a visualization with computed columns.
I would like to display only the header line and the total line. Not all the details (See attached screenshot)
Please how can I do that ?
Regards
Dn

![Sans titre](https://user-images.githubusercontent.com/43039376/200202601-a8c084e8-6e9b-4cb6-8332-96099e51505c.png)

**Comment by AJ1058308** [comment]
Hi,
Thank you for your reply
The fields are computed columns and won't appear for selection for metric agg
Hope I will be able to find a work around
Thanks
Regards
Dn

**Comment by fbaligand** [comment]
What do you mean by "The fields are computed columns and won't appear for selection for metric agg"?
If you have no "bucket" agg, but only "metric" aggs, computed columns will still be displayed.
To understand well your vis, do you use "Enhanced Table" or "Document Table" visualization?

**Comment by dnyamy** [comment]
I use Enhanced Table,
I cannot but use the bucket agg, for my BAT-, BAT, BAT+, BAT++ columns are computed based on columns from the Split cols bucket.

**Comment by fbaligand** [comment]
OK, do you can keep your “split cols” bucket, but remove all “split rows” columns. 
Like that, you will have only one data line.

**Comment by dnyamy** [comment]
The problem is that I also need the split "rows columns" to compute my computed columns.
I think I will just keep the table as is.
Thank you
Dn

**Comment by fbaligand** [comment]
OK. 
For info, if your computed columns require some fields, you can eventually use “top hit” metric. 
not else, you keep table as is 😉

**Comment by fbaligand** [comment]
As question is answered, I close the issue.
