### ISSUE TITLE
Issue with handlebars

### ISSUE THREAD

**Issue by didinyah** [fbaligand/kibana-enhanced-table#3]
I have kibana 6.2.4 on one server and handlebars doesn't work (i tried header brackets, bold, italic, etc.. nothing works)
![image](https://user-images.githubusercontent.com/16062002/40238977-095c5fb4-5ab5-11e8-8234-1a80e93d56e0.png)

It was working fine on Kibana 5.6.6 though, with the same data...
![image](https://user-images.githubusercontent.com/16062002/40239174-9228dee4-5ab5-11e8-9095-3af9967c84ff.png)

I tried to put a string, a number, nothing works... and no error in console...

**Comment by fbaligand** [comment]
Hi @didinyah 

I'm surprised, because I made tests on Kibana 6.2.0, so I didn't expect to have such a feature not working on Kibana 6.2.4.

I will make tests on Kibana 6.2.4 and try to reproduce the issue.

**Comment by fbaligand** [comment]
Hi @didinyah,

I just made tests with Kibana 6.2.4, and HTML template works fine.
But indeed, some HTML does not imply style change. For example : h2, b and i.

On the contrary, these 2 examples work great : 
<strong>{{value}}</strong>
<span style="color: red">{{value}}</span>

**Comment by didinyah** [comment]
Yes indeed, so the only workaround for this issue would be to change the style. I managed to do it with 
`<span style="font-size: 2rem">{{value}}</span>`.

Thank you for your help.

**Comment by fbaligand** [comment]
Yes, that's a way to do what you want.

By the way, I just updated the sample documentation : 
- replace `<b>` sample by `<strong>`
- use `<span style="...">` in template sample
