### ISSUE TITLE
Missing requirement at restart of kibana

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#301]
hello

Today we had a problem when we restarted the computer.
kibana failed to start correctly. In the Kibana log there was this message continuously

``
{
    "type": "log",
    "@timestamp": "2022-12-13T15:22:22+01:00",
    "tags": [
        "fatal",
        "root"
    ],
    "pid": 3827,
    "message": "Error: Cannot find module '/home/ELK/kibana/plugins/enhancedTable/server'\nRequire stack:\n- /home/ELK/kibana/src/core/server/plugins/plugin.js\n- /home/ELK/kibana/src/core/server/plugins/discovery/plugins_discovery.js\n- /home/ELK/kibana/src/core/server/plugins/discovery/index.js\n- /home/ELK/kibana/src/core/server/plugins/plugins_service.js\n- /home/ELK/kibana/src/core/server/plugins/index.js\n- /home/ELK/kibana/src/core/server/server.js\n- /home/ELK/kibana/src/core/server/root/index.js\n- /home/ELK/kibana/src/core/server/bootstrap.js\n- /home/ELK/kibana/src/core/server/index.js\n- /home/ELK/kibana/src/cli/serve/serve.js\n- /home/ELK/kibana/src/cli/cli.js\n- /home/ELK/kibana/src/cli/dist.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Module.Hook._require.Module.require (/home/ELK/kibana/node_modules/require-in-the-middle/index.js:61:29)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at PluginWrapper.getConfigDescriptor (/home/ELK/kibana/src/core/server/plugins/plugin.js:149:30)\n    at MergeMapSubscriber.project (/home/ELK/kibana/src/core/server/plugins/plugins_service.js:180:39)\n    at MergeMapSubscriber._tryNext (/home/ELK/kibana/node_modules/rxjs/internal/operators/mergeMap.js:67:27)\n    at MergeMapSubscriber._next (/home/ELK/kibana/node_modules/rxjs/internal/operators/mergeMap.js:57:18)\n    at MergeMapSubscriber.Subscriber.next (/home/ELK/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at FilterSubscriber._next (/home/ELK/kibana/node_modules/rxjs/internal/operators/filter.js:52:30)\n    at FilterSubscriber.Subscriber.next (/home/ELK/kibana/node_modules/rxjs/internal/Subscriber.js:66:18) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/ELK/kibana/src/core/server/plugins/plugin.js',\n    '/home/ELK/kibana/src/core/server/plugins/discovery/plugins_discovery.js',\n    '/home/ELK/kibana/src/core/server/plugins/discovery/index.js',\n    '/home/ELK/kibana/src/core/server/plugins/plugins_service.js',\n    '/home/ELK/kibana/src/core/server/plugins/index.js',\n    '/home/ELK/kibana/src/core/server/server.js',\n    '/home/ELK/kibana/src/core/server/root/index.js',\n    '/home/ELK/kibana/src/core/server/bootstrap.js',\n    '/home/ELK/kibana/src/core/server/index.js',\n    '/home/ELK/kibana/src/cli/serve/serve.js',\n    '/home/ELK/kibana/src/cli/cli.js',\n    '/home/ELK/kibana/src/cli/dist.js'\n  ]\n}"
}
``

we solved the issue by removing the plugin and reinstalled it.

version OS : Linux ubuntu 22.04
version plugin : 1.13.1
version of kibana : 7.16.3

**Comment by fbaligand** [comment]
So you got this error, then uninstalled enhanced-table plugin, then reinstalled enhanced-table plugin, and finally it works, right?
That's quite surprising...

By the way, the error is `Error: Cannot find module '/home/ELK/kibana/plugins/enhancedTable/server'`. Very surprising, because enhanced-table plugin has no server part. And it has never been a problem, neither for Kibana 5, 6, 7 and 8.

Maybe you first installed the plugin while Kibana was up?

**Comment by toog** [comment]
ok this log it's curious, i will check if this issue occur in the futur.
thank's for the answers.
