### ISSUE TITLE
not able to see the plugin after installing - 8.4.0

### ISSUE THREAD

**Issue by shashankdevaraj** [fbaligand/kibana-enhanced-table#307]
I could not able to see the plugin after installing in the visualization 

./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.3/enhanced-table-1.13.3_8.4.0.zip

**Comment by shashankdevaraj** [comment]
@fbaligand - please help - any known issues

**Comment by fbaligand** [comment]
Hi,

there is no known issue. I tested the plugin on kibana 8.4.0 and it worked fine. 

Few questions: 
- have you restarted kibana after plugin install?
- when you access kibana in your browser, go to Visualize tab, and then click on « aggregation based visualizations ». Here you should see « Enhanced Table » and « Document Table » visualizations
- If it still doesn’t work, completely remove your browser cache (ctrl+shift+suppr on chrome), and then refresh your web page (ctrl+f5)

**Comment by shashankdevaraj** [comment]
Thank you for the quick response @fbaligand

**Comment by fbaligand** [comment]
wjdx

**Comment by fbaligand** [comment]
Question is answered so I close the issue.
