### ISSUE TITLE
Support for Kibana 6.7.0

### ISSUE THREAD

**Issue by lmtjalves** [fbaligand/kibana-enhanced-table#31]
Currently the plugin doesn't seem to be compatible with Kibana 6.7.0.

**Comment by fbaligand** [comment]
Indeed, enhanced-table is not yet compatible with Kibana 6.7.0.
I will work on this issue, this or next week.

**Comment by WeslyG** [comment]
Thank you for supporting this great plugin, I put the latest version of the plugin by changing the version in the package.json and everything works, maybe there are bugs, I have not met.

**Comment by fbaligand** [comment]
@WeslyG I'm very surprised, because I tried this last week, and get whole Kibana app blocked with a red message.

**Comment by npicado** [comment]
+1

**Comment by WeslyG** [comment]
I am install plugin inside docker contaier.

1. download last-plugin.zip 
2. update version package.json inside last-plugin.zip to 6.7.0
3 docker cp last-plugin.zip hash:/tmp/
4 docker exec -it hash bash
5 ./bin/kibana-plugin install file:///tmp/last-plugin.zip
....
container be stop
6. docker-compose up -d 

for more detailed playback I created a test repository, you can see it yourself in Readme.md here https://github.com/WeslyG/table-test

**Comment by fbaligand** [comment]
Well, I’m very surprised it works for you. 
I tried again this morning, and it didn’t work. 
I tried to make the package with standard way to build it, then with latest yarn version, and it still didn’t work. 
=> you should be a lucky :)

**Comment by fbaligand** [comment]
Hi,

So, given that: 
- I managed to make enhanced-table v1.0.0 work fine with kibana 6.7.0 in "dev" mode
- @WeslyG managed to make enhanced-table v1.0.0 work with kibana 6.7.0 on docker

I finally release enhanced table v1.0.0 for Kibana 6.7.0 and 6.7.1.
Packages are available here:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.0.0/enhanced-table-1.0.0_6.7.0.zip
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.0.0/enhanced-table-1.0.0_6.7.1.zip

That said, given that I don't manage to make it work on my computer with a Kibana 6.7.0/6.7.1 standard distribution and Kibana 6.7.0 OSS distribution, I will raise an issue on Kibana core github and try to discuss with Kibana Core team.

**Comment by lmtjalves** [comment]
Since Elastic 7.0 was released, can you also add support for this version (probably not as simple as for 6.7.X). If you prefer, I can open a separated issue for 7.0.

**Comment by fbaligand** [comment]
Hi,

As you can guess, there is much more work to do to bring Kibana 7.0 compatibility. 
So please open a new issue for it.

**Comment by npicado** [comment]
Hi Fabien.
Thank you for your great work.
People, maybe we need to support him ($$) so he can assign a little more time on this project.
Do you have Patreon?

**Comment by fbaligand** [comment]
Hi @npicado ,

I don't have a Patreon account for now.
Thanks for your support, that's rewarding!
If I create an account, I will notify you.

**Comment by fbaligand** [comment]
I just released enhanced-table v1.1.0, that fixes Kibana 6.7 plugin installation. You can install this version on Kibana 6.7, using the standard way to install a plugin.
There are also several new features!
Check it out here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.1.0

**Comment by fbaligand** [comment]
I close this issue, as Kibana 6.7 support is now fully fixed.
If you want support for Kibana 7.0, please open another issue.
