### ISSUE TITLE
Computed column to assign Rank

### ISSUE THREAD

**Issue by PunamNaik** [fbaligand/kibana-enhanced-table#312]
I have a column for total no. of transactions done by customers. I need to add a column for Rank and assign rank(1,2,3,...) to these customers based on no. of transactions. How can I achieve this.

**Comment by fbaligand** [comment]
First, I guess that you have one row by customer, using a "Terms" bucket.
So you can sort your customers bucket by "no. of transactions" metric (descending order).
Then you check "Add a row number column" option. It will add head column "#" that is actually the rank.

**Comment by fbaligand** [comment]
Well, to my known, you can sort lines  customer id by descending Total Txn.
But I have no solution to generate a Rank column as you wish. 

it is possible using « # » column trick. 
But it works only if you have one row per customer id. That is not your case.
