### ISSUE TITLE
Add total on each column

### ISSUE THREAD

**Issue by WeslyG** [fbaligand/kibana-enhanced-table#32]
I'm very happy to see col[1] col[2] col[3] data. 
But I really want to be able to get total[1] total[2] total[3] now, I only have total anyway. 
Did I understand correctly that I can't access total col[3] ? And is there a possibility of similar behavior of the plugin in the future?

**Comment by fbaligand** [comment]
Hi @WeslyG,

Currently, this feature does not exist in the plugin. But given that there are 3 issues asking such a feature, I plan to add this feature in the future.

Waiting, here's a tip to have similar feature right now:
- add a "Filters" bucket with 1 filter "*"
- add a metric that matches the total function you expect (sum, max, ...)
- check "Show metrics for every bucket/level" (in Options tab)
- use this first col value in your computed column. It should be the "total" you expect.
- finally hide this first "Filters" bucket column

**Comment by fbaligand** [comment]
enhanced-table v1.6.0 is out! With support for column total reference in computed column formulas and templates! Ex: `col2 / total2`
You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.6.0
