### ISSUE TITLE
Date Histogram is not generating date columns in sequence

### ISSUE THREAD

**Issue by PunamNaik** [fbaligand/kibana-enhanced-table#323]
Date Histogram is not generating date columns in sequence. 
<img width="928" alt="image" src="https://github.com/fbaligand/kibana-enhanced-table/assets/61153360/50dc8faf-0987-4280-8b69-8cf7dd642431">
On giving histogram interval as DAY, It should have generated dates in sequence, my date format is YYYY-MM-DD, but sorting is not date wise. Am I missing something here.

**Comment by fbaligand** [comment]
Hi,

You can have the columns in the right order, by checking "sort split columns" option, in "Options" tab.
