### ISSUE TITLE
Auto interval change in date histogram

### ISSUE THREAD

**Issue by PunamNaik** [fbaligand/kibana-enhanced-table#324]
In below day level date histogram is showing up daywise when a particular month is selected from dropdown. (global time filter is kept last 1 year)
<img width="641" alt="image" src="https://github.com/fbaligand/kibana-enhanced-table/assets/61153360/41d6426e-809a-409c-8b1a-f390a215f27d">
But when I change the global time filter to more than 1 year window. It automatically changes the histogram interval from daily to monthly aggregation.
<img width="521" alt="image" src="https://github.com/fbaligand/kibana-enhanced-table/assets/61153360/2ca1c21f-b983-452d-9f86-a6626045db3f">

Is there any limitation with regards to time on such visuals? 
Also sometimes I ran into this error "too_many_buckets_exception". My 1st bucket size is 20000. Total buckets are 13.
The table takes too long to load. Any points I can reconsider here.

**Comment by fbaligand** [comment]
Hi,

well, both problems are not tied directly to enhanced table plugin, but more to kibana itself. Kibana or Elasticsearch itself) limits to 10000 buckets in a aggregation query. 
And the correction you see in date histogram is not done by enhanced table but by kibana. 
you can try to set « day » in date histogram configuration. Maybe it could fix or not. 
if you look at Inspect link, you can view Elasticsearch request and response.
