### ISSUE TITLE
how to get contains string in computed columns

### ISSUE THREAD

**Issue by sandeepr43** [fbaligand/kibana-enhanced-table#327]
Hi,

I'm trying to get contains a particular string in computed columns:

For example 

`
col1 : "I have removed this now".
`

`
col2 : (col1 contains "removed") ? "Removed" : "present".
`

How can we implement this in computed column?

Thanks in Advance

**Comment by fbaligand** [comment]
Hi,

You can find here all available functions here:
https://github.com/fbaligand/kibana-enhanced-table#available-functions

To reach your goal, you can do this:
`indexOf(col1, "removed") != -1 ? "Removed" : "present"`
