### ISSUE TITLE
Question about AWS and Enhanced Table (aug 2023)

### ISSUE THREAD

**Issue by luizibfilho** [fbaligand/kibana-enhanced-table#329]
Hello! I am a relatively new professional when it comes to the ELK stack. I have some dashboards hosted locally and I want to transfer them to Elastic Cloud (AWS). I am currently on version 7.17.12

Does AWS still reject third-party plugins like Enhanced Table?

**Comment by fbaligand** [comment]
To my known, on Elastic Cloud, Kibana community plugins are not allowed.
Sorry.
