### ISSUE TITLE
plugin not working in windows 10

### ISSUE THREAD

**Issue by touchstonemark** [fbaligand/kibana-enhanced-table#33]
hi, I have downloaded the zip for version 6.6.2 and in windows 10 opened an admin powershell window and run 'c:\elk6\kibana-6.6.2-windows-x86_64\bin\kibana-plugin install file:///c:/elk6/enhanced-table-1.0.0_6.6.2.zip'  - the process completes after few minutes wait and I then restarted the laptop. When opening Kibana the new options are not visible for the plugin. any suggestions for what is going wrong with the process ?

**Comment by touchstonemark** [comment]
looked to be permissions related now resolved.

**Comment by fbaligand** [comment]
Nice to see you resolve your issue!
Enjoy the plugin :)
