### ISSUE TITLE
OpenSearch Dashboards 2.10 release

### ISSUE THREAD

**Issue by spapadop** [fbaligand/kibana-enhanced-table#337]
Hello,

Firstly, thanks a lot for the developments in this plugin! :) 
I guess the new OpenSearch Dashboards compatible zip file should be expected under the latest v1.13.5 release assets?
Are there any blockers on this?

**Comment by fbaligand** [comment]
Hi,

enhanced table for osd is available in 1.13.3 release, given that newer releases embed only compatibility for last kibana versions. 
here it is:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.3

**Comment by spapadop** [comment]
Hello,

Thanks, just to double-check, so OSD will not be supported any longer for any new enhanced-table releases?
Also, in v1.13.3 there are zip files till OSD v2.9.0, so I guess that is the latest and last supported OSD version?

**Comment by fbaligand** [comment]
I reassure you, I provide support for every OSD versions 1.x & 2.x.
And when OSD 3.x will be out, I will try to make the plugin compatible with.

And so, package for OSD 2.10.0 is really available in v1.13.3 release:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.3/enhanced-table-1.13.3_osd-2.10.0.zip

Don't forget that GitHub sorts files by name, and that 2.10.0 is "alphabetically" before 2.2.0.

**Comment by spapadop** [comment]
Oh, I see. Sorry for the noise and many thanks for the reassurance :)
