### ISSUE TITLE
OpenSearch Dashboards 2.11 release

### ISSUE THREAD

**Issue by fbellomi** [fbaligand/kibana-enhanced-table#338]
Hello,

could you please release a build for OSD 2.11?
I checked in the 1.13.3 page release and the last one added is 2.10

thanks

**Comment by fbaligand** [comment]
Well, OSD 2.11 brings breaking changes that require code changes in enhanced table plugin. I already tried several changes but it’s not enough. 
So that’s why it is not out for now.

**Comment by fbellomi** [comment]
Thanks for your efforts

**Comment by sduenas** [comment]
Any update on the progress of this?

I'm also wondering about what approach you will follow. OSD removed Ansible in 2.11 and this plugin is fully dependent of it, so will you remove it fully from the version for OSD and for Kibana? do you plan to drop the support of OpenSearch?

Thanks for all your work!

**Comment by fbaligand** [comment]
Hi,
Well, I guess that you mean "AngularJS" and not Ansible?
Yes, this plugin is fully dependent of AngularJS. And this is why, today, there is still no package provided for OSD 2.11.
That said, on Kibana, there is no AngularJS today, and I managed to maintain the plugin by embedding AngularJS inside the plugin itself. I hope I will manage to do it also with OSD 2.11.
But there is a bunch of work to do...

**Comment by sduenas** [comment]
Sorry, I meant Angular. My mistake.
All clear now. I thought in Kibana the still had some pieces of Angular around but it's been some years since last time I used it.
I'm sure there's so much work to do to support both solutions.
Anyway, thanks for your work!

**Comment by NMAP97** [comment]
Hi @fbaligand ,
I see that you have pushed some changes to support OpenSearch Dashboards 2.11.

https://github.com/fbaligand/kibana-enhanced-table/commit/7ae2a76c86bd4264c4e80746fcf22094063fa7f9

Is this the final change?

Is the plugin for use in OpenSearch Dashboards 2.11?

Any update on support for OpenSearch Dashboards 2.11 is very much appreciated.

Thanks for your work!

**Comment by fbaligand** [comment]
Hi @NMAP97,

I'm happy to confirm you that - given my tests - this commit definitely fix OpenSearch Dashboards 2.11 support!

I will soon make a new 1.14.0 release with this feature but also other features.

But as I know that OSD 2.11 support is highly expected, I provide here some pre-releases.
Don't hesitate to test them and tell me if it works as expected or if you see some issues.

[enhanced-table-1.14.0-alpha1_osd-2.11.1.zip](https://github.com/fbaligand/kibana-enhanced-table/files/13727732/enhanced-table-1.14.0-alpha1_osd-2.11.1.zip)
[enhanced-table-1.14.0-alpha1_osd-2.11.0.zip](https://github.com/fbaligand/kibana-enhanced-table/files/13727733/enhanced-table-1.14.0-alpha1_osd-2.11.0.zip)

**Comment by NMAP97** [comment]
This is a great news, @fbaligand 

I'll test it and let you guys know:-)

**Comment by fbaligand** [comment]
Enhanced Table v1.14.0 is out! With official support for OSD 2.11 and numerous other features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.14.0
