### ISSUE TITLE
6.7.1 issue

### ISSUE THREAD

**Issue by mdnuts** [fbaligand/kibana-enhanced-table#34]
After the plugin is loaded, when navigating to kibana i get the message "kibana did not load properly. check the server output for more information"  Logs show status of 304.

In earlier versions this usually meant permissions were not set.  i went in to the /usr/share/kibana folder and set user/group to kibana for everything - and got the same status.  If I remove the plugin kibana loads just fine.

I installed it via ##kibanahome##/bin/kibana-plugin install enhanced-table...zip  The optimization in earlier attempts (of 6.7.1) lasted under a minute.

**Comment by fbaligand** [comment]
Well, indeed, there is an issue since Kibana 6.7. I know it, and opened an issue on Kibana repository here:
https://github.com/elastic/kibana/issues/34680
I will try to talk to Kibana core team tomorrow about that.

That said, here's the tip to make plugin installation successful : 
- copy $KIBANA_HOME/plugins/enhanced-table/public/index.css to $KIBANA_HOME/built_assets/css/plugins/enhanced-table/
- just reload Kibana app in browser and it will be OK

**Comment by mdnuts** [comment]
Yeah that sure worked.  Thank you for the reply on it.

not at all related to this - just in Elastic Stack 6.7 in general.  I noticed something else odd going from 6.6 to 6.7 with logstash.  it required the I/O temp directory in jvm.options to be set where previous versions I never touched it.

**Comment by fbaligand** [comment]
Nice to see that my tip work for you.
Concerning Logstash, thanks for the info. I didn't know about it.

**Comment by jorgelbg** [comment]
If by any chance you're running Kibana in Docker or an orchestrator (like Kubernetes or Nomad) you can work around the issue by adding this to a custom `Dockerfile`:

```
RUN mkdir -p $HOME/built_assets/css/plugins/enhanced-table/
RUN cp $HOME/plugins/enhanced-table/public/index.css $HOME/built_assets/css/plugins/enhanced-table/
```

`$HOME` defaults to `/usr/share/kibana`

**Comment by mdnuts** [comment]
Im not - at least not yet.

**Comment by fbaligand** [comment]
Thanks @jorgelbg for the share.

**Comment by fbaligand** [comment]
@mdnuts 
If you don't use containers, you can still "manually" execute the 2 commands : 
```
mkdir -p $KIBANA_HOME/built_assets/css/plugins/enhanced-table/
cp $KIBANA_HOME/plugins/enhanced-table/public/index.css $KIBANA_HOME/built_assets/css/plugins/enhanced-table/
```

**Comment by mdnuts** [comment]
Yeah, that had worked just fine

**Comment by fbaligand** [comment]
Great!

**Comment by fbaligand** [comment]
Hi, 

I just released enhanced-table v1.1.0, that fixes this issue. You can install this version on Kibana 6.7, using the standard way to install a plugin.
There are also several new features!
Check it out here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.1.0

**Comment by mdnuts** [comment]
i finally had a moment to try and installing it again on a fresh ELK build - and it installed just fine.  thank you.

**Comment by fbaligand** [comment]
Nice!
