### ISSUE TITLE
Trouble installing under Kibana 8.11.2

### ISSUE THREAD

**Issue by mcforman** [fbaligand/kibana-enhanced-table#340]
Hello,

Firstly, great plugin that looks as though it'll do exactly what I'm after.

I have been trying to get version 1.13.5 installed into an Ubuntu 22.04.3 system running Kibana 8.11.2, but without success. As soon as I try to create a visualisation (either Enhanced Table or Document Table), an error is displayed, which appears to relate to local Javascript code. Using Firefox 120.0.1 (Mac OS), one of the following is displayed:

1. "can't access lexical declaration 'xt' before initialization" – full error text: `initLocalAngular@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.chunk.1.js:31:57387`
2. "o is undefined" – full error text: `@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.chunk.1.js:1:2266
@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.chunk.1.js:1:3215
i@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.plugin.js:1:361
@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.chunk.1.js:30:66309
i@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.plugin.js:1:361
@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.chunk.1.js:31:39519
i@http://nipp-backup:5601/68299/bundles/plugin/enhancedTable/1.13.5/enhancedTable.plugin.js:1:361`

Have also tried this using Safari 16.6.1 (Mac OS) and behaviour is pretty much the same (just some minor variation in the language of the messages).

No errors at all installing and using enhanced-table 1.13.3 on an Ubuntu 22.04.1 system running Kibana 7.17.8, but for my application I really need to have it running under 8.11.x to access some more recent features.

I've already tried all the steps you listed under 'Troubleshooting'. Given that the earlier version was working under Kibana 7, it doesn't look to me like an issue my end, though happy to try anything else you might be able to suggest.

Please let me know if you need any more information.

Many thanks,
Matt

**Comment by fbaligand** [comment]
Hi,

I just tested with last version (8.11.3) and reproduced your issue.
It's quite awful for me, but I realize, that now, I have to fully rebuild my plugin for every Kibana patch version based on exact Kibana code for this version...
This is hard work...
Before, I just had to build it one time for Kibana X.Y, and then just generate a package for each Kibana patch version.

I will do this as soon as possible and say you here when it will be available.

**Comment by fbaligand** [comment]
Hi, I just updated "releases" page with re-build versions for Kibana 8.11.1, 8.11.2 and 8.11.3.
I invite you to download again the package for your Kibana version, install it, and one last important thing: in your browser, you have to fully remove all your cache files.
With Chrome: Ctrl + Shift + Suppr ; and then select "all" cache, not just 1 hour.

**Comment by mcforman** [comment]
Hi,

Thanks so much for looking at this so quickly. Sorry to hear that the Kibana folks have made this more of a hassle for you!

I will try installing again, and noted re: cache – I would always do this anyway.

Matthew

**Comment by fbaligand** [comment]
Tell me if it works nicely 😉

**Comment by fbaligand** [comment]
As I published the fixed packages for Kibana 8.11.1, 8.11.2, and 8.11.3 ; I close this issue. 

You can get the fixed packages here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.5
