### ISSUE TITLE
Enhanced table for new elastic version (8.12) series

### ISSUE THREAD

**Issue by guru00** [fbaligand/kibana-enhanced-table#342]
Hello Team, 

When we can expect the enhanced table feature/package release available for the new elastic version (8.12.1)? Is there any tentative plan for the release? 

Thanks 
Siva

**Comment by fbaligand** [comment]
Well, it is already available here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.14.0

**Comment by guru00** [comment]
Ha! thanks for your quick response!
