### ISSUE TITLE
OpenSearch Dashboards 2.13 release

### ISSUE THREAD

**Issue by msoler8785** [fbaligand/kibana-enhanced-table#346]
There is a new release of OpenSearch Dashboards 2.13.0. Would it be possible to get a new build?

https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.13.0.md

Thank you 🙏

**Comment by fbaligand** [comment]
Wow, you're very up-to-date!
This release is not yet available on GitHub releases!
https://github.com/opensearch-project/OpenSearch-Dashboards/releases

But I will soon test it. And if it works "as is", I will publish an asset for OSD 2.13.0.

**Comment by fbaligand** [comment]
Hi @msoler8785,
I just published asset for OSD 2.13.0:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.14.0/enhanced-table-1.14.0_osd-2.13.0.zip

**Comment by msoler8785** [comment]
Yeah, there was a bug that was patched from OSD 2.12.0 so I need to update again ASAP, Thank you!

**Comment by fbaligand** [comment]
Nice if I helped you ;)
