### ISSUE TITLE
kibana external plugin integration error

### ISSUE THREAD

**Issue by kamalika-B** [fbaligand/kibana-enhanced-table#349]
I am trying to integrate the external plugin (kibana - enhanced - table) and I am getting

error 1: Refused to execute script from 'http://13.126.227.207:5601/fxe/XXXXXXXXXXXX/bundles/plugin/enhancedTable/kibana/enhancedTable.plugin.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

error 2: Failed to load resource: the server responded with a status of 404 (Not Found)

For this error I tired adding csp rules in kibana.yml file and 

i faced this error: kibana is shutting down fatal error reason config validation of [csp] rules definition for this key is missing server crashed with error code 78 

I am using kibana v7.17.6 and plugin version as v13.0

This is happening while I cloned the kibana enhanced table plugin in the kibana/plugin repository

![image](https://github.com/fbaligand/kibana-enhanced-table/assets/161005314/7923c814-cb47-4203-a81d-b11c925fadb1)

**Comment by fbaligand** [comment]
Hi,

If you just want to use the plugin, then you should not clone the github repository, but download and install this package:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.14.0/enhanced-table-1.14.0_7.17.6.zip
To install it, follow the instructions here:
https://github.com/fbaligand/kibana-enhanced-table/?tab=readme-ov-file#install

If you want to develop new features in the plugin, then you must use Kibana from github respository (not a downloaded package), and follow instructions here:
https://github.com/fbaligand/kibana-enhanced-table/?tab=readme-ov-file#development

**Comment by fbaligand** [comment]
Given that question is answered 4 months ago and there is no answer since then, I close the issue.
