### ISSUE TITLE
Kibana enhanced table for 8.16.0 kibana version

### ISSUE THREAD

**Issue by 8susi8** [fbaligand/kibana-enhanced-table#354]
I upgraded ELK from 7.17.x to 8.16.0 and i would like to use the enhanced-table plugin. I tried by modifying the version in kibana.json but it doesn't work. It would be amazing to have the updated plugin for kibana 8.16.0

**Comment by fbaligand** [comment]
Hi, Kibana 8.16 brings breaking changes that requires some code changes in enhanced table plugin. 
That’s why the plugin package for Kibana 8.16 is currently not published. 
By the way, to have a stable version of Kibana, I recommend you to use the last patch version (I mean last 8.15 patch when 8.16.0 is out). 
And enhanced table is available for all Kibana 8.15 patches.

**Comment by fbaligand** [comment]
I have good news for you @8susi8 !
I fix enhanced table plugin's code to  be compatible with Kibana 8.16!

=> So you can now download the package for Kibana 8.16.0 here:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.14.0/enhanced-table-1.14.0_8.16.0.zip
