### ISSUE TITLE
Kibana-enhanced-table support for kibana 7.0

### ISSUE THREAD

**Issue by swathichowdaryg** [fbaligand/kibana-enhanced-table#36]
Thank you so much for this plugin. The plugin is not compatible with the latest version of Kibana 7.0. Please support

**Comment by sivapavi** [comment]
Hi, 

I'm also eagerly looking for this feature in kibana 7.0 major version.  Could you please consider this request as priority one? 

Thanks for the support!

**Comment by fbaligand** [comment]
I'm working on it.
I will notice you here when it will be available.

**Comment by sivapavi** [comment]
@fbaligand - Thanks for the prompt response! 
Will wait to hear the update.

**Comment by synapticiel** [comment]
Thanks @fbaligand for your great job, we really appreciate this plugin

**Comment by qakart** [comment]
thanks a lot, @fbaligand as I am also eagerly waiting for this version

**Comment by fbaligand** [comment]
Hi @qakart,

I’m working on 7.0 compatibility.
But that’s hard, as there are important breaking changes.

**Comment by fbaligand** [comment]
Hi all,

Great news: enhanced-table plugin v1.2.0 is out, with Kibana 7.0 support!
You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.2.0
