### ISSUE TITLE
Plugin version 1.2.0 not showing with Kibana 6.7.1 when creating a custom docker image

### ISSUE THREAD

**Issue by vimitris** [fbaligand/kibana-enhanced-table#37]
Hello,

I am trying to add the plugin version 1.2.0 to my custom kibana docker image version 6.7.1.  My elasticsearch has version 6.7.1 too. The kibana is showing with correct data from the elasticsearch but the plugin is not enabled. I tried 2 different deployments. One within docker and one within a kubernetes cluster.

The following is the dockefile used when trying only running the docker image:

FROM docker.elastic.co/kibana/kibana-oss:6.7.1
ENV PATH /usr/share/kibana/bin:$PATH
ENV ELASTICSEARCH_HOSTS http://es-cluster:9200

RUN kibana-plugin install \
    "https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.7.1.zip"

USER kibana
EXPOSE 5601
CMD ["/usr/local/bin/kibana-docker"]

The creation of docker image says everything is ok:

Step 4/7 : RUN kibana-plugin install     "https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.7.1.zip"
 ---> Running in 01528e11921d
Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.7.1.zip
Transferring 56872 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

Executing:

bash-4.2$ kibana-plugin list
enhanced-table@1.2.0

so the plugin is listed as installed but it does not show anything in dashboard. 

Looking in the logs I cannot see anything related to this plugin:

{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:kibana@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:elasticsearch@6.7.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:console@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:interpreter@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:metrics@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:tile_map@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:timelion@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-05-15T15:19:21Z","tags":["status","plugin:elasticsearch@6.7.1","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}

The same thing is happening while trying in a kubernetes cluster. 

The dockerfile used for kubernetes is:

FROM docker.elastic.co/kibana/kibana-oss:6.7.1
ENV PATH /usr/share/kibana/bin:$PATH
RUN kibana-plugin install \
    "https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.7.1.zip"

It is used to create an image called custom-image:1.0.0. The the deployment yaml file for kubernetes is:

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kibana
  name: kibana
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  template:
    metadata:
      labels:
        service: kibana
    spec:
      containers:
        - name: kibana
          image: custom-image:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 512Mi
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: SERVER_BASEPATH
              value: /logs
          ports:
            - containerPort: 5601
      restartPolicy: Always

**Comment by vimitris** [comment]
![image](https://user-images.githubusercontent.com/50671047/57789005-c3512c80-7740-11e9-93ab-6c54622c6697.png)

**Comment by fbaligand** [comment]
Hi, I just tested to install the plugin on Kibana 6.7, and it worked fine.

Just to be sure: enhanced-table is a dedicated visualization. It does not automatically "enhance" the standard Data Table.
So if you go to Visualize screen, and add a new visualization, you should get this:
![image](https://user-images.githubusercontent.com/3750300/57945006-00502700-78d9-11e9-8ca4-e4b0ec2e4cad.png)

**Comment by vimitris** [comment]
Hi, indeed it worked. I was checking for standard data table. Thanks!

Maybe more documentation would be nice with some working examples for deployment in various kinds (simple, container image, kubernetes etc) and  also for calculations.

**Comment by fbaligand** [comment]
Hi @vimitris 

Happy to see the enhanced-table plugin works for you! :)

Concerning container configuration, your Dockerfile is fine. 
Maybe you could enhance doc plugin by a PR?

Concerning doc calculations, can you detail what you mean?
