### ISSUE TITLE
Using the "in" operator in the calculated columns

### ISSUE THREAD

**Issue by diallo1** [fbaligand/kibana-enhanced-table#38]
I want to use the "in" operator in the calculated columns but this function is not enabled.

![image](https://user-images.githubusercontent.com/12812107/57862095-1803ae80-77f8-11e9-95b2-e479aebf5604.png)

Can you activate this operator, please?

**Comment by fbaligand** [comment]
Hi,

I will try to add this feature in next version. 
That said, waiting this enhancement, you can do this:
(col0 == "TOTO" or col0 == "TITI") ? ...

**Comment by fbaligand** [comment]
After some investigations, I realized that "in" operator is not the feature you expect.
It lets to do this: `col0 in col3`
But not this: `col0 in [0,1,2]`

That's why I close the issue as "won't fix".
