### ISSUE TITLE
Filter buttons does not work with one 'Split Table' bucket, two 'Split Rows' buckets and "Show metrics for every bucket/level" option enabled

### ISSUE THREAD

**Issue by Finu** [fbaligand/kibana-enhanced-table#39]
Kibana 7.0.1
Enchanced table - 1.2.0

First - amazing work :)!

When using default kibana feature of filter on basic table you can click on some value (magnifier icon) and then kibana apply it as a filter. Now icon is still showing when hovering over field but clicking on it does not results in adding this filter. It worked for bucket where I have date histogram - but when I split by term I connot click it

Is this desired state, or can it be somehow re implemented to behave same as in original kibana?
I understand that it would only works on metrics columns.

**Comment by fbaligand** [comment]
I tried to reproduce your issue, but it worked fine.
Can you give all the details about your buckets and metrics, so that I can reproduce it?
Ideally, if you can reproduce the issue with a Kibana sample data set, it would help a lot as I can easily have the same data set.

**Comment by Finu** [comment]
Sory for late response, so I drilled it down a bit - it stops working when:
* I check **Show metrics for every bucket/level**
And have buckets in this order
* **Split Table**
* **Split Rows**

If i use in **Split Rows** Date-histogram I can filter by it. But if I select **Term** then I'm not able to click on it.

**Comment by fbaligand** [comment]
Hi @Finu ,

I manage to reproduce your issue, with "Show metrics for every bucket/level" enabled, one "Split Table" bucket and one "Split Rows" bucket.

That said, if you have only one "Spit Rows" bucket, "Show metrics for every bucket/level" option is useless. If you disable this option, you will get the same table, and Filter buttons will work.

"Show metrics for every bucket/level"  is useful if you have at lease 2 "Split Rows" buckets.
By the way, after tests, if you have no "Split Table" bucket but 2 "Split Rows" buckets, filter buttons work great.

**Comment by Finu** [comment]
I use it with 1x split table 2x split row - where first split row is by date and second is by term. And this by term does not work while by date works.

**Comment by fbaligand** [comment]
OK, thanks for confirmation.
I will try to fix it in next release.

**Comment by fbaligand** [comment]
Hi @Finu,

Kibana enhanced-table plugin v1.3.0 is just released with this bug fixed!

There are also two new features:
- 'Computed Columns' and 'Lines computed filter' formula validation and error notification
- `now()` custom function available for 'Computed Columns' and 'Lines computed filter' formulas (useful to compute duration with a timestamp field: `now() - col['timestamp']`)

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.3.0

**Comment by Finu** [comment]
Thank you very much :).

**Comment by fbaligand** [comment]
Happy to see you enjoy it!
