### ISSUE TITLE
Convert existing datatables to enhanced-tables

### ISSUE THREAD

**Issue by bradvido** [fbaligand/kibana-enhanced-table#4]
We have hundreds of pre-built Kibana datatables, but would like to use these with the new features available in this project.

Is there any way to automatically convert/copy these to the enhanced datatable format?

**Comment by fbaligand** [comment]
Hi @bradvido ,

Well, I just made a test (successful), and it looks quite easy !

Here are the steps : 
- Go to "Management" > "Saved Objects" and "Visualizations" tab
- for each "data table" : 
  - click on it, and go to "visState" textarea
  - replace `"type": "table"` by `"type": "enhanced-table"`
  - click on "Save visualization Object" button

**Comment by bradvido** [comment]
OK, great. I'll backup my kibana index and run a script to update all these. Thanks!

**Comment by fbaligand** [comment]
Nice !

**Comment by fbaligand** [comment]
Question is answered so I close the issue.
