### ISSUE TITLE
Release for Kibana 6.8

### ISSUE THREAD

**Issue by ch-bas** [fbaligand/kibana-enhanced-table#40]
Hi @fbaligand ,
as the version 6.8 of Kibana was released, is there any plan to make a new release of the kibana-enhanced-table plugin?  
Thanks in advance!

**Comment by fbaligand** [comment]
Hi @ch-bas,

I just published enhanced-table plugin v1.2.0 for Kibana 6.8.0 and Kibana 7.1.0 here : 
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.8.0.zip
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_7.1.0.zip
