### ISSUE TITLE
Q: Is there a way to access search results (hits)?

### ISSUE THREAD

**Issue by bwalsh** [fbaligand/kibana-enhanced-table#41]
Thanks for the plugin.  Great work.

I'd like to leverage formatting and calculations using the  documents returned from the underlying search as opposed to creating aggregation columns and derived columns.  

Syntax might be doc['json.path'].  

Current alternative is to use a 'saved search' on the dashboard, but columns need to be calculated and formatted on the backend and stored in the index.  Additionally, saved search does not allow export as a CSV

**Comment by fbaligand** [comment]
Hi,

Well, in enhanced table, when I want to list documents, and not aggregations, I make a first terms aggregation that is unique, for example, based on _id field. Then I do a terms sub aggregation with size "1" for each field I want to display. Finally, I hide first column (id)

Concerning standard saved search, you can do a CSV export.
If you Kibana 6.3 or later, you go to Discover screen, open your saved search, then click on "Share" button, "CSV Reports" link" and "Generate CSV" button.
That said, it's not perfect, as you can't generate CSV in Dashboard view.
Concerning computed and formatted columns, you can add scripted fields in Kibana, it lets you add new computed columns based on document fields, and format the result using a standard Kibana formatter. Then, you can reference these scripted fields in Saved Searches. By the way, the name of scripted field (so the column name in Saved Search) is free: you can use space chars or any other special chars.

**Comment by bwalsh** [comment]
> Finally, I hide first column (id)

Perfect. That works like a charm.  Thanks very much for the quick answer.

**Comment by fbaligand** [comment]
Nice!
Happy to help :)
