### ISSUE TITLE
Lines computed filter does not work

### ISSUE THREAD

**Issue by tarasen-mv** [fbaligand/kibana-enhanced-table#42]
Kibana 6.2.4
Enchanced table - 1.2.0

Good morning, your plugin is great, but unfortunately, i've found some strange behavior of lines computed filter.
When i put some expr-eval expression in the input, kibana don't react at all, the update visualization button (grey triangle on the blue square) doesn't became active.  I tried different indexes and different buckets, nothing helped.

**Comment by fbaligand** [comment]
Hi @tarasen-mv 

Thanks for the issue.
I will study the bug and try to fix it.

**Comment by fbaligand** [comment]
Hi @tarasen-mv,

I found the issue and fixed it.
It will be part of the next plugin release.

**Comment by fbaligand** [comment]
Hi @tarasen-mv,
 
Kibana enhanced-table plugin v1.3.0 is just released with this bug fixed!

There are also two new features:
- 'Computed Columns' and 'Lines computed filter' formula validation and error notification
- `now()` custom function available for 'Computed Columns' and 'Lines computed filter' formulas (useful to compute duration with a timestamp field: `now() - col['timestamp']`)

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.3.0
