### ISSUE TITLE
The plugin is not showing up

### ISSUE THREAD

**Issue by henriquelssantiago** [fbaligand/kibana-enhanced-table#44]
I installed the plugin but it's not appearing in the kibana.

I'll put some screenshots:

_

> λ kibana-plugin.bat list
> datasweet_formula@2.2.1
> enhanced-table@1.3.0
_

We can see that the plugin was installed, but the options is not there.

Obs:
I'm utilizing:

- Windows 10
- Elasticsearch 7.1.1
- Kibana 7.1.1
- Google chrome

![image](https://user-images.githubusercontent.com/10300921/59634978-5c9ba600-9126-11e9-85e8-4765e8d8fc74.png)

**Comment by fbaligand** [comment]
Hi,

Enhanced-table is a visualization apart, not an “data table” enhancement. 
So, When you add a new visualization, please choose “enhanced table”, and not “data table”.

**Comment by henriquelssantiago** [comment]
Oh, I'm sorry! 
I'm getting used to the nomenclature of kibana.
I tested here and works fine.
Thanks!!

**Comment by fbaligand** [comment]
Great!
