### ISSUE TITLE
Column rename

### ISSUE THREAD

**Issue by IlianYotov** [fbaligand/kibana-enhanced-table#45]
Hello

I have a table whose columns are date ranges. Is there an option to rename columns?? For example I want to display *Today* instead of *Jun 10, 2019 @ 03:00:00.000 to Jun 20, 2019 @ 13:38:55.899*

Regards

**Comment by fbaligand** [comment]
Hi @IlianYotov ,

Well, that's not very easy, but you can do something like that:
- in "Data" tab, add a metric "Min" based on your timestamp field (the field that you use in your Date Range or Date Histogram bucket)
- then in "Options" tab, add this computed column formula: `(floor(now() / 1000 / 60 / 60 / 24) * 1000 * 60 * 60 * 24) < col1 ? "Today" : col0`
- in my previous formula, col0 is the "date ranges" column and col1 is the "min timestamp" column.
- use a "String" format for the computed column
- in "Hidden columns" setting, hide the "min timestamp" column.

The main idea is that if the minimum date in the date range is > to "today at 00:00:00,000", then I display "Today", else I display the date range as it is.

I hope it solves your need. Tell me :)

**Comment by IlianYotov** [comment]
I had implemented another solution but it is also a little bit tricky :) 
I cloned Date range aggregation to add an option for bucket key and then in format function I use the bucket key.

**Comment by fbaligand** [comment]
So you developed a Kibana plugin?

**Comment by IlianYotov** [comment]
Not a plugin, I just get the original date_range from kibana and include it into a local version of enhanced table. I added only one new field in date_range template with id *key* and then use this key as column name. 

It's a tricky solution but I can easily name date range buckets as Today, Yesteday, This month etc. 
I'm looking for a better solution to make a PR

**Comment by fbaligand** [comment]
OK, thanks for the feedback.
And if you have a nice and generic implementation, I would be happy to merge it :)
