### ISSUE TITLE
Issue installing plugin on Kibana 7.1.1

### ISSUE THREAD

**Issue by bhavikshah627** [fbaligand/kibana-enhanced-table#46]
Hi, I've just installed the plugin with Kibana 7.1.1 and Elasticsearch 7.1.0 and get the following issue:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10790195/60052602-b27ec980-96a3-11e9-9671-3e0cccc273ce.png">

The only thing I changed was the path in the uiExports field to "enhanced-table/public/enhanced-table-vis"

**Comment by fbaligand** [comment]
Well, why did you change "uiExports" field?
Normally, you don't need to change anything to install the plugin.

Did you try to install the plugin without changing anything?

**Comment by bhavikshah627** [comment]
I tried it again without changing anything and ran kibana-install, and the same issue occurred. Here is my file structure if it helps at all. 

<img width="995" alt="image" src="https://user-images.githubusercontent.com/10790195/60056701-d6e0a300-96af-11e9-925d-4425d7682377.png">

**Comment by fbaligand** [comment]
Thanks for the details, I will try to reproduce the issue.

**Comment by fbaligand** [comment]
Hi,

I just tried to reproduce the issue, with exactly the same Kibana version and plugin version (enhanced-table-1.3.0_7.1.1.zip), and it works fine for me, without changing anything in zip file available on github.

To be sure, can you delete "optimize" and "plugins" folder, and then re-install official zip file using "kibana-plugin install file:///"?

**Comment by fbaligand** [comment]
By the way, normally, your Elasticsearch version should be equals to or greater than Kibana version.

**Comment by bhavikshah627** [comment]
Hi,

Thanks for your help! Deleting the optimize folder and running again
worked.

**Comment by fbaligand** [comment]
Nice to see it solves your problem!
Hope you will enjoy the plugin!
