### ISSUE TITLE
filtering by value feature is filtering by wrong values

### ISSUE THREAD

**Issue by schafer21mcm** [fbaligand/kibana-enhanced-table#47]
Hi there, great plugin! I am running into an issue though where I have a table where I am using the split row option on a term. If I click on a term in the first page of results, the term is filtered correctly. However if I navigate to any page other than page 1 and click on a term to filter, the wrong term is used in the filter.

For example, say I have a table with 50 terms, we'll call it term[1-50] and am showing 10 terms per page. Page 1 works fine, but If I click on page 4 and then click on the magnifying glass on term43, the term filtered by may be something completely different, like term35. Any idea what's going on here?

Thanks,

**Comment by fbaligand** [comment]
Can you indicate which Kibana version you use and which enhanced-table plugin version you use ?

**Comment by schafer21mcm** [comment]
we are on Kibana v7.1.0 and enhanced table v1.3.0

**Comment by fbaligand** [comment]
Hi @schafer21mcm,

I managed to reproduce the issue. I think I see where is the bug.
I will provide soon a bug fix.

**Comment by schafer21mcm** [comment]
Thanks for the quick response to this @fbaligand!

**Comment by fbaligand** [comment]
I found the bug and fixed it. 
I will just add Kibana 7.2 support and then publish a new release with the fix.

**Comment by schafer21mcm** [comment]
Awesome, thanks so much!

**Comment by fbaligand** [comment]
Hi @schafer21mcm ,

As support for Kibana 7.2 is quite complex to do, I finally published a bug fix release 1.3.1 with just your fix:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.3.1

You can get it an enjoy :)
