### ISSUE TITLE
Adding Item Url option 

### ISSUE THREAD

**Issue by piellick** [fbaligand/kibana-enhanced-table#49]
Hi, 
great job for you plugin !

It will be perfect i we will have the ability to create an item url on the table.  Have you plan to add this functionnality ?

**Comment by fbaligand** [comment]
Can you precise your need please?

Currently, in a computed column, you can define a template, and in template, you can set a url link.
For example : 
`<a href="http://some-host/my-app?myParam={{value}}">{{value}}</a>`

**Comment by fbaligand** [comment]
No answer for more than 1 month ago, so I close the issue.
