### ISSUE TITLE
Support for Kibana 6.3.0

### ISSUE THREAD

**Issue by keeshqs** [fbaligand/kibana-enhanced-table#5]
Can we use the 6.2.x version in Kibana 6.3.0?
Iv'e tried changing the version from package.json but there were some errors during the installation.
Kindly advise.

Thank you.

**Comment by fbaligand** [comment]
Hi @keeshqs

I already tried current version on kibana 6.3.0, and unfortunately, it doesn’t work.

I’m working on a new release with new features that will be out this or next week. 

Then, I will work on making  enhanced table compatible with Kibana 6.3.

**Comment by keeshqs** [comment]
Hi @fbaligand 

Thank you for your response and for sharing the plugin! We could do a lot with our data with this plugin!
I think it'd be long before the support for kibana 6.3.0, so in the meantime, we will just downgrade to 6.2.4 and will check regularly for any new releases.

Best Regards.

**Comment by fbaligand** [comment]
When I’ll release enhanced table for kibana 6.3, I will add a comment here to announce the release so that you’re notified by mail.

**Comment by bradvido** [comment]
Awesome, eagerly awaiting the 6.3 release

**Comment by fbaligand** [comment]
Hi,

For info, I just released enhanced-table v0.7.0, which adds several new features !
Here's the features list : 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.7.0

So right now, I'll start to make enhanced-table compatible with kibana 6.3.0 !

**Comment by fbaligand** [comment]
Hi guys,

Breaking news : I just released enhanced-table for Kibana 6.3.0 !

You can download it here : 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.7.1
