### ISSUE TITLE
Add Kibana 7.2.0 support

### ISSUE THREAD

**Issue by carlosgblos** [fbaligand/kibana-enhanced-table#50]
Hi, I know you don't have yet a version 7.2.0 for this awesome plugin. 
So, I tried to use the 7.1.1, just changing the package version, and the below error happened.

[visualization] > Cannot read property 'aggConfigs' of undefined

I believe we have some incompatibility. :(

Do you know any solution, or I just wait for the new plugin version ?

**Comment by fbaligand** [comment]
Hi,
If I don’t published yet a 7.2.0 release, it is for a reason :)
So yes, there are some breaking changes in Kibana 7.2.0, and there some work to do to make enhanced table plugin compatible. 
I started to work on it. I solved the first issue you get. Now, I have another to fix. 
When I will publish it, I will notify you in this issue.

**Comment by carlosgblos** [comment]
Thanks for your prompt answer, and for your effort. That's really an awesome plugin.
Anything you need, please let me know.

**Comment by fbaligand** [comment]
Happy to see you enjoy the plugin!

**Comment by shivam2202** [comment]
Thanks for the great plugin. We are also waiting for 7.2 support version.

**Comment by fbaligand** [comment]
Hi,

Thanks for your interest for enhanced-table plugin  :)
I plan to publish a new plugin release compatible with Kibana 7.2 this or next week.

**Comment by fbaligand** [comment]
Good news: I just released enhanced-table v1.4.1, with support for Kibana 7.2!
Hope you will enjoy it :)
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.4.1

**Comment by carlosgblos** [comment]
Thanks so much. :) I'm going to install today!

**Comment by fbaligand** [comment]
Great! Enjoy :)
