### ISSUE TITLE
Feature Request: Hide Columns by Name along with Index Numbers

### ISSUE THREAD

**Issue by asthinasthi** [fbaligand/kibana-enhanced-table#51]

**Comment by fbaligand** [comment]
Nice idea

**Comment by fbaligand** [comment]
Hi @asthinasthi, 

I'm pleased to announce you that this new feature is available in version 1.5.0, just released!

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.5.0
