### ISSUE TITLE
Referencing Col By Label error

### ISSUE THREAD

**Issue by asthinasthi** [fbaligand/kibana-enhanced-table#52]
I have a columns 

| **Count** | **Value** |
| ------ | ------- |
| 100 | 5 |

When I try to compute col['Count'] / col['Value'] I get this error:

`In computed column 'col['Count'] / col['Value']', column with label 'Count'] / col['Value' does not exist`

**Comment by fbaligand** [comment]
Thanks for the issue. 
It’s clearly a bug and I guess how to fix it.

**Comment by fbaligand** [comment]
Good news: the issue is fixed and released!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.4.1
