### ISSUE TITLE
Cannot find enchanced-table from kibanaurl/status#?_g=() after install enchanced-table 

### ISSUE THREAD

**Issue by chunanlee** [fbaligand/kibana-enhanced-table#55]
Dear Sir,
I experience an issue that enhanced-table does nor work properly on my Kibana 7.2
My Kibana's version is 7.2 and I download enhanced-table-1.4.2_7.2.0.zip and installed it following your instruction as follows:
bin/kibana-plugin install file:///path/to/enhanced-table-1.4.2_7.2.0.zip
After installation it, I cannot see it from Kibana->New Visualization->Data Table->choose a source->Options.
But I check the plugin status of Kibana from the server terminal. It looks okay showed as below.
![image](https://user-images.githubusercontent.com/13114025/62854911-4cb5d200-bd23-11e9-87af-6f8e42d21874.png)
Can you let me know what's wrong with my installation procedures?

Thank you very much.

**Comment by fbaligand** [comment]
Hi, first, enhanced table is a dedicated visualization. So when you click on “new visualization”, choose “Enhanced Table”. 
If you don’t see it in the list, restart Kibana and refresh your browser. 
If it’s still not enough, check that KIBANA_HOME/plugins contains enhanced-table/package.json, else reinstall plugin and restart Kibana. 
If plugin is present in plugins folder, remove “KIBANA_HOME/optimized” folder and restart Kibana and refresh your browser.

**Comment by chunanlee** [comment]
Dear Sir,
Thank you very much for your help. The problem is solved after reinstalling the plugin.

**Comment by fbaligand** [comment]
Nice!
Thanks for the feedback!
