### ISSUE TITLE
coloring questions

### ISSUE THREAD

**Issue by 0asp0** [fbaligand/kibana-enhanced-table#56]
Hi,

can I also change the background color of a cell?
Is it possible to change color / background color for a complete line, including the "non-computed columns?"
I have a column "status". If it fails, I would show complete line with red background.
If I "clone" all columns as computed column for coloring and hide the original ones, I lose the possibility to filter by clicking the cell.

Thanks, Andreas

**Comment by fbaligand** [comment]
Hi Andreas,

- yes you can change cell background color:
ˋ<div style="background-color: {{col0}}">{{value}}</div>`
- no, you cannot actually change row background color. 
- to set a beautiful row alert, personally, I add a computed column with a font awesome  icon:
https://fontawesome.com/icons?d=gallery&s=duotone

**Comment by fbaligand** [comment]
Coloring the whole line is an interesting feature. Can you open a « feature request » issue for that ?

**Comment by 0asp0** [comment]
feature request has been opened: https://github.com/fbaligand/kibana-enhanced-table/issues/58

Is it also possible to color the whole cell background and not just the background color?

**Comment by fbaligand** [comment]
Currently, this is not possible to change the cell style. 
I saw that you also request it in your feature request. 
Thanks to have opened this feature request!

**Comment by fbaligand** [comment]
I close the issue as question is answered
