### ISSUE TITLE
only first span format is used

### ISSUE THREAD

**Issue by 0asp0** [fbaligand/kibana-enhanced-table#57]
Hi,

it is possible to assign a single format via span as template:

```
<span style="color: {{col4}}">{{value}}</span> 
<span style="font-weight: bold">{{value}}</span>
```

Both are working like charm if I use only one of them.
But when I combine them to 
`<span style="color: {{col4}}" style="font-weight: bold">{{value}}</span> `

only the first style will be processed.

I would like to change foreground, background and status of bold / normal at once

**Comment by fbaligand** [comment]
Well, I’m not sure to understand your question. 
But it seems that some fragments of your example are not displayed. 
Can you put your sample between back quotes?

**Comment by 0asp0** [comment]
sorry, forgot to put into code tags. Original post is updated now.

**Comment by fbaligand** [comment]
Ok, thanks for the update. 
This is just a html/css syntax problem. 
The right syntax is :
`<span style="color: {{col4}}; font-weight: bold">{{value}}</span>`

**Comment by fbaligand** [comment]
No updates for months, and question is answered. 
So I close the issue.
