### ISSUE TITLE
Feature-Request: color the whole line

### ISSUE THREAD

**Issue by 0asp0** [fbaligand/kibana-enhanced-table#58]
Hi,

currently it is possible to insert coloring of text or background via "\<span\>" tags.

I would like to have the possibility to set the background cell color for a whole line at once. It should be applied to the computed columns **and** to the "normal" columns at once.

UseCase:
I use kibana to show metrics, which are showing following fields for example:

- kubernetes Node
- namespace
- number of ready pods
- number of scheduled pods

Currently if the number of ready pods is smaller than the number of scheduled pods (target) I compute a status and set background color to green or red.

It would be really nice if I could color backround of all columns (computed and standard cols) by such condition. 
Being able to color background of the whole cell and not just the text background would also be really nice.

**Comment by fbaligand** [comment]
@piellick
If you’re working on this feature, don’t hesitate to submit a PR!
I would be happy to merge it!

**Comment by fbaligand** [comment]
Sorry, I misunderstood your previous comment 😊
But for sure, this feature would be a great enhancement for numerous users, I think.

**Comment by mordekasg** [comment]
@piellick @0asp0 
So you would like to add templates support for:
- [ ] stock columns/metrics
- [ ] table cell (not metric value)
- [ ] table row

**Comment by fbaligand** [comment]
Good news: enhanced table v1.10.0 is out with both 'Rows computed CSS' feature and 'Cell computed CSS' computed column feature!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0
