### ISSUE TITLE
I am able to Transpose but unable to configure column for row heading

### ISSUE THREAD

**Issue by shai2017** [fbaligand/kibana-enhanced-table#6]
hi I was trying to transpose below table
Currency,TradeCount,
USD,20
EUR,12
GBP,15

to 
USD,EUR,GBP
20,12,15

But I am unable to transpose like below:
Currency,USD,EUR,GBP
TradeCount,20,12,15

Is this feature exist in current release of this plugin?

**Comment by fbaligand** [comment]
Hi @shai2017,

First, I guess you use 'Split Cols' feature to do this ?
Then, I'm sorry, this is not possible in current release of this plugin.
