### ISSUE TITLE
[ES 7.3.1] Error: Skipping non-plugin directory at /usr/share/kibana/plugins/enhanced-table

### ISSUE THREAD

**Issue by magnuslarsen** [fbaligand/kibana-enhanced-table#60]
Hey Fabien,

Thanks for the plugin.
I seem to have trouble updating the plugin from ES 7.3.0 to ES 7.3.1 (with your plugin version staying at 1.4.3):

```
# Remove previous installation
/usr/share/kibana/bin/kibana-plugin remove enhanced-table --allow-root

# Install the new version
/usr/share/kibana/bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip --allow-root

# Restart Kibana to get the new plugin
systemctl restart kibana
```
Everything good thus far.

`package.json` gives me this:
```
{
  "name": "enhanced-table",
  "version": "1.4.3",
  "description": "This visualization plugin is like a Data Table, but with enhanced features like computed columns and filter bar",
  "main": "index.js",
  "kibana": {
    "version": "7.3.1"
  },
  "dependencies": {
    "expr-eval": "^1.2.2"
  },
  "build": {
    "git": {
      "count": "111",
      "sha": "79df487",
      "date": "Thu, 8 Aug 2019 21:37:31 +0200"
    },
    "date": "Thu Aug 08 2019 22:03:20 GMT+0200 (GMT+02:00)"
  }
}
```

In the Kibana log file however, I get this message: `Skipping non-plugin directory at /usr/share/kibana/plugins/enhanced-table`

Can you help?
Thanks

**Comment by fbaligand** [comment]
This is weird...

I invite you to do these actions:
- stop Kibana
- remove $KIBANA_HOME/optimize folder
- start Kibana

**Comment by magnuslarsen** [comment]
No dice sorry. It still comes with the same error message:
```
{"type":"log","@timestamp":"2019-08-26T12:59:38Z","tags":["plugin","warning"],"pid":24683,"path":"/usr/share/kibana/plugins/enhanced-table","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/enhanced-table"}
```

**Comment by fbaligand** [comment]
Did you try to launch Kibana UI in your browser and check that plugin is available?
![image](https://user-images.githubusercontent.com/3750300/63694340-80f6bb80-c816-11e9-83e0-fac72901d259.png)

**Comment by magnuslarsen** [comment]
Yep, I get this:
![image](https://user-images.githubusercontent.com/7879747/63742945-12534580-c88a-11e9-8a84-924576ef6134.png)
...just like a new upgrade without the plugin :(

**Comment by magnuslarsen** [comment]
I've just tried to purge my entire Kibana installation:
```
apt purge kibana
```
..leaving only my raw kibana data folder back (`/var/lib/kibana/`). Reinstalled and reconfigured, and then installed the plugin. Still no dice.

```
{"type":"log","@timestamp":"2019-08-27T05:25:40Z","tags":["info","plugins-system"],"pid":24465,"message":"Starting [1] plugins: [translations]"}
```

**Comment by fbaligand** [comment]
Very strange...

Could you :
- stop Kibana 
- remove optimize and plugins/enhanced-table folders
- install enhanced-table plugin 
- start Kibana

**Comment by magnuslarsen** [comment]
Hey Fabien,

I figured out something. I switched to the local `kibana` user (using `su kibana -s /bin/bash`), and tried to install the plugin, and it came with this "new" (well uncaught) error:
```
kibana@kibana1:/usr/share/kibana$ bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip
Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip
Transferring 52125 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "EACCES: permission denied, open '/usr/share/kibana/plugins/.plugin.installing/package.json'"
```
That file doesn't exists at all, so I tried to create that file..
```
kibana@kibana1:/usr/share/kibana$ mkdir /usr/share/kibana/plugins/.plugin.installing/
kibana@kibana1:/usr/share/kibana$ touch /usr/share/kibana/plugins/.plugin.installing/package.json
```
And re-ran the install:
```
kibana@kibana1:/usr/share/kibana$ bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip
Transferring 52125 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "EACCES: permission denied, open '/usr/share/kibana/plugins/.plugin.installing/package.json'"
```

The `kibana` user has rwx (775) all the way through `/usr/share/kibana/plugins/` and the `optimize` folder.

**Comment by magnuslarsen** [comment]
Create the `/usr/share/kibana/plugins/enhanced-table` folder manually, and then installing the plugin again, gives the "plugin already installed" error. HOWEVER, it leaves the `/usr/share/kibana/plugins/.plugin.installing/` folder. Look at these permessions:
```
root@kibana1.clm-test.jppol.net:~# ls -alt /usr/share/kibana/plugins/.plugin.installing/
total 12
drwxrwxr-x 4 kibana kibana   76 Aug 27 08:44 .
drwxrwxr-x 4 kibana kibana 4096 Aug 27 08:44 public
-----w---- 1 kibana kibana  490 Aug 27 08:44 package.json
-----w---- 1 kibana kibana  479 Aug 27 08:44 index.js
drwxrwxr-x 3 kibana kibana   23 Aug 27 08:44 node_modules
drwxrwxr-x 4 kibana kibana   54 Aug 27 08:44 ..
```

There is only write access to `package.json` and `index.js` - are you setting those permissions? Or how are they set? 

Thanks for the help Fabien.

**Comment by fbaligand** [comment]
Well, here it is clearly a Linux user permission problem. 
You can install the plugin with whatever user who have write access to plugins folder. 
Then, make sure that user who runs Kibana has read access to whole Kibana folder, including all enhanced-table plugin folders and files.

**Comment by magnuslarsen** [comment]
Hey @fbaligand,
Indeed it is.

Doing it this way works:
```
# Install
kibana@kibana1:/usr/share/kibana$ bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip

# Correct permissions
root@kibana1:/usr/share/kibana# chown kibana:kibana plugins/ -R
root@kibana1:/usr/share/kibana# chmod 755 plugins/ -R

# Restart Kibana
root@kibana1:/# systemctl restart kibana
```

HOWEVER, I tried to download `https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.0.zip` (for ES 7.3.0), and it gives these DIFFERENT permissions, which work for the Kibana users, without the above workaround:
```
# Create folder to keep the .plugin.installing folder
kibana@kibana2:/usr/share/kibana$ mkdir plugins/enhanced-table

# Download previous release
kibana@kibana2:/usr/share/kibana$ bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.0.zip

# Get permissions
kibana@kibana2:/usr/share/kibana$ ls -alt plugins/.plugin.installing/
total 12
drwxrwxr-x 4 kibana kibana   76 Aug 27 13:25 .
drwxrwxr-x 4 kibana kibana 4096 Aug 27 13:25 public
drwxrwxr-x 3 kibana kibana   23 Aug 27 13:25 node_modules
-rw-rw-r-- 1 kibana kibana  490 Aug 27 13:25 package.json
-rw-rw-r-- 1 kibana kibana  479 Aug 27 13:25 index.js
drwxrwxr-x 4 kibana kibana   54 Aug 27 13:25 ..
```

I think there is a permission problem in the `7.3.1` release, since it works with the previous release.

**Comment by fbaligand** [comment]
Thanks for your feedback. 
First, happy to see it finally works. 
Then, indeed, package for Kibana 7.3.1 has been packaged using a different way from Kibana 7.3.0. It is probably the reason of the difference. 
I will try to fix it.

**Comment by fbaligand** [comment]
Hi @magnuslarsen ,

I just packaged and published a new package for Kibana  :
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.1.zip

Could you try to install it and tell me if works fine without workaround?

**Comment by magnuslarsen** [comment]
Hey @fbaligand,

Absolutely, and it works! 

Thanks for the prompt help and effort. And thanks for the plugin :)

**Comment by fbaligand** [comment]
Thanks for your feedback!

And happy to see that you appreciate the plugin :)

**Comment by magnuslarsen** [comment]
Hey @fbaligand 

I tried to download the new package this morning on my production system, and it seems that the `node_modules` and `public` folders are completely empty, causing the plugin to crash.

I tried to download and open the ZIP file in my browser, and indeed, that is empty too.

**Comment by fbaligand** [comment]
Very sad to hear that. 
Sorry for this partial package, I will fix it today.

**Comment by fbaligand** [comment]
Hi,

I just published 7.3.1 package.
This time, I use exactly the same way than for 7.3.0 package.
It should work as expected.

Sorry for this issue...

**Comment by magnuslarsen** [comment]
No problem!

Let me know if you want to test the new deployment system in the future :+1: - I update our test cluster as soon as your plugin is released for the new Elastic version, so it shouldn't be a problem :)

Also i can confirm that it works completely now!

**Comment by fbaligand** [comment]
Thanks for your help!
Community help is always much appreciated!

If you didn’t do it, you can subscribe to new releases in the github repository. 
Like this, you are notified by mail each time a new release is published. 
That said, if I published a new package for an existing release, you shouldn’t be notified. 

And so, if you see a bug on a fresh new release, don’t hesitate to open an issue!
