### ISSUE TITLE
Table goes completely blank during refresh

### ISSUE THREAD

**Issue by chammel4** [fbaligand/kibana-enhanced-table#61]
This plugin has all the features I want, but I need to update the data every 1-3 seconds, and it currently goes blank on every refresh, making it completely useless to me in practice.

Please fix this!

**Comment by fbaligand** [comment]
Can you give me some information:
- which Kibana version do you use?
- which plugin version do you use?
-,when you say “refresh every 1-3s”, you mean that you activate auto refresh on your dashboard? Or do you cluck Kibana refresh button? Or browser refresh button?
- when you say “blank”, you mean that whole page is blank? Only visualization? Real blank screen or empty table?
- do you have some error logged in your browser console?

Thanks 
Fabien

**Comment by chammel4** [comment]
Hi Fabien,

I'm currently using Kibana 7.2.0, plugin version 1.4.2

When I say refresh, I mean activating auto-refresh.
"Blank" == the visualization is blank.  Table completely disappears, then is redrawn (it's shown with a duty cycle of perhaps 70-80% when auto-refreshing every second

Attached is an error that's being thrown.

[kibana-enhanced-table_error.txt](https://github.com/fbaligand/kibana-enhanced-table/files/3557592/kibana-enhanced-table_error.txt)

**Comment by chammel4** [comment]
I just tested a few tweaks, and I'm not sure what is causing that error, but I don't believe it has anything to do with this plugin

**Comment by fbaligand** [comment]
Thanks for the details. 
If I understand well, when “1s” auto-refresh is launched, table disappears some time and finally is redrawn, right?
So you have some blink effect?

**Comment by chammel4** [comment]
Yes, that's correct.

**Comment by fbaligand** [comment]
Ok. 
Thanks for your confirmation. 
To me, this is because of data loading from elasticsearch. 
So I close this issue as I cannot fix that.

**Comment by chammel4** [comment]
it seems that you should be able to load the data from elasticsearch proir to calling redraw, if that isn't already happening?

**Comment by fbaligand** [comment]
You’re right. 
I was doing so in the past. 
But to keep “total” variable, I had to change that. “total” variable now requires to load elasticsearch data at redraw phase. 
The only way to not do that is to remove “total” variable access. 
It would be a breaking change.
