### ISSUE TITLE
unable to list all duplicate values

### ISSUE THREAD

**Issue by iburahim786** [fbaligand/kibana-enhanced-table#63]
Suppose i have two different files (testcase, title, buildnumber, result) but only difference is build number for each unique row, All other column remaining same(But i am not including the build number in the table instead i was mentioning under separate drop down filter). Now some of the data might have same for both file. In that case how can list all values (i.e duplicate values)

file 1:
tc tit build  result
01 a  8.8.01  pass
02 b  8.8.01  fail

file 2:
tc tit build  result
01 a  8.8.02  pass
02 b  8.8.02  fail

when i choos 8.8.01 and 02, table listing one value. How we can add the duplicate values

**Comment by fbaligand** [comment]
Not sure to understand your need.
Given your example, what table data do you expect in enhanced table? I mean the exact columns and rows you wish.

**Comment by fbaligand** [comment]
No updates for months. 
So I close the issue. 
Don’t hesitate to re-open issue and bring requested details so that I can understand and answer the issue.
