### ISSUE TITLE
Is any possibility to add custom column and comments based on the PASS/FAILED status manually ?

### ISSUE THREAD

**Issue by iburahim786** [fbaligand/kibana-enhanced-table#64]
Its not an issue, Question and Enhancement.
I have the table which has automation results. I just want to update the comments based on the results. Based on the Coumn updates, can possible to create visualization ?

**Comment by fbaligand** [comment]
If you have a column with PASS/FAILED value, you can create a computed column to display a custom comment, with this formula:
`col['Status'] == "PASS" ? "Here is a positive comment" : "Here is a negative comment"`

**Comment by fbaligand** [comment]
No updates for months, and question is answered. 
So I close the issue.
