### ISSUE TITLE
Workspace Dark Theme Support

### ISSUE THREAD

**Issue by csurett** [fbaligand/kibana-enhanced-table#66]
Currently highlighting in the enhanced table does not work when using a dark themed workspace. The colors and visibility when hovering over an item is unreadable.

**Comment by fbaligand** [comment]
Hi,

Could you provide some screenshot showing the wrong behavior?
Have you tried to do the same table with standard “Data Table”? Does it render well? Or same than “Enhanced Table”?

**Comment by fbaligand** [comment]
Hi @csurett,

I'm pleased to announce you that this bug is fixed in version 1.5.0, just released!

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.5.0
