### ISSUE TITLE
HTML Escaping in Computed Columns

### ISSUE THREAD

**Issue by ranko6** [fbaligand/kibana-enhanced-table#67]
Hello,

I am trying to do a drill-down using links.
And "Computed Columns" with enabled templates allow me to do this on a higher level than modifying Kibana Index Pattern fields.

Though I have one problem with computed columns, it doesn't seem to do HTML-escaping.

For example, let's say that I have a value "Candie+Land" which I want to put into a filter with an URL.
Steps to reproduce:
1. Create new visualization and select "Enhanced Table".
2. Leave everything as is (a simple count is enough for demo)
3. Click on "Options"
4. Click "Add computed column"
5. In "Formula" write `"Candie+Land"` (with quotation marks)
6. Set "Format" to "String"
7. Click on "Apply template"
8. Replace "<dashboard_id>" with your dashboard id `<a href="#/dashboard/<dashboard_id>?_a=(filters:!((meta:(key:testKey,params:(query:'{{value}}'),type:phrase,value:'{{value}})'),query:(match:(testKey:(query:'{{value}}',type:phrase))))))">{{value}}</a>`
9. Paste it into a "Template"
10. Press the "Run" button (Apply changes)".
11. Click on the new link

What I expect to get is a filter:
`testKey: Candie+Land`

What I get is a dashboard with filter:
`testKey: Candie Land`
and, logically, that filter returns no results.

If I use Kibana Index Pattern to set this field as an "Url", it HTML-escapes all the values and I get the correct value.
Problem with that approach is that I am trying to use more than one value/filter, so Kibana Index Pattern is a bit limiting in that case.

When trying to find a way to HTML-escape it in a Computed Columns (Handlebars), on Handlebars web page I found that:
> Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{.

Though, from what I have seen, regardless if I use double or triple slash, template behaves like I am always using triple slash.

Is there a way to HTML escape a string in Computed Columns?

Kibana version: 7.3.2
Plugin version: 1.5.0

Kind regards,
Ranko

**Comment by fbaligand** [comment]
Hi,

I made some tests, and:
- `{{value}}` will do HTML escaping (ex: replace `<` by `&lt;`)
- `{{{value}}}` will copy exactly value as is
- but actually, handlebars does not provide **URL** escaping :(
- and you need URL escaping (not HTML escaping).

So to answer your need, an enhancement is required:
- either add "encodeURIComponent" method available in computed formula
- either add a "encodeURIComponent" method available in template, so that you  can do `{{encodeURI value}}` in your template.

**Comment by ranko6** [comment]
Thank you for the answer and suggestion :)

In this case, both seem to be the best way.

- Template enhancement because I use more than one column value in some cases and computed formula would affect only one column
- Computed formula enhancement because, in the example above, variable is used 4 times. Three of it needs URI encoding. So, with only template enhancement, the method would be called three times while with computed formula enhancement once.

**Comment by fbaligand** [comment]
In next release, I plan to add a `urlEncode` function, both available in computed column and template.

**Comment by fbaligand** [comment]
enhanced-table v1.6.0 is out! With new function `encodeURIComponent`, available in computed column formulas and templates!
You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.6.0
