### ISSUE TITLE
Unknown uiExport types: styleSheetPaths from enhanced-table

### ISSUE THREAD

**Issue by ahkumar** [fbaligand/kibana-enhanced-table#68]
I get the following error upon trying to install this plugin:

I am using version 6.4.1 for kibana and the rest. Does it mean I am missing some packages? 

Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCachefalse --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:3188) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL Error: Unknown uiExport types: styleSheetPaths from enhanced-table
    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:19:9)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)
    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)
    at <anonymous>

Thanks,
Amit

**Comment by fbaligand** [comment]
Which enhanced-table plugin version do you use? 1.5.0?

**Comment by ahkumar** [comment]
I used latest version from git clone 1.5.0; I think that was just an accident me using the wrong file. After I used the specific v6.4.1 + 1.5.0 release of the plugin I was able to get it to install. Although as previously install always gets stuck at optimization of bundles which i have to cancel and then restart Kibana to see that plugin is available for use.

**Comment by fbaligand** [comment]
Hi,

To install the plugin on Kibana 6.4.1, I strongly recommend you to install the official package provided in v1.5.0 release, specifically for Kibana 6.4.1:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.5.0/enhanced-table-1.5.0_6.4.1.zip

If you clone from master, it will not work on Kibana 6.4.1. Nearly each minor Kibana has breaking changes.
So I have a branch for breaking Kibana minor version.

**Comment by fbaligand** [comment]
For info, I just tested this package on Kibana 6.4 and it works fine.

**Comment by fbaligand** [comment]
No updates for months, and question is answered. 
So I close the issue.
