### ISSUE TITLE
Add support for Kibana 7.4

### ISSUE THREAD

**Issue by ShellySingh1** [fbaligand/kibana-enhanced-table#69]
Hi,
I am trying to install on Kibana 7.4. I am using the version 1.5.0 which is tested for Kibana 7.3. I am running into below issue - 
After downloading the zip, I changed the version in package.json to match my Kibana version. I get a successful installation message. But when I start kibana i get a series of errors as below - 

 ********************
FATAL  Error: Optimizations failure.
   2329 modules

    ERROR in ./plugins/enhanced-table/public/enhanced-table-vis-controller.js
    Module not found: Error: Can't resolve 'ui/notify/notifier' in 'C:\elk\OSS\k
ibana-7.4.0-windows-x86_64\plugins\enhanced-table\public'

    ERROR in ./plugins/enhanced-table/public/enhanced-table-vis-controller.js
    Module not found: Error: Can't resolve 'ui/vis/agg_config_result' in 'C:\elk
\OSS\kibana-7.4.0-windows-x86_64\plugins\enhanced-table\public'

    ERROR in ./plugins/enhanced-table/public/enhanced-table-response-handler.js
    Module not found: Error: Can't resolve 'ui/vis/agg_config_result' in 'C:\elk
\OSS\kibana-7.4.0-windows-x86_64\plugins\enhanced-table\public'

    ERROR in ./plugins/enhanced-table/public/paginated_table/rows.js
    Module not found: Error: Can't resolve 'ui/vis/agg_config_result' in 'C:\elk
\OSS\kibana-7.4.0-windows-x86_64\plugins\enhanced-table\public\paginated_table'

    ERROR in ./plugins/enhanced-table/public/paginated_table/paginated_table.js
    Module not found: Error: Can't resolve 'ui/vis/agg_config_result' in 'C:\elk
\OSS\kibana-7.4.0-windows-x86_64\plugins\enhanced-table\public\paginated_table'

 ********************

I am sure I am doing something wrong. But I am unable to figure out what I am doing wrong. Help is most appreciated.

**Comment by fbaligand** [comment]
Hi,

As usual, each Kibana minor version brings some breaking changes for plugins.
As you maybe noticed, the last published version for enhanced-table supports Kibana 7.3, but not 7.4.
There's some work to do on the plugin to be compatible with Kibana 7.4.
I'm currently working on it and will publish it soon!
When next enhanced-table version will be available, I will add a comment here.
Stay tuned :)

**Comment by ShellySingh1** [comment]
@fbaligand, Thanks for your response. I will roll back to 7.3 for now and use the plugin.

**Comment by fbaligand** [comment]
enhanced-table v1.6.0 is out! With support for Kibana 7.4!
You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.6.0
