### ISSUE TITLE
Which version for Kibana 5.6.2

### ISSUE THREAD

**Issue by karnamonkster** [fbaligand/kibana-enhanced-table#7]
Hello,
Could you please guide me to the available releases which can be use with Kibana 5.6.2?

**Comment by fbaligand** [comment]
Hello,

Indeed, currently there is no version for kibana 5.6.2. 
Tonight, I will release it and give you the link here.

**Comment by karnamonkster** [comment]
Thanks so much

**Comment by fbaligand** [comment]
I just released enhanced-table 0.2.0 for Kibana 5.5.1, 5.5.2, 5.5.3, 5.6.0, 5.6.1 and 5.6.2 !

You can find all these releases here : 
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v0.2.0

Hope you will enjoy !
Fabien

**Comment by karnamonkster** [comment]
Thanks so much , let me get it added and let you know how that works . 
Please close the issue 

Thanks again
