### ISSUE TITLE
Feature-request: add option for alternating row/column color

### ISSUE THREAD

**Issue by osckal** [fbaligand/kibana-enhanced-table#70]
it would be great to have alternating color option (customizable colors) to improve readability. lots of columns and rows tends to be difficult to see.

**Comment by mordekasg** [comment]
Is it duplicate of #58?

**Comment by fbaligand** [comment]
@mordekasg 
No. #58 asks a bg color if a scripted condition is met. 
Here, it is static striped rows (and cols)

**Comment by fbaligand** [comment]
Hi, great news! Enhanced Table plugin v1.8.0 is out with a new option "Striped rows"!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.8.0
