### ISSUE TITLE
Remove duplicates from a top hit metric

### ISSUE THREAD

**Issue by josephja** [fbaligand/kibana-enhanced-table#71]
Just wondering if there is an easy way to remove the duplicates from a top hit metric in an enhanced table ?

**Comment by josephja** [comment]
Thanks @fbaligand

**Comment by fbaligand** [comment]
Hi @josephja 
enhanced-table v1.7.0 is out with a new `uniq` function that solves your need!
You can now add a computed column like that:
`join(',', uniq(col['top_hits_col']))`

You can even sort the values:
`join(',', sort(uniq(col['top_hits_col'])))`
