### ISSUE TITLE
Error on refreshing

### ISSUE THREAD

**Issue by 0asp0** [fbaligand/kibana-enhanced-table#73]
Hi,

I am using Version 1.6.0 with kibana 7.4.2

config looks like this:
![image](https://user-images.githubusercontent.com/25737721/68464938-c91c5c00-0211-11ea-9772-9a329f5d6f2e.png)

![image](https://user-images.githubusercontent.com/25737721/68465019-ee10cf00-0211-11ea-898c-04306964b97b.png)

I encounter an rendering bug, which often does not render the table after changing the sort. Sometimes it does not render after refresh. Occurs in visalization and dashboard view.

When I am in dashboard's edit mode it renders again after moving the table.

![rendering bug enhanced table](https://user-images.githubusercontent.com/25737721/68465473-d9810680-0212-11ea-9278-eff2d5308d80.gif)

Clicking on refresh again does help in dashboard, but not in visualizations. If refreshing in viz, it renders and then clears the screen again. Saving helps in viz.

Occurs in Firefox and Chromium based browser.
Please fix it, your nice plugin is currently not usable for my usecase :(

**Comment by fbaligand** [comment]
Hi,

Well, I just tried to reproduce your issue, but didn't managed to.
I mean: it works fine for me with similar table than yours:

![image](https://user-images.githubusercontent.com/3750300/68487964-5c6e8500-0244-11ea-97f5-29adbf36a7b3.png)

**Comment by fbaligand** [comment]
Do you have some error logs in browser console ?

**Comment by 0asp0** [comment]
No, I don't have any errors in console.
I am not sure if every time, but sometimes the rendering shows up a (long) while later.

But in inspect the data is fetched quite fast:
![image](https://user-images.githubusercontent.com/25737721/68577905-45f94100-0471-11ea-8db3-1c85a4290f6b.png)

Is there any intensive post processing done in the plugin / browser after the results are fetched?
I also noticed that if re-order one column, that elasticsearch is queried for the data again. But for searching (search bar of the plugin) we have all data in cache so we do not need to fetch it again.

Can I enable any plugin debugging to see, when times of:
- data fetching done
- postprocessing done
- start rendering
- finished rendering?

**Comment by fbaligand** [comment]
Hi,

Thanks for trying to debug the issue. 
Unfortunately, currently, there is no mean to activate debug logs. 

Yes, there are some post process after getting data. This is precisely what plugin brings. 

Concerning es request done at each time, since 7.3, I have to get elasticsearch data at each rendering, to get “total” meta-info. 
But there’s probably way to optimize code to avoid elasticsearch data reload.

**Comment by fbaligand** [comment]
Hi,

New version 1.7.0 should fix the issue!
Give it a try :)
