### ISSUE TITLE
Add support for 7.5

### ISSUE THREAD

**Issue by YoavCohen** [fbaligand/kibana-enhanced-table#74]
Hi,

So a new Kibana version released so I wonder if you can add a support for it.

Thanks!!

**Comment by fbaligand** [comment]
Hi, I plan to add 7.5 compatibility

**Comment by YoavCohen** [comment]
Thanks!

**Comment by rljie** [comment]
when

**Comment by fbaligand** [comment]
I can’t give you a date. 
But I’ll notify here when it’ll be available,

**Comment by markusTh83** [comment]
+1

**Comment by qakart** [comment]
I am also waiting for this release , please let know if you need any help

**Comment by fbaligand** [comment]
Hi,

If you're ready to, I'm open to a pull request!

**Comment by MrGaoandLin** [comment]
i am also waiting for release! thanks

**Comment by fbaligand** [comment]
I currently try to add 7.5 compatibility. 
Unfortunately, as usual, there are several breaking changes in Kibana 7.5, not easy to fix. I try to get help from Kibana core team. 
If someone wants to help, don’t hesitate to contact me ;)

**Comment by MrGaoandLin** [comment]
> I currently try to add 7.5 compatibility.
> Unfortunately, as usual, there are several breaking changes in Kibana 7.5, not easy to fix. I try to get help from Kibana core team.
> If someone wants to help, don’t hesitate to contact me ;)

I can do something if you still need help, how to contact you?

**Comment by fbaligand** [comment]
Hi @MrGaoandLin, 
I solved some breaking changes, but there's still stuff to do to achieve 7.5 compatibility.
So help is welcome :)

You can join me by email.
You can find my email on my GitHub home page:
https://github.com/fbaligand/

**Comment by swathichowdaryg** [comment]
+1, Waiting for this release, Thanks :)

**Comment by fbaligand** [comment]
Hi guys,

Good news: enhanced-table v1.7.0 is out with Kibana 7.5 compatibility!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.7.0

**Comment by markgaolei** [comment]
Great, thank you very much.


Mark
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fabien Baligand"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 上午6:13
收件人:&nbsp;"fbaligand/kibana-enhanced-table"<kibana-enhanced-table@noreply.github.com&gt;;
抄送:&nbsp;"七分醉意"<178000406@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fbaligand/kibana-enhanced-table] Add support for 7.5 (#74)




Hi guys,
 
Good news: enhanced-table v1.7.0 is out with Kibana 7.5 compatibility!
 https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.7.0

**Comment by fbaligand** [comment]
Happy that you appreciate:)
