### ISSUE TITLE
Feature-Request: Add the row numbers

### ISSUE THREAD

**Issue by fstepho** [fbaligand/kibana-enhanced-table#76]
Add an option to show a column indicating the number of the row . Like this : 

<img width="615" alt="row number" src="https://user-images.githubusercontent.com/13305201/71495442-1d28e180-284e-11ea-8d74-740301efbbfd.png">

**Comment by fstepho75** [comment]
+1

**Comment by fstepho** [comment]
+1

**Comment by ganesh-s05** [comment]
+1

**Comment by fbaligand** [comment]
Do you want that this column is accessible by computed columns?
I mean, using `col0` reference in formula.

**Comment by ganesh-s05** [comment]
@fbaligand - I am not sure if a column reference is needed. Having a reference with column will make the row numbers dependable. So, is it possible to just display a row number aka. Serial Number ?

**Comment by fbaligand** [comment]
Yes, it is possible. That’s why I ask the question ;)
It depends if I add the the row number column after or before computed columns are processed.

**Comment by ganesh-s05** [comment]
Yes. (My Thoughts) With my limited experience, I think it's OK to add before the computed columns are processed, because it won't change the number of rows that are in the table. If someone uses computed columns that would only change the number of columns but not the rows.

**Comment by fbaligand** [comment]
Well, if you don’t need to reference row number column in a computed column, then I will add row number column after that computed columns are processed. 
Is it ok for you?

**Comment by ganesh-s05** [comment]
Yes. I'm OK with that.

**Comment by ganesh-s05** [comment]
Hi @fbaligand , Out of curiosity.. can we expect this with next release?

**Comment by fbaligand** [comment]
I plan to add the feature on next release, as several people are interested.

**Comment by ganesh-s05** [comment]
Great... thank you! I will await

**Comment by fbaligand** [comment]
Good news: enhanced table v1.10.0 is out with this feature request implemented and more enhancements!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.10.0
