### ISSUE TITLE
Calculate difference in time between two documents in same bucket

### ISSUE THREAD

**Issue by lancemitchell** [fbaligand/kibana-enhanced-table#77]
I am struggling implementing the functionality below either with using (1) this plugin or (2) painless and scripted fields, to capture the timestamp of the last doc where a field value changed from the current doc, so that I can show the difference in time.

For example below, show the time difference since the status field changed to UP in the Name field bucket??

Can anyone help  point the way?

![image](https://user-images.githubusercontent.com/18689906/71807167-a6070080-3038-11ea-9cc7-c259cb4b714c.png)

**Comment by fbaligand** [comment]
Well, if "start" and "end" dates for your difference calculation are in different documents, Kibana scripted fields won't help, because they only work on one document.

With enhanced-table, you can do this:
- a "Split rows" bucket per name 
- a "Top Hit" metric giving the date field, ordered by date "asc" ("start" date)
- a "Top Hit" metric giving the date field, ordered by date "desc" ("end" date)
- a computed column, that calculates date difference: col2 - col1

**Comment by fbaligand** [comment]
Question is answered, and there is no feedback since more than a month.
That's why I close the issue.

**Comment by lancemitchell** [comment]
I am so sorry,...I meant no disrespect.... I did not see, or missed the notification of your answer & i do not visit Github often...I thank you for responding and I will try your suggestion!

Much Thanks

**Comment by fbaligand** [comment]
No problem :)

**Comment by lancemitchell** [comment]
Thanks
BTW. Do you support Elastic Cloud? 
Before I spend precious time figuring out how to to perform a local install on Cloud, 
I was hoping you had already vetted your plugin with that platform?

**Comment by fbaligand** [comment]
Well, actually, Elastic Cloud does not support Kibana community plugins.

**Comment by lancemitchell** [comment]
Darn! They had this plugin UI interface, so I was hoping....Thanks

**Comment by fbaligand** [comment]
Don't hesitate to contact Elastic support about that, and to argue you are very interested.
If clients ask for this feature, it will help to add the feature to Elastic Cloud.

**Comment by fbaligand** [comment]
On the contrary, you can install a Elasticsearch community plugin on Elastic Cloud

**Comment by lancemitchell** [comment]
OK. will try it...I'm using Open Distro as STAGING and Cloud as a PRODUCTION environment. It would be awesome to use your plugin on both

**Comment by fbaligand** [comment]
Indeed!

**Comment by fbaligand** [comment]
@lancemitchell 
For info, ECE 2.5 is out with support for kibana community plugins.
