### ISSUE TITLE
Kibana enhanced table visualization error

### ISSUE THREAD

**Issue by swatidupare** [fbaligand/kibana-enhanced-table#78]
Hi,
I am getting below error,as col4 is dynamic .sometimes I will get value of col4 or some times not.
How can I handle this dynamically.

"In computed column ‘col1 + col2 +col3 + col4’, column number 4 does not exist"

**Comment by fbaligand** [comment]
I guess you use 'Split Cols' feature?
If so, a good way to have a fixed column count is to use a "Filters" aggregation, with one filter per wished column. For example, a filter "loglevel:ERROR", and another "loglevel:INFO".
Doing so, even if you have no data with "loglevel:ERROR", the column is still here with count=0.
So, you have a fixed column count.

**Comment by fbaligand** [comment]
Question is answered and there is no feedback since more than a month.
That's why I close the issue.
