### ISSUE TITLE
Top Hits allows only number fields

### ISSUE THREAD

**Issue by GeorgeRD** [fbaligand/kibana-enhanced-table#8]
Hi fbaligand,

Great plugin, the split cols feature is really useful. I am using version 6.2.3 and I noticed that the top hits aggregation allows only numbers, while the data table allows for more data types, inc. string. Is there any reason for this restriction? Is there any workaround to define top hits with string data type?

Many thanks in advance.

**Comment by fbaligand** [comment]
Hi @GeorgeRD,

Well, it's actually a voluntary restriction in 'Top Hits' aggregation (in kibana-core code) : the string fields are possible only for visualizations named 'table' and 'metric'. 
So, not for 'enhanced-table' ... :(

That said, there is a workaround that I just tested successfully : 
- edit $KIBANA_HOME/optimize/bundles/commons.bundle.js
- replace `"table"===vis.type.name` by `"table"===vis.type.type`
- reload Kibana in your browser and you're done ! (no Kibana server restart is necessary)

**Comment by GeorgeRD** [comment]
Hi @fbaligand ,

Many thanks for the immediate response. I tried the workaround, it requires one more addition. In the same file, i added the following: 
{display:"Concatenate",isCompatibleType:_lodash2.default.constant(!0),isCompatibleVis:function(name){return"metric"===name||"table"===name`||"enhanced-table"===name`)
This enables the plugin to return the Concatenate value in _Aggregate With_ dropdown list, otherwise you cannot proceed with entering a top hit aggregation as no value appears.

I will close the issue as resolved, many thanks again!

**Comment by fbaligand** [comment]
Nice to see your problem is solved !

**Comment by fbaligand** [comment]
Hi,

Since version 1.4.0 (just released), this issue is now fixed!

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.4.0
