### ISSUE TITLE
KIbana Data Table visualization for raw documents 

### ISSUE THREAD

**Issue by LaygoMaricar** [fbaligand/kibana-enhanced-table#80]
Hi team, 

I just want to ask if there's a plan to create a new data table that does not require to aggregate the data?

**Comment by fbaligand** [comment]
Well, yes, I already thought about to create a similar table plugin but to display raw documents, instead of aggregations.

That said, you can already do that, using terms aggregation on id for example.

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with a brand new visualization named “Document Table”, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
