### ISSUE TITLE
Percentiles metric causes table not to render

### ISSUE THREAD

**Issue by nicknickel** [fbaligand/kibana-enhanced-table#82]
We're on Kibana 7.5.1 and Enhanced Tables 1.7.0 and are trying to set up an enhanced table visualization with percentiles as one of the metrics. However, when the percentiles metric is added and enabled, the table doesn't render. Inspecting the chrome javascript console, there are a few error messages that are thrown. If the percentiles metric is disabled (but still added), the table renders. I have not tried any other browsers.

![image](https://user-images.githubusercontent.com/11166962/73566153-c1dba780-4428-11ea-8696-f6ad4e5bc9c0.png)

**Comment by fbaligand** [comment]
Hi, could you also take a screenshot of your Options tab please?

**Comment by nicknickel** [comment]
Here is the Options tab with expanded computed columns:


![image](https://user-images.githubusercontent.com/11166962/73667150-75cb7580-4669-11ea-89f4-9e4f560202b7.png)
![image](https://user-images.githubusercontent.com/11166962/73667184-824fce00-4669-11ea-8660-cec1edd0493b.png)
![image](https://user-images.githubusercontent.com/11166962/73667197-8aa80900-4669-11ea-9979-c30d47e44f48.png)
![image](https://user-images.githubusercontent.com/11166962/73667220-9267ad80-4669-11ea-932b-1b3629fb2573.png)
![image](https://user-images.githubusercontent.com/11166962/73667229-97c4f800-4669-11ea-91e1-180a7f05d7af.png)
