### ISSUE TITLE
Unable to Filter Data on Enhanced Table

### ISSUE THREAD

**Issue by apple477373** [fbaligand/kibana-enhanced-table#84]
ELK Version: 7.5.1
Enhance Table Plugin File: https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.7.0/enhanced-table-1.7.0_7.5.1.zip

Recently I have upgraded ELK to 7.5.1 and I upgraded Enhanced table with the latest version, but I found an issue with the plugin.

I have created an Index pattern without any custom index pattern ID by selecting "I don't want to use any time filter", when I created the report on this index, I can't filter the data and the filter is not applying, but when I filter data with @timestamp as custom index pattern I'm able to filter the data.

I haven't faced this problem in 6.4.3 version, but I'm facing this now. Kindly help me to solve this

**Step 1: I have created an index pattern

Step 2: Here I have selected I don't want to use Time Filter and created index pattern

Step 3: The index got created with out any time filter

Step 4: Now I created a table viz. with names and their counts

Step 5: In edit mode, the filters are working properly

Step 6: When I moved the viz in to a dashboard, the filter is not working properly

Step 7: Now, I deleted the index pattern and created a new index pattern with @timestamp as the time filter

Step 8: The index got created with @timestamp as the time filter

Step 9: I created the same viz in Step 4 and moved to dashboard and applied the filter, then the filter is applying properly.**

Hope it's clear the issue I'm facing. Please check and help me to fix this.

Thanks & Regards

**Comment by fbaligand** [comment]
Hi @apple477373,

After some tests, I realized that it is actually a Kibana bug, that is fixed in Kibana 7.5.2, both for enhanced-table plugin and standard visualizations.

So I invite you to upgrade your Kibana version.

And so, I close this issue, as it is not a enhanced-table issue.
