### ISSUE TITLE
change the order of the columns

### ISSUE THREAD

**Issue by umarfachreza** [fbaligand/kibana-enhanced-table#86]
hi i had make the table like :

Partner | Col0 | Col1 | Col2 | Col3 | computed col
-- | -- | -- | -- | -- | --
AA | 67 | 45 | 11 | 55 | 0.308988764
AB | 11 | 76 | 37 | 36 | 0.225
AC | 82 | 28 | 98 | 73 | 0.259786477
AD | 62 | 35 | 87 | 87 | 0.32103321

can i change the order of the columns table to 

Partner | Col0 | computed col | Col1 | Col2 | Col3
-- | -- | -- | -- | -- | --
AA | 67 | 0.308988764 | 45 | 11 | 55
AB | 11 | 0.225 | 76 | 37 | 36
AC | 82 | 0.259786477 | 28 | 98 | 73
AD | 62 | 0.32103321 | 35 | 87 | 87

thnks before ...

**Comment by fbaligand** [comment]
No, this is not possible.
But you can create 3 computed columns that just reference col1, col2 and col3, and then hide original col1, col2 and col3 columns

**Comment by fbaligand** [comment]
A last update, with version 1.8.0, you can now have “filter” links on computed columns that simply reference a column: `col0`
That allows you to have the column order that you want, without loosing filter capabilities

**Comment by fbaligand** [comment]
Question is answered and no feedback since one month, so I close the issue.

**Comment by katherinemunro** [comment]
Hi fbaligand, could you please provide more detail in your answer? I have the same question as OP (although I have TWO computed columns at the end of my table which should actually come earlier on, instead of just one), and I can't work out how to use your advice to achieve this.

As an example, say I have the computed column col['Computed A'] and I want it to follow col['Col A'] and I have col['Computed B'] and want it to follow col['Col B']. How can I rearrange to make this happen?

**Comment by fbaligand** [comment]
Hi,

You can do it like this:
- computed column 'Computed A'
- then a computed column, with formula: `col['Col A']` (so it is a computed column that just display 'Col A' column content as is)
- computed column 'Computed B'
- then a computed column, with formula: `col['Col B']` (so it is a computed column that just display 'Col B' column content as is)
- and finally, in hidden columns option: `Col A,Col B`

**Comment by tomryanx** [comment]
My problem is a bit tangential, but basically gets me here.

I am trying to rename the first column when using a `Filters` agg. Adding a computed column that simply equals `col['filters']` allows me to get the name I want (`Priority`, in this case), but I need the column to be on the left, not the right.

I also use a terms agg to split columns, and the number of terms that comes back is somewhat variable (6 or less). Because the number of columns changes, I can't just replace them all with computed columns.

Thoughts? If there's another way to change the 'filters' column name, I'd be happy to do that. I mucked around in `public/agg_types/buckets/filters.js` but I only succeeded in breaking stuff.

**Comment by fbaligand** [comment]
Hi,

If you just want to rename your "Filters" column label, it is possible using Kibana core, with a label for each filter.

See this screenshot;
![image](https://user-images.githubusercontent.com/3750300/81581809-85b4cd00-93af-11ea-8df1-432d72b41143.png)

**Comment by tomryanx** [comment]
That changes each filter's label, but not the label of the column itself

![filters](https://user-images.githubusercontent.com/10695410/81595905-8fb5ea80-9406-11ea-828d-c05ba2f690eb.png)

There's a neglected (but open) issue in Kibana regarding the same point https://github.com/elastic/kibana/issues/26737

**Comment by fbaligand** [comment]
Ah OK. 
So yes, you can do that with enhanced table. 
You add a computed column with “col0” as formula. Then you set “0” in “hidden columns”

**Comment by tomryanx** [comment]
Yep. Except the new column is on the right, and I need it on the left. Just like this thread was originally about ;)

**Comment by fbaligand** [comment]
Indeed, this is not really convenient.
For now, the only way is to create a computed column, for each "normal" column at the right of "Filters" bucket.

But, I admit that this would a nice enhancement.

**Comment by umarfachreza** [comment]
hi fbaligand, I had issue, if i want to change order columns but its a date histogram columns, we cant create computed columns that just reference the col1 cause we didnt know what date will the column label, can we reference col label too?

![image](https://user-images.githubusercontent.com/54354227/92424392-72bfd700-f1ae-11ea-8f35-693159715f6d.png)

want to be this

![image](https://user-images.githubusercontent.com/54354227/92424631-0db8b100-f1af-11ea-9b02-e1095899408c.png)

**Comment by fbaligand** [comment]
Hi,

First, I guess that you use "split cols" bucket, right?
Then, if I understand well, you want a computed column per split column, right?

If so, I advice you to check "computed/hidden columns per split column" option and only one computed column. The computed column formula references col0 (if you don't have "split rows" bucket).

**Comment by fbaligand** [comment]
By the way, you can reference a column by its label: col['label']

**Comment by umarfachreza** [comment]
> Hi,
> 
> First, I guess that you use "split cols" bucket, right?
> Then, if I understand well, you want a computed column per split column, right?
> 
> If so, I advice you to check "computed/hidden columns per split column" option and only one computed column. The computed column formula references col0 (if you don't have "split rows" bucket).

no i didnt use split cols, cause this count % increase data this day per data yesterday, its cant using split cols by date histogram.

or can we get data yesterday for date today?

and i mean get the label of col, example col0 label is "2020-09-01" than in computed label i get thats label

**Comment by fbaligand** [comment]
Thanks for the precision.
Could you tell me what formula you use currently?

**Comment by umarfachreza** [comment]
> Thanks for the precision.
> Could you tell me what computed column formula you use currently?

![image](https://user-images.githubusercontent.com/54354227/92550423-999d0c80-f285-11ea-9afd-9a8dadffdb06.png)


in computed column i use formula (col1-col2)/col1 for H+1 %, (col2-col3)/col2 for H+2 %, (col3-col4)/col3 for H+3 %, (col4-col5)/col4 for H+4 %, (col5-col6)/col5 for H+5 %, and (col6-col7)/col6 for H+6 %.so we can see the increase data per day,

can we use "computed/hidden columns per split column" for this?

**Comment by fbaligand** [comment]
Hi,

Given your formula, I guess that you have also first 2 columns that you hide, that are "Split Rows" bucket, right?
For your formula, when I see "H+1" column value, it seems to be: `(col3-col2) / col2`, right?

I made some tests, and found a way that should answer your need!

This is how you can do:
- first, on Data tab, add a "Serial Diff" in Metrics. The custom metric inside is the same metric that the one you currently use (probably Count).
- enable  "Computed/Hidden cols per split col"
- add only one computed column with this settings:
-- label: H+1
-- formula: `diff = col(3) ? col(3) : 0; diff / (col2 - diff)`
-- pattern : 0.00%
- in "Hidden columns", set `3`

You're done!

**Comment by fbaligand** [comment]
Hi, 
I just published Enhanced Table v1.11.0! And it includes a new feature named "Custom column position".
This new setting enables you to define the target position of the computed column. And it can be any position, including 0!

More info on release here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.11.0
