### ISSUE TITLE
Support Kibana 7.6 version

### ISSUE THREAD

**Issue by Nathlmt** [fbaligand/kibana-enhanced-table#87]
Kibana introduces 7.6 version, 3 days ago. Please support this version . Thank you

**Comment by fbaligand** [comment]
Hi, this is planned for next release.
One or two weeks depending work to do to be compatible with kibana 7.6

**Comment by mikida12** [comment]
Hi,

any news on this?

Thanks

**Comment by fbaligand** [comment]
I’m working on it. 
There are several breaking changes in Kibana 7.6, so there is stuff to do in enhanced table plugin.

**Comment by anush0247** [comment]
+1 for this support

**Comment by fbaligand** [comment]
Hi, great news! Enhanced Table plugin v1.8.0 is out with Kibana 7.6 support!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.8.0
