### ISSUE TITLE
Split Cols - date histogram - interval is not sorted correctly

### ISSUE THREAD

**Issue by tonykoval** [fbaligand/kibana-enhanced-table#89]
Hi,
we found a bug (attached image), where 0 values for the first row are shifted to end and also empty results are missed.
![bug1](https://user-images.githubusercontent.com/1135652/74654474-a68fcc80-518a-11ea-8166-49141d98e8f0.png)

Kibana version (7.5.2) and plugin version (master branch - 1.7.0)

Tony

**Comment by shobhitsinghal624** [comment]
We are also facing the same issue. Any pointers on how to fix this?

**Comment by fbaligand** [comment]
Hi,

Here's a tip to fix the issue:
- in "date histogram" bucket, click on "Advanced", and fill this:
`{"min_doc_count":0}`

**Comment by tonykoval** [comment]
It works! Thank you :)

**Comment by fbaligand** [comment]
As question is answered, I close the issue.
