### ISSUE TITLE
likely newbie question

### ISSUE THREAD

**Issue by mdnuts** [fbaligand/kibana-enhanced-table#9]
I did a manual install of the plugin and it responded back that it installed okay.  I run a list of plugins and the enhanced version is there (for 6.3).  

But it doesn't show in visualization tab, I cleared browser cache, restarted browser, restarted kibana and it won't show.

any idea?

**Comment by fbaligand** [comment]
If by manual install you mean a manual unzip into Kibana’s « plugins » folder, you have also to delete « optimized » folder.

**Comment by mdnuts** [comment]
I should have noted it.  I did the zip install.
##kibanahome##/bin/kibana-plugin install enhanced-table...

**Comment by fbaligand** [comment]
If you installed the plugin using « kibana-plugin » command, this is the standard command which should create plugins/enhanced-table folder and then regenerate « optimized » folder. 
Do your install was more than 1-minute long ?
Is the optimized content files are newer than your install date ?
When you restart kibana, go to kibana through your browser, and then  create a new visualization, is there  a new element named « Enhanced Table » ?

**Comment by mdnuts** [comment]
Okay thank you, I'll check for the folder.  When I run kibana-plugin list
it shows it there but nothing in visualization.

**Comment by fbaligand** [comment]
Could you provide « package.json » file content present in plugins/enhanced-table folder ?

**Comment by mdnuts** [comment]
I can take a look when I get back to work.  I probably should have just
waited until Monday to post about it but it was bugging me that I couldn't
get to view it

**Comment by fbaligand** [comment]
Nice to see you finally managed to install the plugin !
Hope you will enjoy it ! :)
