### ISSUE TITLE
Split Cols - date histogram - values are not correct

### ISSUE THREAD

**Issue by tonykoval** [fbaligand/kibana-enhanced-table#90]
Hi,
we encountered a strange bug, where some values (counts) are divided by 2. I attached response from elasticsearch and also screenshot.
![bug2](https://user-images.githubusercontent.com/1135652/74664609-56226a00-519e-11ea-838d-deffbb87ff1e.png)

[response.txt](https://github.com/fbaligand/kibana-enhanced-table/files/4214389/response.txt)

Kibana version (7.5.2) and plugin version (master branch - 1.7.0)

Tony

**Comment by fbaligand** [comment]
Indeed, as you say, that's a strange bug...
Can you tell me your Kibana version and enhanced table plugin version ?

**Comment by tonykoval** [comment]
Kibana version is 7.5.2 and master branch

**Comment by fbaligand** [comment]
master branch?

Did you try with last official release?
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.7.0/enhanced-table-1.7.0_7.5.2.zip

**Comment by tonykoval** [comment]
Yes, I tried and the same behavior.

**Comment by fbaligand** [comment]
OK, thanks for the info.

**Comment by fbaligand** [comment]
Hi,

I just tried to reproduce your issue, with Kibana 7.5.2, enhanced table v1.7.0, and Kibana "Sample web logs" data, and it worked fine.
So I don't manage to reproduce your issue.

Here's the screenshot:
![image](https://user-images.githubusercontent.com/3750300/74732207-09946880-524a-11ea-8336-05a67d1520cf.png)

**Comment by tonykoval** [comment]
Yes, I couldn't reproduce too with "Sample web logs". I created a scripted field timestamp the same as @timestamp field and now it works (see gif)
![bug](https://user-images.githubusercontent.com/1135652/74733574-e28b6600-524c-11ea-88dc-6d8ccd17d137.gif)

I think we can close this issue.

**Comment by fbaligand** [comment]
OK.
Nice to see that you find a way to make it work!
So I close the issue.
