### ISSUE TITLE
Testing column existence in a computed column formula

### ISSUE THREAD

**Issue by cerutidavide** [fbaligand/kibana-enhanced-table#95]
Hi, I have a computed column that perform the sum of col0,col1 and so on.
Unfortunately my columns come from a split column so it's dynamic and it could happen that one or more column is not present.
Is there a way to sum all existing columns? Or in other words is there a way to test existence od a specific column by its label or its index?
Thanks
Davide

**Comment by fbaligand** [comment]
Hi,
Currently, there is no such way to do this. 
But this is an interesting enhancement. 
I will plan to add a “colExists” method that takes a label as a parameter. 

That said, a way to have a fixed number of columns when using a  “split cols” bucket, is to use “Filters” aggregation. 
You can add a filter for each column you  wish: one with “my_field:val1”, another with “my_field:val2”, etc...
Doing so, even if you have no document with “my_field:val1”, the column will still be present.

**Comment by valentinMERCIER** [comment]
+1 
@fbaligand : thx for the component

**Comment by fbaligand** [comment]
Hi,

Enhanced table plugin 1.9.0 is out with `col(indexOrLabel, defaultValue)` function, and more features!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.0
