### ISSUE TITLE
Installation issue on Kibana v7.6.0

### ISSUE THREAD

**Issue by arcadas** [fbaligand/kibana-enhanced-table#96]
Hello!

Thank you for this plugin. Could you help me in the following issue?

I have tried install this plugin, but I got the following error:

```sh
/usr/share/kibana $
sudo -u kibana ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.8.0/enhanced-table-1.8.0_5.5.0.zip

 ERROR  unknown command install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.8.0/enhanced-table-1.8.0_5.5.0.zip

  Usage: bin/kibana-plugin [command] [options]

  The Kibana plugin manager enables you to install and remove plugins that provide additional functionality to Kibana

  Commands:
    list  [options]                 list installed plugins
    install  [options] <plugin/url> install a plugin
    remove  [options] <plugin>      remove a plugin
    help  <command>                 get the help for a specific command
```

**Comment by fbaligand** [comment]
Well,
Weird error, because error says that you should do exactly the command you did!

My best guess would be : 
instead of using sudo, can you login as "kibana", and then do "./bin/kibana-plugin install https://..."
Another idea is to first download the plugin (using wget for instance), and then launch : 
 sudo -u kibana ./bin/kibana-plugin install file:///path/to/enhanced-table-1.8.0_5.5.0.zip

Anyway, issue is more on Kibana plugin install tool than plugin itself.

**Comment by arcadas** [comment]
Thank you for your reply.

I can not switch to kibana user:
```sh
su kibana
This account is currently not available.
```
With downloaded plugin:
```sh
/usr/share/kibana $
sudo -u kibana ./bin/kibana-plugin install enhanced-table-1.8.0_5.5.0.zip
Attempting to transfer from enhanced-table-1.8.0_5.5.0.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/enhanced-table-1.8.0_5.5.0.zip/enhanced-table-1.8.0_5.5.0.zip-7.6.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```
My system:
```sh
CentOS Linux release 7.7.1908 (Core)
Kibana: v7.6.0
```
Maybe you are right, and it is a Kibana plugin install tool issue, but I have tried an other plugin, and the installation process started:
```sh
/usr/share/kibana $
sudo -u kibana ./bin/kibana-plugin install https://github.com/flexmonster/pivot-kibana/releases/download/v1.21/flexmonster_pivot-v1.21.zip
Attempting to transfer from https://github.com/flexmonster/pivot-kibana/releases/download/v1.21/flexmonster_pivot-v1.21.zip
Transferring 14172 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin flexmonster_pivot [7.3.2] is incompatible with Kibana [7.6.0]"

```

**Comment by fbaligand** [comment]
First, as explained here (https://github.com/fbaligand/kibana-enhanced-table#install), you have to choose the right plugin package for your Kibana version.

So for instance, "enhanced-table-1.8.0_5.5.0.zip" is plugin version 1.8.0 for Kibana 5.5.0.

Then, if plugin installation by url works nice for another plugin, indeed, there is no reason that it does not work for enhanced-table.

So, can you try this:
`sudo -u kibana ./bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.8.0/enhanced-table-1.8.0_7.6.0.zip`

**Comment by arcadas** [comment]
Thank you very much! It is working now.

**Comment by fbaligand** [comment]
Nice!
