### ISSUE TITLE
Question : how to concatenate 2 columns in a new computed column ?

### ISSUE THREAD

**Issue by leprince-martine** [fbaligand/kibana-enhanced-table#97]
Hello. 

First, your plug-in is very useful for me, thank you very much :). 

I use Kibana 6.7 and Enhanced Table 1.8.0

My question is : 
I have 2 **numeric columns**. The first one **col2** contains Years (ex 2019), the second one **col3** contains Month numbers (ex 6).
I want to create a new computed string column containing Year+'-'+Month (ex 2019-06). I try many  things without success (for example col2+'-'+col3).

Can you help me please ?

**Comment by fbaligand** [comment]
To do concatenation, you have to use `||` operator.
For instance: `col0 || '-' || col1`

You can find whole expr-eval doc here (link is available in visualization editor view):
https://github.com/silentmatt/expr-eval#expression-syntax

**Comment by fbaligand** [comment]
Question is answered and there is no feedback since 3 months, so I close the issue.
